export const PREMIUM_COPY = {
  en: {
    title: "Premium subscription",
    subtitle: "Unlock all features of LetsBeParents",
    free: "Free",
    premium: "Premium",
    monthly: "1 month",
    quarterly: "3 months",
    monthlyPrice: "$29.99",
    quarterlyPrice: "$17.99",
    perMonth: "per month",
    billedQuarterly: "$53.99 billed quarterly",
    save: "Save 40%",
    likes: "Likes per day",
    directMessage: "Message without matching",
    likedMe: "See who liked you",
    visitors: "See profile visitors",
    videoCalls: "Video & audio calls",
    filters: "Advanced filters",
    priority: "Priority in catalog",
    included: "Included",
    notIncluded: "Not included",
    getMonthly: "Get 1 month for $29.99",
    getQuarterly: "Get 3 months for $53.99",
    alreadyPremium: "You're on the Premium plan",
    alreadyPremiumDesc: "Enjoy all premium features.",
    mobileTitle: "Subscribe in our iOS app",
    mobileBody:
      "We're rolling out payments carefully and haven't enabled web checkout yet. For now, Premium can only be activated through our iOS app — install it and your subscription will sync to the website automatically.",
    appStore: "Open in App Store",
    androidNote: "Android version is coming soon.",
    maybeLater: "Maybe later",
    paymentUnavailable: "Payment is not connected yet.",
  },
  ru: {
    title: "Premium-подписка",
    subtitle: "Откройте все возможности LetsBeParents",
    free: "Бесплатно",
    premium: "Premium",
    monthly: "1 месяц",
    quarterly: "3 месяца",
    monthlyPrice: "$29.99",
    quarterlyPrice: "$17.99",
    perMonth: "в месяц",
    billedQuarterly: "$53.99 за 3 месяца",
    save: "Экономия 40%",
    likes: "Лайков в день",
    directMessage: "Сообщения без совпадения",
    likedMe: "Кто поставил вам лайк",
    visitors: "Посетители профиля",
    videoCalls: "Видео- и аудиозвонки",
    filters: "Расширенные фильтры",
    priority: "Приоритет в каталоге",
    included: "Включено",
    notIncluded: "Не включено",
    getMonthly: "Получить 1 месяц за $29.99",
    getQuarterly: "Получить 3 месяца за $53.99",
    alreadyPremium: "У вас активен план Premium",
    alreadyPremiumDesc: "Все возможности Premium доступны.",
    mobileTitle: "Оформите подписку в приложении iOS",
    mobileBody:
      "Мы подключаем платежи постепенно, поэтому оплата на сайте пока недоступна. Сейчас Premium можно активировать только в приложении iOS — подписка автоматически появится на сайте.",
    appStore: "Открыть App Store",
    androidNote: "Версия для Android скоро появится.",
    maybeLater: "Может быть позже",
    paymentUnavailable: "Оплата пока не подключена.",
  },
  es: {
    title: "Suscripción Premium",
    subtitle: "Desbloquea todas las funciones de LetsBeParents",
    free: "Gratis",
    premium: "Premium",
    monthly: "1 mes",
    quarterly: "3 meses",
    monthlyPrice: "$29.99",
    quarterlyPrice: "$17.99",
    perMonth: "al mes",
    billedQuarterly: "$53.99 facturados trimestralmente",
    save: "Ahorra 40%",
    likes: "Me gusta por día",
    directMessage: "Mensajes sin coincidencia",
    likedMe: "Ver a quién le gustas",
    visitors: "Ver visitantes del perfil",
    videoCalls: "Videollamadas y llamadas",
    filters: "Filtros avanzados",
    priority: "Prioridad en el catálogo",
    included: "Incluido",
    notIncluded: "No incluido",
    getMonthly: "Obtener 1 mes por $29.99",
    getQuarterly: "Obtener 3 meses por $53.99",
    alreadyPremium: "Tienes el plan Premium",
    alreadyPremiumDesc: "Disfruta de todas las funciones Premium.",
    mobileTitle: "Suscríbete en nuestra app para iOS",
    mobileBody:
      "Estamos habilitando los pagos gradualmente y todavía no ofrecemos pagos en la web. Por ahora, Premium solo puede activarse en nuestra app para iOS y se sincronizará automáticamente con el sitio web.",
    appStore: "Abrir en App Store",
    androidNote: "La versión para Android llegará pronto.",
    maybeLater: "Quizá más tarde",
    paymentUnavailable: "El pago todavía no está conectado.",
  },
};
export const PREMIUM_ICONS = {
  heartIcon:
    '<svg class="action-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"></path></svg>',
  messageIcon:
    '<svg class="action-icon message-action-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7A8.38 8.38 0 0 1 4 11.5a8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5Z"></path></svg>',
  eyeIcon:
    '<svg class="action-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"></path><circle cx="12" cy="12" r="2.5"></circle></svg>',
  videoIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m22 8-6 4 6 4V8Z"></path><rect x="2" y="6" width="14" height="12" rx="2"></rect></svg>',
  slidersIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 4h-7"></path><path d="M10 4H3"></path><path d="M21 12h-9"></path><path d="M8 12H3"></path><path d="M21 20h-5"></path><path d="M12 20H3"></path><path d="M14 2v4"></path><path d="M8 10v4"></path><path d="M16 18v4"></path></svg>',
  starIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 2.5 2.9 5.9 6.5.9-4.7 4.6 1.1 6.5-5.8-3.1-5.8 3.1 1.1-6.5-4.7-4.6 6.5-.9L12 2.5Z"></path></svg>',
  smartphoneIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="2" width="14" height="20" rx="2"></rect><circle cx="12" cy="18" r="0.8" fill="currentColor" stroke="none"></circle></svg>',
  premiumCheckIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"></path></svg>',
  premiumXIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 6 6 18"></path><path d="m6 6 12 12"></path></svg>',
  closeIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 6 6 18"></path><path d="m6 6 12 12"></path></svg>',
};
