import { useEffect, useId, useRef, useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { createApiClient } from './api';
import { MemberError, MemberLoading, notifyMemberChanged, ownProfileData, useMemberResource } from './member-account';
import { Overlay } from './member-profile';
import { FLOW_COPY, TOOLS_CHOICES, TOOLS_COPY, TOOLS_ICONS, TOOLS_PICKERS, TOOLS_OPTIONS, TOOLS_LANGUAGES, TOOLS_CITY_TRANSLATIONS } from './member-tools-reference';
import { chooseFlow, countryLabel, fieldLabel, flowDraft, flowKind, imperialHeight, languageCode, languageLabel, list, matchingComplete, needsContact, row, stepComplete, text, totalSteps, type Flow, type Locale, type Matching, type Row } from './member-tools-model';
const api=createApiClient();
type Props={locale:Locale};
export function ToolsIcon({name}:{name:keyof typeof TOOLS_ICONS}) {const source=TOOLS_ICONS[name];return <svg className={source.match(/class="([^"]*)"/)?.[1]} viewBox="0 0 24 24" aria-hidden="true" dangerouslySetInnerHTML={{__html:source.replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'')}}/>;}
export function toolsError(error:unknown,fallback:string) {try {const data=JSON.parse(error instanceof Error?error.message:'');return typeof data.detail==='string'?data.detail:fallback;}catch{return fallback;}}
type Entry={value:string;label:string;placeId?:string};
function Picker({name,label,value,entries,locale,onChange}:{name:keyof typeof TOOLS_PICKERS.en;label:string;value:string;entries:Entry[];locale:Locale;onChange:(v:string)=>void}) {
 const [open,setOpen]=useState(false),[query,setQuery]=useState('');const ref=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),search=useRef<HTMLInputElement>(null),id=useId();
 const c=TOOLS_PICKERS[locale][name],visible=entries.filter(e=>e.label.toLocaleLowerCase().startsWith(query.trim().toLocaleLowerCase()));
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false);};document.addEventListener('pointerdown',outside);search.current?.focus({preventScroll:true});const selected=ref.current?.querySelector<HTMLElement>('[aria-selected="true"]'),list=ref.current?.querySelector<HTMLElement>('.profile-picker-list');if(selected&&list)list.scrollTop=Math.max(0,selected.offsetTop-list.offsetTop-list.clientHeight/2+selected.clientHeight/2);return()=>document.removeEventListener('pointerdown',outside);},[open]);
 const choose=(v:string)=>{onChange(v);setOpen(false);setQuery('');trigger.current?.focus({preventScroll:true});};
 return <div className="profile-picker" ref={ref} data-profile-picker={name} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);trigger.current?.focus({preventScroll:true});}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(!open){setOpen(true);return;}const items=[...ref.current!.querySelectorAll<HTMLButtonElement>('[role="option"]')],i=items.indexOf(document.activeElement as HTMLButtonElement),next=i+(e.key==='ArrowDown'?1:-1);items[(next+items.length)%items.length]?.focus();}if(e.key==='Enter'&&e.target===search.current&&visible.length){e.preventDefault();choose(visible[0].value);}}}>
  <button className="profile-picker-trigger" type="button" ref={trigger} aria-label={label} aria-haspopup="listbox" aria-controls={id} aria-expanded={open} onClick={()=>{setQuery('');setOpen(v=>!v);}}><span>{entries.find(e=>e.value.toUpperCase()===value.toUpperCase())?.label||c.select}</span><ToolsIcon name="chevronIcon"/></button>
  {open&&<div className="profile-picker-popover"><div className="profile-picker-search-wrap"><input ref={search} className="profile-picker-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={c.placeholder} aria-label={c.placeholder} autoComplete="off"/></div><div className="profile-picker-list" role="listbox" id={id} aria-label={label}>{visible.length?visible.map(e=><button className={`profile-picker-option${e.value===value?' selected':''}`} type="button" role="option" aria-selected={e.value===value} key={e.value} onClick={()=>choose(e.value)}><span>{e.label}</span>{e.value===value&&<span className="profile-picker-selected-mark"><ToolsIcon name="languageCheckIcon"/></span>}</button>):<p className="profile-autocomplete-empty">{c.empty}</p>}</div></div>}
 </div>;
}
function Languages({locale,value,onChange}:{locale:Locale;value:string[];onChange:(v:string[])=>void}) {
 const c=TOOLS_COPY[locale],[open,setOpen]=useState(false),[query,setQuery]=useState(''),ref=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null),id=useId();
 const entries=TOOLS_LANGUAGES.filter(code=>!value.includes(code)).map(code=>({value:code,label:languageLabel(code,locale)})).sort((a,b)=>a.label.localeCompare(b.label,locale)).filter(e=>e.label.toLocaleLowerCase().startsWith(query.toLocaleLowerCase()));
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false);};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[]);
 const select=(code:string)=>{onChange([...value,code]);setQuery('');setOpen(false);};
 return <div className="language-editor" ref={ref} data-language-editor onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);}if(e.key==='Enter'&&e.target===input.current&&open&&entries.length){e.preventDefault();select(entries[0].value);}}}><div className="language-chips">{value.map(code=><span key={code}>{languageLabel(code,locale)}<button type="button" aria-label={`${c.remove}: ${languageLabel(code,locale)}`} onClick={()=>{onChange(value.filter(v=>v!==code));setOpen(false);}}>×</button></span>)}<input ref={input} type="text" value={query} onChange={e=>{setQuery(e.target.value);setOpen(true);}} onFocus={()=>setOpen(true)} placeholder={value.length?'':c.searchLanguage} aria-label={c.languagesPlain} autoComplete="off" role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={id}/></div>{open&&<div className="profile-autocomplete language-autocomplete" id={id} role="listbox" aria-label={c.languagesPlain}>{entries.length?entries.map(e=><button key={e.value} type="button" role="option" aria-selected={false} onClick={()=>select(e.value)}>{e.label}</button>):<p className="profile-autocomplete-empty">{c.noLanguagesFound}</p>}</div>}</div>;
}
function City({locale,country,value,onChange,onSelect}:{locale:Locale;country:string;value:string;onChange:(v:string)=>void;onSelect:(e:Entry)=>void}) {
 const c=TOOLS_COPY[locale],[open,setOpen]=useState(false),[entries,setEntries]=useState<Entry[]>([]),[loading,setLoading]=useState(false),[failed,setFailed]=useState(false),ref=useRef<HTMLLabelElement>(null),id=useId();
 const translations=(TOOLS_CITY_TRANSLATIONS as Record<string,Record<string,string>>)[locale]||{};
 const local=(v:string)=>translations[v]||translations[v.replace(/\s+/g,'')]||v;
 useEffect(()=>{let active=true;if(!open)return;if(!country){setEntries([]);return;}setLoading(true);setFailed(false);const normalized=value.trim().toLowerCase(),q=Object.entries(translations).find(([key,label])=>[key,label].some(v=>v.toLowerCase().startsWith(normalized)))?.[0]||value.trim();const timer=setTimeout(()=>{void api.get<Row>('/member/catalog/filter-options?'+new URLSearchParams({country,q})).then(result=>{if(!active)return;const seen=new Set<string>();setEntries((Array.isArray(result.cities)?result.cities:[]).map(v=>{const r=row(v);return {value:text(r.value),label:text(r.label||r.value),placeId:text(r.placeId||r.placeid)};}).filter(e=>{const key=e.value.toLowerCase();if(seen.has(key))return false;seen.add(key);return [e.value,e.label,local(e.label)].some(v=>v.toLowerCase().startsWith(normalized));}));}).catch(()=>{if(active){setEntries([]);setFailed(true);}}).finally(()=>{if(active)setLoading(false);});},140);return()=>{active=false;clearTimeout(timer);};},[open,country,value,locale]);
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false);};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[]);
 return <label className="profile-location-field" ref={ref}>{c.city}<input name="city" value={value} onChange={e=>{onChange(e.target.value);setOpen(true);}} onFocus={()=>setOpen(true)} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);}if(e.key==='Enter'&&open){e.preventDefault();if(entries[0]){onSelect(entries[0]);setOpen(false);}}}} maxLength={128} autoComplete="off" role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={id} placeholder={c.searchCity}/>{open&&<div className="profile-autocomplete" role="listbox" id={id} aria-label={c.city}>{!country||loading||!entries.length?<p className="profile-autocomplete-empty" role="status">{!country?c.chooseCountryFirst:loading?'…':failed?c.tryAgain:c.noCitiesFound}</p>:entries.map(e=><button className="profile-autocomplete-option" key={e.value} type="button" role="option" aria-selected={value===e.value} onClick={()=>{onSelect(e);setOpen(false);}}><span><strong>{e.label}</strong><span>, {[local(e.label)!==e.label?local(e.label):'',countryLabel(country,locale)].filter(Boolean).join(', ')}</span></span></button>)}</div>}</label>;
}
export function MatchingDialog({locale,value,close,onDone}:{locale:Locale;value:Matching;close:()=>void;onDone:(v:Matching)=>void}) {
 const c=TOOLS_COPY[locale],flow=FLOW_COPY[locale],[draft,setDraft]=useState(()=>flowDraft(value)),[step,setStep]=useState(1),body=useRef<HTMLDivElement>(null);
 const kind=flowKind(draft,step),total=totalSteps(draft),preset=TOOLS_CHOICES[locale][(draft.profileType||'SINGLE_WOMAN') as keyof typeof TOOLS_CHOICES.en];
 const t=(ru:string,en:string,es:string)=>locale==='ru'?ru:locale==='es'?es:en;
 const contacts=[['FULL_ANONYMITY','🔒',flow.full],['IDENTITY_DISCLOSURE_AT_18','🗓️',flow.identity],['LIMITED_CONTACT','✉️',flow.limited],['OPEN_CONTACT','🤝',flow.open]];
 const icons:Record<string,string>={SINGLE_WOMAN:'👩',SINGLE_MAN:'👨',HETERO_COUPLE:'👩‍❤️‍👨',LESBIAN_COUPLE:'👩‍❤️‍👩',GAY_COUPLE:'👨‍❤️‍👨'};
 const choices=kind==='who'?TOOLS_OPTIONS.profileTypes.map(([v])=>[v,icons[v],fieldLabel(locale,'profileTypes',v)]):kind==='goal'?preset.goalChoices:kind==='contact'?contacts:kind==='heteroDonor'?preset.heteroDonorChoices:kind==='heteroParent'?preset.heteroParentChoices:preset.parentPathChoices;
 const selected=(v:string)=>kind==='who'?draft.profileType===v:kind==='goal'?draft.goal===v:kind==='contact'?draft.desiredDonorContact===v:kind==='heteroDonor'?v==='BOTH'?draft.donorType.length===2:draft.donorType.length===1&&draft.donorType.includes(v):kind==='heteroParent'?draft.lookingFor.length===1&&draft.lookingFor.includes(v):v==='both'?draft.lookingFor.length===2:v==='coparent'?draft.lookingFor.length===1&&draft.lookingFor.includes('CO_PARENTING_PARTNER'):draft.lookingFor.length===1&&draft.lookingFor.includes(v);
 const title=kind==='who'?flow.who:kind==='goal'?['HETERO_COUPLE','LESBIAN_COUPLE','GAY_COUPLE'].includes(draft.profileType)?t('Какая ваша цель?',"What's your goal?",'¿Cuál es vuestro objetivo?'):flow.goal:kind==='contact'?draft.lookingFor.some(v=>v.endsWith('_DONOR'))?flow.donorContact:flow.contact:kind==='heteroDonor'?t('Как вы можете помочь?','How can you help?','¿Cómo podéis ayudar?'):kind==='heteroParent'?t('Как вы хотите завести ребёнка?','How do you want to have a child?','¿Cómo queréis tener un hijo?'):t('Как хочешь завести ребёнка?','How do you want to have a child?','¿Cómo quieres tener un hijo?');
 useEffect(()=>{body.current?.scrollTo(0,0);},[step]);
 return <Overlay className="profile-dialog matching-dialog tools-modal" surfaceClassName="profile-tools-surface" label={flow.title} close={close} fullViewport="page"><div className="profile-dialog-backdrop" onClick={close}/><section className="profile-dialog-panel"><header className="matching-flow-head"><button type="button" aria-label={step===1?c.close:c.back} onClick={()=>step===1?close():setStep(v=>v-1)}><ToolsIcon name={step===1?'closeIcon':'questionnaireBackIcon'}/></button><h3>{flow.title}</h3><span/></header><div className="matching-flow-body" ref={body}><p className="matching-flow-step">{flow.step} {step} {flow.of} {total}</p><h2>{title}</h2><div className="matching-flow-options">{choices.map(([v,icon,label,help])=><button className={`matching-flow-card${selected(v)?' selected':''}`} type="button" aria-pressed={selected(v)} key={v} onClick={()=>setDraft(d=>chooseFlow(d,step,v))}><span className="matching-flow-icon">{icon}</span><span className="matching-flow-copy"><strong>{label}</strong>{help&&<small>{help}</small>}</span><span className="matching-flow-mark" aria-hidden="true">{selected(v)?'✓':''}</span></button>)}</div>{kind!=='who'&&kind!=='contact'&&<div className="matching-flow-note"><p><strong>{t('Донор','A donor','Un donante')}</strong> {flow.donorInfo}</p>{draft.profileType!=='HETERO_COUPLE'&&<p><strong>{t('Со-родитель','A co-parent','Un coprogenitor')}</strong> {flow.coparentInfo}</p>}</div>}</div><footer className="matching-flow-footer"><button className="primary" type="button" disabled={!stepComplete(draft,step)} onClick={()=>{if(step<total)setStep(v=>v+1);else{const {goal,...answers}=draft;onDone(answers);close();}}}>{step<total?flow.next:flow.done}</button></footer></section></Overlay>;
}
const fields=['displayName','dateOfBirth','country','city','cityPlaceId','eyeColor','hairColor','ethnicity','bio','occupation','education','religion','smokingStatus','drinkingStatus'] as const;
type Draft=Record<typeof fields[number],string>&Matching&{unitPreference:string;heightMetric:string;heightFeet:string;heightInches:string;weightDisplay:string;languages:string[]};
function makeDraft(member:Row):Draft {
 const p=ownProfileData(member.profile),height=Number(p.height)||0,imperial=p.unitPreference==='IMPERIAL',parts=imperialHeight(height),result={} as Draft;
 for(const field of fields)result[field]=text(p[field]);
 result.displayName=text(p.displayName||row(member.user).displayName);result.bio=text(p.bio||p.about);
 return {...result,profileType:text(p.profileType).replace(/\s+/g,'_').toUpperCase(),donorType:list(p.donorType).map(s=>s.toUpperCase()),lookingFor:list(p.lookingFor).map(s=>s.toUpperCase()),desiredDonorContact:text(p.desiredDonorContact).toUpperCase(),unitPreference:imperial?'IMPERIAL':'METRIC',heightMetric:height?String(height):'',heightFeet:height?String(parts.feet):'',heightInches:height?String(parts.inches):'',weightDisplay:Number(p.weight)?String(imperial?Math.round(Number(p.weight)*2.20462):p.weight):'',languages:[...new Set(list(p.languages).map(languageCode))]};
}
const normalized=(d:Draft)=>JSON.stringify({...d,...Object.fromEntries(fields.map(k=>[k,d[k].trim()])),languages:[...d.languages].sort(),donorType:[...d.donorType].sort(),lookingFor:[...d.lookingFor].sort()});
export function MemberProfileEdit({locale}:Props) {
 const member=useMemberResource<Row>('/member/me',true),options=useMemberResource<Row>('/member/catalog/filter-options?limit=60',true);
 if(member.error!==undefined)return <MemberError locale={locale} retry={member.retry} status={member.error}/>;
 if(!member.data)return <MemberLoading locale={locale}/>;
 return <ProfileEditor key={locale} member={member.data} locale={locale} countries={options.data} countryError={options.error!==undefined} retryCountries={options.retry}/>;
}
function ProfileEditor({member,locale,countries,countryError,retryCountries}:{member:Row;locale:Locale;countries?:Row;countryError:boolean;retryCountries:()=>void}) {
 const c=TOOLS_COPY[locale],navigate=useNavigate(),[draft,setDraft]=useState(()=>makeDraft(member)),initial=useRef(normalized(draft)),[matching,setMatching]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),form=useRef<HTMLFormElement>(null),saving=useRef(false);
 const set=(key:keyof Draft,value:Draft[keyof Draft])=>setDraft(d=>({...d,[key]:value}));
 const dirty=normalized(draft)!==initial.current,imperial=draft.unitPreference==='IMPERIAL';
 const countryEntries=(Array.isArray(countries?.countries)?countries.countries:[]).map(v=>{const e=row(v),value=text(e.value).toUpperCase();return {value,label:countryLabel(value,locale)||text(e.label)};});
 if(draft.country&&!countryEntries.some(e=>e.value===draft.country))countryEntries.push({value:draft.country,label:countryLabel(draft.country,locale)});countryEntries.sort((a,b)=>a.label.localeCompare(b.label,locale));
 const picker=(key:keyof typeof TOOLS_PICKERS.en,label:string)=><Picker name={key} locale={locale} label={label} value={draft[key]} entries={key==='country'?countryEntries:(TOOLS_OPTIONS[key] as string[][]).map(([value])=>({value,label:fieldLabel(locale,key,value)}))} onChange={v=>{setDraft(d=>({...d,[key]:v,...key==='country'?{city:'',cityPlaceId:''}:{}}));}}/>;
 const units={en:{cm:'cm',kg:'kg',feet:'ft',inches:'in',pounds:'lb'},ru:{cm:'см',kg:'кг',feet:'фт',inches:'дюйм',pounds:'фунт'},es:{cm:'cm',kg:'kg',feet:'pies',inches:'pulg.',pounds:'lb'}}[locale];
 const switchUnits=(next:string)=>{if(next===draft.unitPreference)return;setDraft(d=>{const height=d.unitPreference==='IMPERIAL'?(Number(d.heightFeet)*12+Number(d.heightInches))*2.54:Number(d.heightMetric),parts=imperialHeight(height),weight=Number(d.weightDisplay);return {...d,unitPreference:next,heightMetric:height?String(Math.round(height)):'',heightFeet:height?String(parts.feet):'',heightInches:height?String(parts.inches):'',weightDisplay:weight?String(next==='IMPERIAL'?Math.round(weight*2.20462):Math.round(weight/2.20462)):''};});};
 const t=(ru:string,en:string,es:string)=>locale==='ru'?ru:locale==='es'?es:en;
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!dirty||saving.current)return;setError('');if(!draft.displayName.trim()){setError(t('Укажите имя.','Enter your name.','Introduce tu nombre.'));return;}if(!matchingComplete(draft)){setError(t('Заполните все обязательные ответы анкеты.','Complete all required questionnaire answers.','Completa todas las respuestas obligatorias del cuestionario.'));setMatching(true);return;}
  const height=imperial?(draft.heightFeet||draft.heightInches?(Number(draft.heightFeet)*12+Number(draft.heightInches))*2.54:null):draft.heightMetric?Number(draft.heightMetric):null,weight=draft.weightDisplay?Number(draft.weightDisplay)/(imperial?2.20462:1):null;
  if(height!==null&&(height<80||height>250)||weight!==null&&(weight<25||weight>350)){setError(t('Укажите рост от 80 до 250 см и вес от 25 до 350 кг.','Enter a height from 80 to 250 cm and a weight from 25 to 350 kg.','Indica una altura de 80 a 250 cm y un peso de 25 a 350 kg.'));return;}
  saving.current=true;setBusy(true);try{await api.patch('/member/profile',{...Object.fromEntries(fields.map(k=>[k,draft[k].trim()])),profileType:draft.profileType,lookingFor:draft.lookingFor,donorType:draft.donorType,desiredDonorContact:needsContact(draft)?draft.desiredDonorContact:'',unitPreference:draft.unitPreference,height:height===null?null:Math.round(height),weight:weight===null?null:Math.round(weight),languages:draft.languages});notifyMemberChanged();navigate(`/${locale}/profile`);}catch(err){setError(toolsError(err,t('Не удалось сохранить изменения. Попробуйте ещё раз.','Could not save changes. Please try again.','No se pudieron guardar los cambios. Inténtalo de nuevo.')));}finally{setBusy(false);saving.current=false;}};
 const today=new Date(),maxDate=`${today.getFullYear()-18}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
 const save=<button className="primary" type="submit" form="profile-edit-form" disabled={!dirty||busy} aria-busy={busy}>{busy?<span className="tools-spinner"/>:c.save}</button>,cancel=<Link className="soft-button linklike" to={`/${locale}/profile`}>{c.cancel}</Link>;
 const input=(key:typeof fields[number],label:string,props:Record<string,unknown>={})=><label>{label}<input name={key} value={draft[key]} onChange={e=>set(key,e.target.value)} {...props}/></label>;
 const contacts:Record<string,string>={FULL_ANONYMITY:c.fullAnonymity,LIMITED_CONTACT:c.limitedContact,CONTACT_BY_AGREEMENT:c.limitedContact,IDENTITY_DISCLOSURE_AT_18:FLOW_COPY[locale].identity,OPEN_CONTACT:c.openContact};
 const ownContact=draft.donorType.length>0&&!draft.lookingFor.some(v=>v.endsWith('_DONOR'));
 return <div className="profile-tools-surface profile-edit-context"><div className="app-shell narrow profile-edit-shell"><div className="edit-title-row"><h1 className="page-title compact">{c.editHeading}</h1><div className="edit-title-actions">{cancel}{save}</div></div><form id="profile-edit-form" className="edit-form profile-edit-form" ref={form} onSubmit={submit} aria-busy={busy}><section className="edit-section"><h2>{c.basicInfo}</h2><div className="edit-grid">{input('displayName',c.name,{required:true,maxLength:255})}{input('dateOfBirth',c.dob,{type:'date',required:true,max:maxDate})}<label>{c.country}{picker('country',c.country)}{countryError&&<button className="tools-inline-retry" type="button" onClick={retryCountries}>{c.tryAgain}</button>}</label><City locale={locale} country={draft.country} value={draft.city} onChange={v=>setDraft(d=>({...d,city:v,cityPlaceId:''}))} onSelect={e=>setDraft(d=>({...d,city:e.value,cityPlaceId:e.placeId||''}))}/><section className={`matching-summary edit-wide${matchingComplete(draft)?'':' is-incomplete'}`}><h3>{c.questionnaire}</h3><p>{c.questionnaireHelp}</p><dl><div hidden={!draft.profileType}><dt>{t('Вы','You are','Eres')}</dt><dd data-match-summary="profileType">{fieldLabel(locale,'profileTypes',draft.profileType)}</dd></div><div hidden={!draft.donorType.length}><dt>{c.donorReady}</dt><dd data-match-summary="donorType">{draft.donorType.map(v=>v==='EGG'?t('Яйцеклетки','Eggs','Óvulos'):t('Сперма','Sperm','Esperma')).join(', ')}</dd></div><div hidden={!draft.lookingFor.length}><dt>{c.lookingFor}</dt><dd data-match-summary="lookingFor">{draft.lookingFor.map(v=>fieldLabel(locale,'lookingFor',v)).join(', ')}</dd></div><div hidden={!needsContact(draft)}><dt>{ownContact?t('Мой контакт с ребёнком','My contact with the child','Mi contacto con el menor'):t('Контакт донора',"Donor's contact",'Contacto del donante')}</dt><dd data-match-summary="desiredDonorContact">{contacts[draft.desiredDonorContact]}</dd></div></dl><button className="matching-edit-button" type="button" onClick={()=>setMatching(true)}>✏️ {c.editAnswers}</button></section></div></section>
 <section className="edit-section"><div className="appearance-heading"><h2>{c.appearance}</h2></div><div className="appearance-measurements"><div className="unit-toggle" role="group" aria-label="Units"><button type="button" className={!imperial?'active':''} aria-pressed={!imperial} onClick={()=>switchUnits('METRIC')}>{c.metric}</button><button type="button" className={imperial?'active':''} aria-pressed={imperial} onClick={()=>switchUnits('IMPERIAL')}>{c.imperial}</button></div><label>{c.heightPlain}<span className="measurement-input" hidden={imperial}><input name="heightMetric" type="number" min="80" max="250" step="1" value={draft.heightMetric} onChange={e=>set('heightMetric',e.target.value)} disabled={imperial}/><b>{units.cm}</b></span><span className="height-imperial-inputs" hidden={!imperial}><span className="measurement-input"><input name="heightFeet" aria-label={`${c.heightPlain} ${units.feet}`} type="number" min="2" max="8" step="1" value={draft.heightFeet} onChange={e=>set('heightFeet',e.target.value)} disabled={!imperial}/><b>{units.feet}</b></span><span className="measurement-input"><input name="heightInches" aria-label={`${c.heightPlain} ${units.inches}`} type="number" min="0" max="11" step="1" value={draft.heightInches} onChange={e=>set('heightInches',e.target.value)} disabled={!imperial}/><b>{units.inches}</b></span></span></label><label>{c.weightPlain}<span className="measurement-input"><input name="weightDisplay" type="number" min={imperial?'55':'25'} max={imperial?'772':'350'} step="0.1" value={draft.weightDisplay} onChange={e=>set('weightDisplay',e.target.value)}/><b>{imperial?units.pounds:units.kg}</b></span></label></div><div className="edit-grid"><label>{c.eye}{picker('eyeColor',c.eye)}</label><label>{c.hair}{picker('hairColor',c.hair)}</label><label className="edit-wide">{c.ethnicity}{picker('ethnicity',c.ethnicity)}</label></div></section>
 <section className="edit-section"><h2>{c.aboutSection}</h2><div className="edit-grid"><label className="edit-wide">{c.about}<textarea name="bio" rows={6} maxLength={2000} value={draft.bio} onChange={e=>set('bio',e.target.value)}/><small><span>{draft.bio.length}</span> / 2000</small></label><label className="edit-wide">{c.languagesPlain}<Languages locale={locale} value={draft.languages} onChange={v=>set('languages',v)}/></label>{input('occupation',c.occupation,{placeholder:c.occupationPlaceholder,maxLength:255})}<label>{c.education}{picker('education',c.education)}</label><label>{c.religion}{picker('religion',c.religion)}</label><label>{c.smoking}{picker('smokingStatus',c.smoking)}</label><label>{c.alcohol}{picker('drinkingStatus',c.alcohol)}</label></div></section>{error&&<p className="tools-error" role="alert">{error}</p>}<div className="form-actions edit-bottom-actions">{cancel}{save}</div></form></div>{matching&&<MatchingDialog locale={locale} value={draft} close={()=>setMatching(false)} onDone={v=>setDraft(d=>({...d,...v}))}/>}</div>;
}
