// Copy and fixed SVG assets retained from the existing HTML implementation.
const ACCOUNT_COPY_BASE = {
  en: {
    back: "Back to profile",
    blockedBack: "My profile",
    blockedTitle: "Blocked users",
    unblockConfirmPrefix: "Unblock",
    unblockConfirmBody:
      "This user will be able to see your profile and write to you again.",
    edit: "Edit profile",
    photos: "Edit photos",
    photosHeading: "Photos",
    photosIntro:
      "Add photos to your profile. The first photo will be your avatar.",
    primary: "Primary",
    mainPhoto: "Main photo",
    avatar: "Avatar",
    avatarSet: "Avatar set",
    avatarNotSet: "Avatar not set",
    changeAvatar: "Change avatar",
    remove: "Delete",
    photoDeleteMainTitle: "Delete main photo?",
    photoDeleteMainBody:
      "Your main photo and avatar will be removed. Are you sure you want to continue?",
    photoDeleteAdditionalTitle: "Delete this photo?",
    photoDeleteAdditionalBody:
      "This photo will be permanently removed from your profile.",
    additionalPhotos: "Additional photos",
    addPhoto: "Add another photo",
    uploadPrompt: "Click to upload or drag a file",
    photoHelp: "JPEG, PNG or WebP (max. 10 MB)",
    photoLimit: "You can upload up to 6 photos.",
    photoLimitReached: "The 6 photo limit has been reached.",
    photoInvalid: "Only JPEG, PNG and WebP images are supported.",
    photoTooLarge: "The photo must not exceed 10 MB.",
    photoEmpty: "The selected photo is empty.",
    photoUploadFailed: "Unable to upload the photo. Try again.",
    photoUploadTimeout:
      "Photo upload took too long. Check your connection and try again.",
    cropTitle: "Crop your avatar",
    scale: "Scale",
    cancel: "Cancel",
    saveAvatar: "Save avatar",
    saving: "",
    upload: "",
    photoPending: "Photo is being checked automatically.",
    photoRejected: "Photo was rejected. Choose another image.",
    photoApproved: "Photo approved.",
    avatarVerificationResetTitle: "Change your verified profile photo?",
    avatarVerificationResetBody:
      "If you replace your main photo, your verification will be reset and you will need to complete it again.",
    avatarVerificationResetAction: "Change photo",
    completed: "Profile completed",
    visible: "Visible in catalog",
    premium: "Premium subscription",
    advisor: "AI Family Advisor",
    verification: "Profile verification",
    notifications: "Notification settings",
    language: "Interface language",
    blocked: "Blocked users",
    boostLink: "Profile Boost",
    communityLink: "Community",
    referralLink: "Invite & earn a Boost",
    savedLink: "Saved",
    safetyLink: "Safety Check-In",
    delete: "Delete account",
    signOut: "Sign out",
    editHeading: "Edit profile",
    basicInfo: "Basic information",
    questionnaire: "Matching questionnaire",
    questionnaireHelp:
      "These answers determine who you see and who can see you.",
    who: "Who you are",
    donorReady: "Ready to be a donor",
    childContact: "Contact with the child",
    editAnswers: "Edit answers",
    noAnswer: "Not specified",
    none: "No",
    fullAnonymity: "Full anonymity",
    limitedContact: "Contact by agreement",
    openContact: "Open contact",
    metric: "kg/cm",
    imperial: "lb/ft",
    heightPlain: "Height",
    weightPlain: "Weight",
    languagesPlain: "Languages",
    personal: "Personal details",
    name: "Your name",
    dob: "Date of birth",
    country: "Country",
    city: "City",
    profileType: "Profile type",
    searchCity: "Start typing a city",
    chooseCountryFirst: "Select a country first",
    noCitiesFound: "No cities found",
    searchLanguage: "Start typing a language...",
    noLanguagesFound: "No languages found",
    matching: "Matching",
    lookingFor: "Looking for",
    appearance: "Appearance",
    height: "Height (cm)",
    weight: "Weight (kg)",
    eye: "Eye color",
    hair: "Hair color",
    ethnicity: "Ethnicity",
    aboutSection: "About me",
    about: "About you",
    occupation: "Occupation",
    occupationPlaceholder: "e.g. Software Engineer, Teacher...",
    education: "Education",
    religion: "Religion",
    smoking: "Smoking",
    alcohol: "Alcohol",
    languages: "Languages (comma separated)",
    save: "Save changes",
    saved: "Profile saved.",
    choose: "Choose",
    verificationHeading: "Profile verification",
    verificationTitle: "We'll match your selfie to your main photo",
    verificationBody:
      "Make sure your main photo clearly shows your face — no sunglasses, hat, or phone covering it. If it doesn't, change it first or verification will fail.",
    currentPhoto: "Your main photo",
    changeMainPhoto: "Change main photo",
    startVerification: "Start verification",
    startingVerification: "Starting verification…",
    continueVerification: "Continue verification",
    cancelVerification: "Cancel",
    cancellingVerification: "Cancelling…",
    verificationCancelled:
      "Verification cancelled. You can start again at any time.",
    verificationCancelFailed:
      "Unable to cancel verification. Please try again.",
    tryAgain: "Try again",
    verificationPending: "Verification is being reviewed",
    verificationApproved: "Profile verified",
    verificationComplete: "Verification completed",
    verificationSuccessTitle: "Verification successful",
    verificationSuccessBody: "Your profile has been verified.",
    verificationFailureTitle: "Verification unsuccessful",
    verificationFailed: "Verification failed. You can try again.",
    verificationResultOk: "OK",
    verificationPhotoRequired:
      "Upload an approved main photo before starting verification.",
    verificationLoadFailed: "Unable to load verification status. Try again.",
    verificationStartTimeout:
      "Verification could not be started in time. Please try again.",
    verificationCreditsUnavailable:
      "Photo verification is temporarily unavailable because the verification service has no available credits.",
    providerUnavailable: "Photo verification is temporarily unavailable.",
    notificationsTitle: "Email notifications",
    notificationsIntro:
      "Manage the emails we send you. Push notifications are controlled by your device settings.",
    newMatch: "New matches",
    newMatchHelp: "When someone matches with you",
    newLike: "New likes",
    newLikeHelp: "When someone likes your profile",
    newMessage: "New messages",
    newMessageHelp: "When someone sends you a message",
    profileView: "Profile views",
    profileViewHelp: "Daily summary of who viewed your profile",
    marketing: "News & updates",
    marketingHelp: "Product updates and special offers",
    noBlocked: "You haven't blocked anyone",
    unblock: "Unblock",
    selectLanguage: "Choose interface language",
    close: "Close",
    deleteTitle: "Delete account",
    deleteBody:
      "Your profile will be hidden immediately. Your account and personal data will be permanently deleted after 30 days.",
    deleteReason: "Why are you leaving?",
    deleteConfirm: "Type delete to confirm",
    deleteWord: "delete",
    deleteButton: "Delete my account",
    deletionSent: "Account deletion scheduled.",
  },
  ru: {
    back: "Назад к профилю",
    blockedBack: "Мой профиль",
    blockedTitle: "Заблокированные",
    unblockConfirmPrefix: "Разблокировать",
    unblockConfirmBody:
      "Этот пользователь снова сможет видеть ваш профиль и писать вам.",
    edit: "Редактировать профиль",
    photos: "Редактировать фото",
    photosHeading: "Фотографии",
    photosIntro:
      "Добавьте фотографии в профиль. Первое фото будет вашим аватаром.",
    primary: "Главное",
    mainPhoto: "Главное фото",
    avatar: "Аватар",
    avatarSet: "Аватар установлен",
    avatarNotSet: "Аватар не установлен",
    changeAvatar: "Сменить аватар",
    remove: "Удалить",
    photoDeleteMainTitle: "Удалить главное фото?",
    photoDeleteMainBody:
      "Главное фото и аватар будут удалены. Вы уверены, что хотите продолжить?",
    photoDeleteAdditionalTitle: "Удалить эту фотографию?",
    photoDeleteAdditionalBody:
      "Фотография будет безвозвратно удалена из вашего профиля.",
    additionalPhotos: "Дополнительные фото",
    addPhoto: "Добавить фото",
    uploadPrompt: "Нажмите для загрузки или перетащите файл",
    photoHelp: "JPEG, PNG или WebP (макс. 10МБ)",
    photoLimit: "Можно загрузить не более 6 фотографий.",
    photoLimitReached: "Достигнут лимит: 6 фотографий.",
    photoInvalid: "Поддерживаются только JPEG, PNG и WebP.",
    photoTooLarge: "Размер фотографии не должен превышать 10 МБ.",
    photoEmpty: "Выбранная фотография пуста.",
    photoUploadFailed: "Не удалось загрузить фотографию. Попробуйте ещё раз.",
    photoUploadTimeout:
      "Загрузка фотографии заняла слишком много времени. Проверьте соединение и повторите попытку.",
    cropTitle: "Обрежьте аватар",
    scale: "Масштаб",
    cancel: "Отмена",
    saveAvatar: "Сохранить аватар",
    saving: "",
    upload: "",
    photoPending: "Фотография проходит автоматическую проверку.",
    photoRejected: "Фотография отклонена. Выберите другое изображение.",
    photoApproved: "Фотография одобрена.",
    avatarVerificationResetTitle: "Сменить фото верифицированного профиля?",
    avatarVerificationResetBody:
      "Если вы замените главное фото, верификация будет сброшена и её потребуется пройти заново.",
    avatarVerificationResetAction: "Сменить фото",
    completed: "Профиль заполнен",
    visible: "Показывать в каталоге",
    premium: "Премиум-подписка",
    advisor: "AI Family Advisor",
    verification: "Верификация профиля",
    notifications: "Настройки уведомлений",
    language: "Язык интерфейса",
    blocked: "Заблокированные пользователи",
    boostLink: "Boost профиля",
    communityLink: "Community",
    referralLink: "Приглашай и получай Boost",
    savedLink: "Избранное",
    safetyLink: "Safety Check-In",
    delete: "Удалить аккаунт",
    signOut: "Выйти",
    editHeading: "Редактирование профиля",
    basicInfo: "Основная информация",
    questionnaire: "Анкета для подбора",
    questionnaireHelp:
      "Эти ответы определяют, кого мы тебе показываем и кому показываем тебя.",
    who: "Кто ты",
    donorReady: "Готов(а) стать донором",
    childContact: "Мой контакт с ребёнком",
    editAnswers: "Изменить ответы",
    noAnswer: "Не указано",
    none: "Нет",
    fullAnonymity: "Полная анонимность",
    limitedContact: "Контакт по договорённости",
    openContact: "Открытый контакт",
    metric: "kg/cm",
    imperial: "lb/ft",
    heightPlain: "Рост",
    weightPlain: "Вес",
    languagesPlain: "Языки",
    personal: "Личные данные",
    name: "Ваше имя",
    dob: "Дата рождения",
    country: "Страна",
    city: "Город",
    profileType: "Тип профиля",
    searchCity: "Начните вводить город...",
    chooseCountryFirst: "Сначала выберите страну",
    noCitiesFound: "Города не найдены",
    searchLanguage: "Начните вводить язык...",
    noLanguagesFound: "Языки не найдены",
    matching: "Подбор пары",
    lookingFor: "Кого вы ищете",
    appearance: "Внешность",
    height: "Рост (см)",
    weight: "Вес (кг)",
    eye: "Цвет глаз",
    hair: "Цвет волос",
    ethnicity: "Этническая принадлежность",
    aboutSection: "Обо мне",
    about: "О себе",
    occupation: "Профессия",
    occupationPlaceholder: "Например, программист, учитель...",
    education: "Образование",
    religion: "Религия",
    smoking: "Курение",
    alcohol: "Алкоголь",
    languages: "Языки через запятую",
    save: "Сохранить",
    saved: "Профиль сохранён.",
    choose: "Выберите",
    verificationHeading: "Верификация профиля",
    verificationTitle: "Мы сравним ваше селфи с главным фото",
    verificationBody:
      "Убедитесь, что на главном фото хорошо видно ваше лицо — без солнцезащитных очков, головного убора и телефона, закрывающего лицо. Если это не так, сначала смените фото, иначе проверка не пройдёт.",
    currentPhoto: "Ваше главное фото",
    changeMainPhoto: "Сменить главное фото",
    startVerification: "Начать верификацию",
    startingVerification: "Запускаем верификацию…",
    continueVerification: "Продолжить верификацию",
    cancelVerification: "Отменить",
    cancellingVerification: "Отменяем…",
    verificationCancelled:
      "Верификация отменена. Её можно начать заново в любое время.",
    verificationCancelFailed:
      "Не удалось отменить верификацию. Попробуйте ещё раз.",
    tryAgain: "Попробовать снова",
    verificationPending: "Верификация на проверке",
    verificationApproved: "Профиль верифицирован",
    verificationComplete: "Верификация завершена",
    verificationSuccessTitle: "Верификация прошла успешно",
    verificationSuccessBody: "Ваш профиль верифицирован.",
    verificationFailureTitle: "Верификация не пройдена",
    verificationFailed: "Верификация не пройдена. Можно попробовать снова.",
    verificationResultOk: "ОК",
    verificationPhotoRequired:
      "Перед началом верификации загрузите одобренное главное фото.",
    verificationLoadFailed:
      "Не удалось загрузить статус верификации. Попробуйте ещё раз.",
    verificationStartTimeout:
      "Не удалось вовремя запустить верификацию. Попробуйте ещё раз.",
    verificationCreditsUnavailable:
      "Фотоверификация временно недоступна: на балансе сервиса проверки нет средств.",
    providerUnavailable: "Фотоверификация временно недоступна.",
    notificationsTitle: "Email-уведомления",
    notificationsIntro:
      "Управляйте письмами, которые мы вам отправляем. Push-уведомления настраиваются в настройках устройства.",
    newMatch: "Новые совпадения",
    newMatchHelp: "Когда кто-то совпал с вами",
    newLike: "Новые лайки",
    newLikeHelp: "Когда кто-то лайкнул ваш профиль",
    newMessage: "Новые сообщения",
    newMessageHelp: "Когда вам отправили сообщение",
    profileView: "Просмотры профиля",
    profileViewHelp: "Ежедневная сводка о тех, кто смотрел ваш профиль",
    marketing: "Новости и обновления",
    marketingHelp: "Обновления продукта и специальные предложения",
    noBlocked: "Вы никого не заблокировали.",
    unblock: "Разблокировать",
    selectLanguage: "Выберите язык интерфейса",
    close: "Закрыть",
    deleteTitle: "Удаление аккаунта",
    deleteBody:
      "Профиль будет скрыт сразу. Аккаунт и персональные данные будут окончательно удалены через 30 дней.",
    deleteReason: "Почему вы уходите?",
    deleteConfirm: "Введите delete для подтверждения",
    deleteWord: "delete",
    deleteButton: "Удалить аккаунт",
    deletionSent: "Удаление аккаунта запланировано.",
  },
  es: {
    back: "Volver al perfil",
    blockedBack: "Mi perfil",
    blockedTitle: "Bloqueados",
    unblockConfirmPrefix: "Desbloquear",
    unblockConfirmBody:
      "Este usuario podrá volver a ver tu perfil y escribirte.",
    edit: "Editar perfil",
    photos: "Editar fotos",
    photosHeading: "Fotos",
    photosIntro: "Añade fotos a tu perfil. La primera foto será tu avatar.",
    primary: "Principal",
    mainPhoto: "Foto principal",
    avatar: "Avatar",
    avatarSet: "Avatar establecido",
    avatarNotSet: "Avatar no establecido",
    changeAvatar: "Cambiar avatar",
    remove: "Eliminar",
    photoDeleteMainTitle: "¿Eliminar la foto principal?",
    photoDeleteMainBody:
      "Se eliminarán tu foto principal y tu avatar. ¿Seguro que quieres continuar?",
    photoDeleteAdditionalTitle: "¿Eliminar esta foto?",
    photoDeleteAdditionalBody:
      "Esta foto se eliminará permanentemente de tu perfil.",
    additionalPhotos: "Fotos adicionales",
    addPhoto: "Añadir foto",
    uploadPrompt: "Haz clic para subir o arrastra un archivo",
    photoHelp: "JPEG, PNG o WebP (máx. 10 MB)",
    photoLimit: "Puedes subir hasta 6 fotos.",
    photoLimitReached: "Se alcanzó el límite de 6 fotos.",
    photoInvalid: "Solo se admiten imágenes JPEG, PNG y WebP.",
    photoTooLarge: "La foto no debe superar los 10 MB.",
    photoEmpty: "La foto seleccionada está vacía.",
    photoUploadFailed: "No se pudo cargar la foto. Inténtalo de nuevo.",
    photoUploadTimeout:
      "La carga de la foto tardó demasiado. Comprueba la conexión e inténtalo de nuevo.",
    cropTitle: "Recorta tu avatar",
    scale: "Escala",
    cancel: "Cancelar",
    saveAvatar: "Guardar avatar",
    saving: "",
    upload: "",
    photoPending: "La foto está siendo comprobada automáticamente.",
    photoRejected: "La foto fue rechazada. Elige otra imagen.",
    photoApproved: "Foto aprobada.",
    avatarVerificationResetTitle: "¿Cambiar la foto de un perfil verificado?",
    avatarVerificationResetBody:
      "Si reemplazas la foto principal, se restablecerá la verificación y tendrás que completarla de nuevo.",
    avatarVerificationResetAction: "Cambiar foto",
    completed: "Perfil completado",
    visible: "Visible en el catálogo",
    premium: "Suscripción Premium",
    advisor: "AI Family Advisor",
    verification: "Verificación del perfil",
    notifications: "Notificaciones",
    language: "Idioma",
    blocked: "Usuarios bloqueados",
    boostLink: "Boost de perfil",
    communityLink: "Community",
    referralLink: "Invita y gana un Boost",
    savedLink: "Guardados",
    safetyLink: "Safety Check-In",
    delete: "Eliminar cuenta",
    signOut: "Cerrar sesión",
    editHeading: "Editar perfil",
    basicInfo: "Información básica",
    questionnaire: "Cuestionario de coincidencias",
    questionnaireHelp:
      "Estas respuestas determinan a quién ves y quién puede verte.",
    who: "Quién eres",
    donorReady: "Dispuesto a donar",
    childContact: "Contacto con el niño",
    editAnswers: "Editar respuestas",
    noAnswer: "Sin especificar",
    none: "No",
    fullAnonymity: "Anonimato completo",
    limitedContact: "Contacto por acuerdo",
    openContact: "Contacto abierto",
    metric: "kg/cm",
    imperial: "lb/ft",
    heightPlain: "Altura",
    weightPlain: "Peso",
    languagesPlain: "Idiomas",
    personal: "Datos personales",
    name: "Tu nombre",
    dob: "Fecha de nacimiento",
    country: "País",
    city: "Ciudad",
    profileType: "Tipo de perfil",
    searchCity: "Empieza a escribir una ciudad...",
    chooseCountryFirst: "Selecciona primero un país",
    noCitiesFound: "No se encontraron ciudades",
    searchLanguage: "Empieza a escribir un idioma...",
    noLanguagesFound: "No se encontraron idiomas",
    matching: "Coincidencias",
    lookingFor: "Busco",
    appearance: "Apariencia",
    height: "Altura (cm)",
    weight: "Peso (kg)",
    eye: "Color de ojos",
    hair: "Color de pelo",
    ethnicity: "Origen étnico",
    aboutSection: "Sobre mí",
    about: "Sobre mí",
    occupation: "Ocupación",
    occupationPlaceholder: "p. ej., ingeniero de software, docente...",
    education: "Educación",
    religion: "Religión",
    smoking: "Tabaco",
    alcohol: "Alcohol",
    languages: "Idiomas separados por comas",
    save: "Guardar",
    saved: "Perfil guardado.",
    choose: "Selecciona",
    verificationHeading: "Verificación del perfil",
    verificationTitle: "Compararemos tu selfie con tu foto principal",
    verificationBody:
      "Asegúrate de que tu foto principal muestre claramente tu cara, sin gafas de sol, gorra ni teléfono que la tapen. Si no es así, cámbiala primero o la verificación fallará.",
    currentPhoto: "Tu foto principal",
    changeMainPhoto: "Cambiar foto principal",
    startVerification: "Iniciar verificación",
    startingVerification: "Iniciando la verificación…",
    continueVerification: "Continuar verificación",
    cancelVerification: "Cancelar",
    cancellingVerification: "Cancelando…",
    verificationCancelled:
      "Verificación cancelada. Puedes volver a iniciarla en cualquier momento.",
    verificationCancelFailed:
      "No se pudo cancelar la verificación. Inténtalo de nuevo.",
    tryAgain: "Intentar de nuevo",
    verificationPending: "Verificación en revisión",
    verificationApproved: "Perfil verificado",
    verificationComplete: "Verificación completada",
    verificationSuccessTitle: "Verificación completada correctamente",
    verificationSuccessBody: "Tu perfil ha sido verificado.",
    verificationFailureTitle: "No se pudo completar la verificación",
    verificationFailed: "La verificación falló. Puedes volver a intentarlo.",
    verificationResultOk: "Aceptar",
    verificationPhotoRequired:
      "Sube una foto principal aprobada antes de iniciar la verificación.",
    verificationLoadFailed:
      "No se pudo cargar el estado de verificación. Inténtalo de nuevo.",
    verificationStartTimeout:
      "No se pudo iniciar la verificación a tiempo. Inténtalo de nuevo.",
    verificationCreditsUnavailable:
      "La verificación de foto no está disponible temporalmente porque el servicio no tiene créditos disponibles.",
    providerUnavailable:
      "La verificación de foto no está disponible temporalmente.",
    notificationsTitle: "Notificaciones por email",
    notificationsIntro:
      "Gestiona los correos que te enviamos. Las notificaciones push se controlan desde los ajustes de tu dispositivo.",
    newMatch: "Nuevos matches",
    newMatchHelp: "Cuando alguien hace match contigo",
    newLike: "Nuevos likes",
    newLikeHelp: "Cuando alguien da like a tu perfil",
    newMessage: "Nuevos mensajes",
    newMessageHelp: "Cuando alguien te envía un mensaje",
    profileView: "Visitas al perfil",
    profileViewHelp: "Resumen diario de quién ha visto tu perfil",
    marketing: "Noticias y novedades",
    marketingHelp: "Actualizaciones y ofertas especiales",
    noBlocked: "No has bloqueado a nadie.",
    unblock: "Desbloquear",
    selectLanguage: "Elige el idioma",
    close: "Cerrar",
    deleteTitle: "Eliminar cuenta",
    deleteBody:
      "Tu perfil se ocultará de inmediato. La cuenta y los datos se eliminarán definitivamente después de 30 días.",
    deleteReason: "¿Por qué te vas?",
    deleteConfirm: "Escribe delete para confirmar",
    deleteWord: "delete",
    deleteButton: "Eliminar mi cuenta",
    deletionSent: "Eliminación programada.",
  },
} as const;

export const ACCOUNT_COPY = {
  ...ACCOUNT_COPY_BASE,
  pt: { ...ACCOUNT_COPY_BASE.en,
    back: "Voltar ao perfil", blockedBack: "Meu perfil", blockedTitle: "Usuários bloqueados",
    unblockConfirmPrefix: "Desbloquear",
    unblockConfirmBody: "Este usuário poderá ver seu perfil e escrever para você novamente.",
    edit: "Editar perfil", photos: "Editar fotos", photosHeading: "Fotos",
    photosIntro: "Adicione fotos ao seu perfil. A primeira foto será seu avatar.",
    primary: "Principal", mainPhoto: "Foto principal", avatar: "Avatar", avatarSet: "Avatar definido",
    avatarNotSet: "Avatar não definido", changeAvatar: "Alterar avatar", remove: "Excluir",
    photoDeleteMainTitle: "Excluir a foto principal?",
    photoDeleteMainBody: "Sua foto principal e seu avatar serão removidos. Tem certeza de que deseja continuar?",
    photoDeleteAdditionalTitle: "Excluir esta foto?",
    photoDeleteAdditionalBody: "Esta foto será removida permanentemente do seu perfil.",
    additionalPhotos: "Fotos adicionais", addPhoto: "Adicionar outra foto",
    uploadPrompt: "Clique para enviar ou arraste um arquivo", photoHelp: "JPEG, PNG ou WebP (máx. 10 MB)",
    photoLimit: "Você pode enviar até 6 fotos.", photoLimitReached: "O limite de 6 fotos foi atingido.",
    photoInvalid: "Apenas imagens JPEG, PNG e WebP são aceitas.", photoTooLarge: "A foto não pode ultrapassar 10 MB.",
    photoEmpty: "A foto selecionada está vazia.", photoUploadFailed: "Não foi possível enviar a foto. Tente novamente.",
    photoUploadTimeout: "O envio da foto demorou demais. Verifique sua conexão e tente novamente.",
    cropTitle: "Recorte seu avatar", scale: "Escala", cancel: "Cancelar", saveAvatar: "Salvar avatar",
    saving: "", upload: "", photoPending: "A foto está sendo verificada automaticamente.",
    photoRejected: "A foto foi rejeitada. Escolha outra imagem.", photoApproved: "Foto aprovada.",
    avatarVerificationResetTitle: "Alterar a foto do perfil verificado?",
    avatarVerificationResetBody: "Se você substituir a foto principal, a verificação será redefinida e precisará ser refeita.",
    avatarVerificationResetAction: "Alterar foto", completed: "Perfil concluído", visible: "Visível no catálogo",
    premium: "Assinatura Premium", advisor: "AI Family Advisor", verification: "Verificação de perfil",
    notifications: "Configurações de notificação", language: "Idioma da interface", blocked: "Usuários bloqueados",
    delete: "Excluir conta", signOut: "Sair", editHeading: "Editar perfil", basicInfo: "Informações básicas",
    questionnaire: "Questionário de compatibilidade",
    questionnaireHelp: "Essas respostas determinam quem você vê e quem pode ver você.",
    who: "Quem você é", donorReady: "Pronto(a) para ser doador(a)", childContact: "Contato com a criança",
    editAnswers: "Editar respostas", noAnswer: "Não especificado", none: "Não",
    fullAnonymity: "Anonimato total", limitedContact: "Contato por acordo", openContact: "Contato aberto",
    metric: "kg/cm", imperial: "lb/ft", heightPlain: "Altura", weightPlain: "Peso", languagesPlain: "Idiomas",
    personal: "Dados pessoais", name: "Seu nome", dob: "Data de nascimento", country: "País", city: "Cidade",
    profileType: "Tipo de perfil", searchCity: "Comece a digitar uma cidade",
    chooseCountryFirst: "Selecione primeiro um país", noCitiesFound: "Nenhuma cidade encontrada",
    searchLanguage: "Comece a digitar um idioma...", noLanguagesFound: "Nenhum idioma encontrado",
    matching: "Compatibilidade", lookingFor: "Procurando por", appearance: "Aparência", height: "Altura (cm)",
    weight: "Peso (kg)", eye: "Cor dos olhos", hair: "Cor do cabelo", ethnicity: "Etnia",
    aboutSection: "Sobre mim", about: "Sobre você", occupation: "Profissão",
    occupationPlaceholder: "ex.: engenheiro(a) de software, professor(a)...", education: "Escolaridade",
    religion: "Religião", smoking: "Fumo", alcohol: "Álcool", languages: "Idiomas (separados por vírgula)",
    save: "Salvar alterações", saved: "Perfil salvo.", choose: "Escolher",
    verificationHeading: "Verificação de perfil",
    verificationTitle: "Vamos comparar seu selfie com sua foto principal",
    verificationBody: "Verifique se sua foto principal mostra claramente seu rosto — sem óculos escuros, boné ou celular cobrindo-o. Caso contrário, troque-a antes, ou a verificação falhará.",
    currentPhoto: "Sua foto principal", changeMainPhoto: "Alterar foto principal",
    startVerification: "Iniciar verificação", startingVerification: "Iniciando verificação…",
    continueVerification: "Continuar verificação", cancelVerification: "Cancelar",
    cancellingVerification: "Cancelando…",
    verificationCancelled: "Verificação cancelada. Você pode começar novamente a qualquer momento.",
    verificationCancelFailed: "Não foi possível cancelar a verificação. Tente novamente.",
    tryAgain: "Tentar novamente", verificationPending: "Verificação em análise",
    verificationApproved: "Perfil verificado", verificationComplete: "Verificação concluída",
    verificationSuccessTitle: "Verificação bem-sucedida", verificationSuccessBody: "Seu perfil foi verificado.",
    verificationFailureTitle: "Verificação sem sucesso", verificationFailed: "A verificação falhou. Você pode tentar novamente.",
    verificationResultOk: "OK",
    verificationPhotoRequired: "Envie uma foto principal aprovada antes de iniciar a verificação.",
    verificationLoadFailed: "Não foi possível carregar o status da verificação. Tente novamente.",
    verificationStartTimeout: "Não foi possível iniciar a verificação a tempo. Tente novamente.",
    verificationCreditsUnavailable: "A verificação de foto está temporariamente indisponível porque o serviço não tem créditos disponíveis.",
    providerUnavailable: "A verificação de foto está temporariamente indisponível.",
    notificationsTitle: "Notificações por e-mail",
    notificationsIntro: "Gerencie os e-mails que enviamos a você. As notificações push são controladas nas configurações do seu dispositivo.",
    newMatch: "Novos matches", newMatchHelp: "Quando alguém combina com você", newLike: "Novas curtidas",
    newLikeHelp: "Quando alguém curte seu perfil", newMessage: "Novas mensagens",
    newMessageHelp: "Quando alguém envia uma mensagem", profileView: "Visualizações do perfil",
    profileViewHelp: "Resumo diário de quem visualizou seu perfil", marketing: "Novidades e atualizações",
    marketingHelp: "Atualizações do produto e ofertas especiais", noBlocked: "Você não bloqueou ninguém.",
    unblock: "Desbloquear", selectLanguage: "Escolha o idioma da interface", close: "Fechar",
    deleteTitle: "Excluir conta",
    deleteBody: "Seu perfil será ocultado imediatamente. Sua conta e dados pessoais serão excluídos permanentemente após 30 dias.",
    deleteReason: "Por que você está saindo?", deleteConfirm: "Digite delete para confirmar",
    deleteWord: "delete", deleteButton: "Excluir minha conta", deletionSent: "Exclusão de conta agendada.",
  },
  fr: { ...ACCOUNT_COPY_BASE.en,
    back: "Retour au profil", blockedBack: "Mon profil", blockedTitle: "Utilisateurs bloqués",
    unblockConfirmPrefix: "Débloquer",
    unblockConfirmBody: "Cet utilisateur pourra à nouveau voir votre profil et vous écrire.",
    edit: "Modifier le profil", photos: "Modifier les photos", photosHeading: "Photos",
    photosIntro: "Ajoutez des photos à votre profil. La première photo sera votre avatar.",
    primary: "Principale", mainPhoto: "Photo principale", avatar: "Avatar", avatarSet: "Avatar défini",
    avatarNotSet: "Avatar non défini", changeAvatar: "Changer l'avatar", remove: "Supprimer",
    photoDeleteMainTitle: "Supprimer la photo principale ?",
    photoDeleteMainBody: "Votre photo principale et votre avatar seront supprimés. Voulez-vous vraiment continuer ?",
    photoDeleteAdditionalTitle: "Supprimer cette photo ?",
    photoDeleteAdditionalBody: "Cette photo sera définitivement supprimée de votre profil.",
    additionalPhotos: "Photos supplémentaires", addPhoto: "Ajouter une photo",
    uploadPrompt: "Cliquez pour envoyer ou déposez un fichier", photoHelp: "JPEG, PNG ou WebP (max. 10 Mo)",
    photoLimit: "Vous pouvez ajouter jusqu'à 6 photos.", photoLimitReached: "La limite de 6 photos est atteinte.",
    photoInvalid: "Seules les images JPEG, PNG et WebP sont acceptées.", photoTooLarge: "La photo ne doit pas dépasser 10 Mo.",
    photoEmpty: "La photo sélectionnée est vide.", photoUploadFailed: "Impossible d'envoyer la photo. Réessayez.",
    photoUploadTimeout: "L'envoi de la photo a pris trop de temps. Vérifiez votre connexion et réessayez.",
    cropTitle: "Recadrez votre avatar", scale: "Échelle", cancel: "Annuler", saveAvatar: "Enregistrer l'avatar",
    saving: "", upload: "", photoPending: "La photo est en cours de vérification automatique.",
    photoRejected: "La photo a été refusée. Choisissez une autre image.", photoApproved: "Photo approuvée.",
    avatarVerificationResetTitle: "Changer la photo du profil vérifié ?",
    avatarVerificationResetBody: "Si vous remplacez votre photo principale, votre vérification sera réinitialisée et vous devrez la refaire.",
    avatarVerificationResetAction: "Changer la photo", completed: "Profil complété", visible: "Visible dans le catalogue",
    premium: "Abonnement Premium", advisor: "AI Family Advisor", verification: "Vérification du profil",
    notifications: "Paramètres de notification", language: "Langue de l'interface", blocked: "Utilisateurs bloqués",
    delete: "Supprimer le compte", signOut: "Se déconnecter", editHeading: "Modifier le profil",
    basicInfo: "Informations de base", questionnaire: "Questionnaire de compatibilité",
    questionnaireHelp: "Ces réponses déterminent qui vous voyez et qui peut vous voir.",
    who: "Qui vous êtes", donorReady: "Prêt(e) à être donneur/donneuse", childContact: "Contact avec l'enfant",
    editAnswers: "Modifier les réponses", noAnswer: "Non précisé", none: "Non",
    fullAnonymity: "Anonymat complet", limitedContact: "Contact par accord", openContact: "Contact ouvert",
    metric: "kg/cm", imperial: "lb/ft", heightPlain: "Taille", weightPlain: "Poids", languagesPlain: "Langues",
    personal: "Informations personnelles", name: "Votre nom", dob: "Date de naissance", country: "Pays", city: "Ville",
    profileType: "Type de profil", searchCity: "Commencez à taper une ville",
    chooseCountryFirst: "Sélectionnez d'abord un pays", noCitiesFound: "Aucune ville trouvée",
    searchLanguage: "Commencez à taper une langue...", noLanguagesFound: "Aucune langue trouvée",
    matching: "Compatibilité", lookingFor: "Vous recherchez", appearance: "Apparence", height: "Taille (cm)",
    weight: "Poids (kg)", eye: "Couleur des yeux", hair: "Couleur des cheveux", ethnicity: "Origine ethnique",
    aboutSection: "À propos de moi", about: "À propos de vous", occupation: "Profession",
    occupationPlaceholder: "p. ex. ingénieur logiciel, enseignant...", education: "Formation",
    religion: "Religion", smoking: "Tabac", alcohol: "Alcool", languages: "Langues (séparées par des virgules)",
    save: "Enregistrer les modifications", saved: "Profil enregistré.", choose: "Choisir",
    verificationHeading: "Vérification du profil",
    verificationTitle: "Nous comparerons votre selfie à votre photo principale",
    verificationBody: "Assurez-vous que votre photo principale montre clairement votre visage — sans lunettes de soleil, casquette ni téléphone le cachant. Sinon, changez-la d'abord, sinon la vérification échouera.",
    currentPhoto: "Votre photo principale", changeMainPhoto: "Changer la photo principale",
    startVerification: "Démarrer la vérification", startingVerification: "Démarrage de la vérification…",
    continueVerification: "Continuer la vérification", cancelVerification: "Annuler",
    cancellingVerification: "Annulation…",
    verificationCancelled: "Vérification annulée. Vous pouvez recommencer à tout moment.",
    verificationCancelFailed: "Impossible d'annuler la vérification. Réessayez.",
    tryAgain: "Réessayer", verificationPending: "Vérification en cours d'examen",
    verificationApproved: "Profil vérifié", verificationComplete: "Vérification terminée",
    verificationSuccessTitle: "Vérification réussie", verificationSuccessBody: "Votre profil a été vérifié.",
    verificationFailureTitle: "Échec de la vérification", verificationFailed: "La vérification a échoué. Vous pouvez réessayer.",
    verificationResultOk: "OK",
    verificationPhotoRequired: "Envoyez une photo principale approuvée avant de démarrer la vérification.",
    verificationLoadFailed: "Impossible de charger le statut de la vérification. Réessayez.",
    verificationStartTimeout: "La vérification n'a pas pu démarrer à temps. Réessayez.",
    verificationCreditsUnavailable: "La vérification photo est temporairement indisponible car le service n'a plus de crédits.",
    providerUnavailable: "La vérification photo est temporairement indisponible.",
    notificationsTitle: "Notifications par e-mail",
    notificationsIntro: "Gérez les e-mails que nous vous envoyons. Les notifications push sont contrôlées dans les paramètres de votre appareil.",
    newMatch: "Nouveaux matchs", newMatchHelp: "Quand quelqu'un matche avec vous", newLike: "Nouveaux likes",
    newLikeHelp: "Quand quelqu'un aime votre profil", newMessage: "Nouveaux messages",
    newMessageHelp: "Quand quelqu'un vous envoie un message", profileView: "Vues du profil",
    profileViewHelp: "Résumé quotidien de qui a consulté votre profil", marketing: "Actualités et mises à jour",
    marketingHelp: "Mises à jour du produit et offres spéciales", noBlocked: "Vous n'avez bloqué personne.",
    unblock: "Débloquer", selectLanguage: "Choisissez la langue de l'interface", close: "Fermer",
    deleteTitle: "Supprimer le compte",
    deleteBody: "Votre profil sera masqué immédiatement. Votre compte et vos données personnelles seront définitivement supprimés après 30 jours.",
    deleteReason: "Pourquoi partez-vous ?", deleteConfirm: "Tapez delete pour confirmer",
    deleteWord: "delete", deleteButton: "Supprimer mon compte", deletionSent: "Suppression du compte programmée.",
  },
  de: { ...ACCOUNT_COPY_BASE.en,
    back: "Zurück zum Profil", blockedBack: "Mein Profil", blockedTitle: "Blockierte Nutzer",
    unblockConfirmPrefix: "Entsperren",
    unblockConfirmBody: "Dieser Nutzer kann Ihr Profil wieder sehen und Ihnen wieder schreiben.",
    edit: "Profil bearbeiten", photos: "Fotos bearbeiten", photosHeading: "Fotos",
    photosIntro: "Fügen Sie Ihrem Profil Fotos hinzu. Das erste Foto wird Ihr Avatar.",
    primary: "Hauptfoto", mainPhoto: "Hauptfoto", avatar: "Avatar", avatarSet: "Avatar festgelegt",
    avatarNotSet: "Avatar nicht festgelegt", changeAvatar: "Avatar ändern", remove: "Löschen",
    photoDeleteMainTitle: "Hauptfoto löschen?",
    photoDeleteMainBody: "Ihr Hauptfoto und Avatar werden entfernt. Möchten Sie wirklich fortfahren?",
    photoDeleteAdditionalTitle: "Dieses Foto löschen?",
    photoDeleteAdditionalBody: "Dieses Foto wird dauerhaft von Ihrem Profil entfernt.",
    additionalPhotos: "Weitere Fotos", addPhoto: "Weiteres Foto hinzufügen",
    uploadPrompt: "Klicken Sie zum Hochladen oder ziehen Sie eine Datei hierher", photoHelp: "JPEG, PNG oder WebP (max. 10 MB)",
    photoLimit: "Sie können bis zu 6 Fotos hochladen.", photoLimitReached: "Das Limit von 6 Fotos wurde erreicht.",
    photoInvalid: "Nur JPEG-, PNG- und WebP-Bilder werden unterstützt.", photoTooLarge: "Das Foto darf 10 MB nicht überschreiten.",
    photoEmpty: "Das ausgewählte Foto ist leer.", photoUploadFailed: "Das Foto konnte nicht hochgeladen werden. Versuchen Sie es erneut.",
    photoUploadTimeout: "Der Foto-Upload hat zu lange gedauert. Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.",
    cropTitle: "Avatar zuschneiden", scale: "Zoom", cancel: "Abbrechen", saveAvatar: "Avatar speichern",
    saving: "", upload: "", photoPending: "Das Foto wird automatisch geprüft.",
    photoRejected: "Das Foto wurde abgelehnt. Wählen Sie ein anderes Bild.", photoApproved: "Foto genehmigt.",
    avatarVerificationResetTitle: "Foto des verifizierten Profils ändern?",
    avatarVerificationResetBody: "Wenn Sie Ihr Hauptfoto ersetzen, wird Ihre Verifizierung zurückgesetzt und muss erneut durchgeführt werden.",
    avatarVerificationResetAction: "Foto ändern", completed: "Profil vollständig", visible: "Im Katalog sichtbar",
    premium: "Premium-Abonnement", advisor: "AI Family Advisor", verification: "Profilverifizierung",
    notifications: "Benachrichtigungseinstellungen", language: "Oberflächensprache", blocked: "Blockierte Nutzer",
    delete: "Konto löschen", signOut: "Abmelden", editHeading: "Profil bearbeiten",
    basicInfo: "Grundinformationen", questionnaire: "Matching-Fragebogen",
    questionnaireHelp: "Diese Antworten bestimmen, wen Sie sehen und wer Sie sehen kann.",
    who: "Wer Sie sind", donorReady: "Bereit, Spender/in zu sein", childContact: "Kontakt zum Kind",
    editAnswers: "Antworten bearbeiten", noAnswer: "Nicht angegeben", none: "Nein",
    fullAnonymity: "Vollständige Anonymität", limitedContact: "Kontakt nach Vereinbarung", openContact: "Offener Kontakt",
    metric: "kg/cm", imperial: "lb/ft", heightPlain: "Größe", weightPlain: "Gewicht", languagesPlain: "Sprachen",
    personal: "Persönliche Angaben", name: "Ihr Name", dob: "Geburtsdatum", country: "Land", city: "Stadt",
    profileType: "Profiltyp", searchCity: "Stadt eingeben",
    chooseCountryFirst: "Wählen Sie zuerst ein Land", noCitiesFound: "Keine Städte gefunden",
    searchLanguage: "Sprache eingeben...", noLanguagesFound: "Keine Sprachen gefunden",
    matching: "Matching", lookingFor: "Ich suche", appearance: "Aussehen", height: "Größe (cm)",
    weight: "Gewicht (kg)", eye: "Augenfarbe", hair: "Haarfarbe", ethnicity: "Ethnizität",
    aboutSection: "Über mich", about: "Über Sie", occupation: "Beruf",
    occupationPlaceholder: "z. B. Softwareentwickler/in, Lehrer/in...", education: "Ausbildung",
    religion: "Religion", smoking: "Rauchen", alcohol: "Alkohol", languages: "Sprachen (durch Komma getrennt)",
    save: "Änderungen speichern", saved: "Profil gespeichert.", choose: "Auswählen",
    verificationHeading: "Profilverifizierung",
    verificationTitle: "Wir gleichen Ihr Selfie mit Ihrem Hauptfoto ab",
    verificationBody: "Stellen Sie sicher, dass Ihr Hauptfoto Ihr Gesicht deutlich zeigt — ohne Sonnenbrille, Mütze oder Telefon, das es verdeckt. Andernfalls ändern Sie es zuerst, sonst schlägt die Verifizierung fehl.",
    currentPhoto: "Ihr Hauptfoto", changeMainPhoto: "Hauptfoto ändern",
    startVerification: "Verifizierung starten", startingVerification: "Verifizierung wird gestartet…",
    continueVerification: "Verifizierung fortsetzen", cancelVerification: "Abbrechen",
    cancellingVerification: "Wird abgebrochen…",
    verificationCancelled: "Verifizierung abgebrochen. Sie können sie jederzeit erneut starten.",
    verificationCancelFailed: "Die Verifizierung konnte nicht abgebrochen werden. Versuchen Sie es erneut.",
    tryAgain: "Erneut versuchen", verificationPending: "Verifizierung wird geprüft",
    verificationApproved: "Profil verifiziert", verificationComplete: "Verifizierung abgeschlossen",
    verificationSuccessTitle: "Verifizierung erfolgreich", verificationSuccessBody: "Ihr Profil wurde verifiziert.",
    verificationFailureTitle: "Verifizierung nicht erfolgreich", verificationFailed: "Die Verifizierung ist fehlgeschlagen. Sie können es erneut versuchen.",
    verificationResultOk: "OK",
    verificationPhotoRequired: "Laden Sie ein genehmigtes Hauptfoto hoch, bevor Sie die Verifizierung starten.",
    verificationLoadFailed: "Der Verifizierungsstatus konnte nicht geladen werden. Versuchen Sie es erneut.",
    verificationStartTimeout: "Die Verifizierung konnte nicht rechtzeitig gestartet werden. Versuchen Sie es erneut.",
    verificationCreditsUnavailable: "Die Fotoverifizierung ist vorübergehend nicht verfügbar, da der Verifizierungsdienst kein Guthaben mehr hat.",
    providerUnavailable: "Die Fotoverifizierung ist vorübergehend nicht verfügbar.",
    notificationsTitle: "E-Mail-Benachrichtigungen",
    notificationsIntro: "Verwalten Sie die E-Mails, die wir Ihnen senden. Push-Benachrichtigungen werden über die Geräteeinstellungen gesteuert.",
    newMatch: "Neue Matches", newMatchHelp: "Wenn jemand mit Ihnen matcht", newLike: "Neue Likes",
    newLikeHelp: "Wenn jemandem Ihr Profil gefällt", newMessage: "Neue Nachrichten",
    newMessageHelp: "Wenn Ihnen jemand eine Nachricht sendet", profileView: "Profilaufrufe",
    profileViewHelp: "Tägliche Zusammenfassung, wer Ihr Profil angesehen hat", marketing: "Neuigkeiten & Updates",
    marketingHelp: "Produkt-Updates und Sonderangebote", noBlocked: "Sie haben niemanden blockiert.",
    unblock: "Entsperren", selectLanguage: "Oberflächensprache wählen", close: "Schließen",
    deleteTitle: "Konto löschen",
    deleteBody: "Ihr Profil wird sofort ausgeblendet. Ihr Konto und Ihre persönlichen Daten werden nach 30 Tagen endgültig gelöscht.",
    deleteReason: "Warum verlassen Sie uns?", deleteConfirm: "Geben Sie delete ein, um zu bestätigen",
    deleteWord: "delete", deleteButton: "Mein Konto löschen", deletionSent: "Kontolöschung geplant.",
  },
  it: { ...ACCOUNT_COPY_BASE.en,
    back: "Torna al profilo", blockedBack: "Il mio profilo", blockedTitle: "Utenti bloccati",
    unblockConfirmPrefix: "Sblocca",
    unblockConfirmBody: "Questo utente potrà vedere di nuovo il tuo profilo e scriverti.",
    edit: "Modifica profilo", photos: "Modifica foto", photosHeading: "Foto",
    photosIntro: "Aggiungi foto al tuo profilo. La prima foto sarà il tuo avatar.",
    primary: "Principale", mainPhoto: "Foto principale", avatar: "Avatar", avatarSet: "Avatar impostato",
    avatarNotSet: "Avatar non impostato", changeAvatar: "Cambia avatar", remove: "Elimina",
    photoDeleteMainTitle: "Eliminare la foto principale?",
    photoDeleteMainBody: "La tua foto principale e il tuo avatar verranno rimossi. Vuoi davvero continuare?",
    photoDeleteAdditionalTitle: "Eliminare questa foto?",
    photoDeleteAdditionalBody: "Questa foto verrà rimossa definitivamente dal tuo profilo.",
    additionalPhotos: "Foto aggiuntive", addPhoto: "Aggiungi un'altra foto",
    uploadPrompt: "Clicca per caricare o trascina un file", photoHelp: "JPEG, PNG o WebP (max. 10 MB)",
    photoLimit: "Puoi caricare fino a 6 foto.", photoLimitReached: "Hai raggiunto il limite di 6 foto.",
    photoInvalid: "Sono supportate solo immagini JPEG, PNG e WebP.", photoTooLarge: "La foto non deve superare i 10 MB.",
    photoEmpty: "La foto selezionata è vuota.", photoUploadFailed: "Impossibile caricare la foto. Riprova.",
    photoUploadTimeout: "Il caricamento della foto ha impiegato troppo tempo. Controlla la connessione e riprova.",
    cropTitle: "Ritaglia il tuo avatar", scale: "Zoom", cancel: "Annulla", saveAvatar: "Salva avatar",
    saving: "", upload: "", photoPending: "La foto è in fase di controllo automatico.",
    photoRejected: "La foto è stata rifiutata. Scegli un'altra immagine.", photoApproved: "Foto approvata.",
    avatarVerificationResetTitle: "Cambiare la foto del profilo verificato?",
    avatarVerificationResetBody: "Se sostituisci la foto principale, la verifica verrà azzerata e dovrai rifarla.",
    avatarVerificationResetAction: "Cambia foto", completed: "Profilo completato", visible: "Visibile nel catalogo",
    premium: "Abbonamento Premium", advisor: "AI Family Advisor", verification: "Verifica del profilo",
    notifications: "Impostazioni notifiche", language: "Lingua dell'interfaccia", blocked: "Utenti bloccati",
    delete: "Elimina account", signOut: "Esci", editHeading: "Modifica profilo",
    basicInfo: "Informazioni di base", questionnaire: "Questionario di compatibilità",
    questionnaireHelp: "Queste risposte determinano chi vedi e chi può vederti.",
    who: "Chi sei", donorReady: "Disposto/a a essere donatore/donatrice", childContact: "Contatto con il bambino",
    editAnswers: "Modifica risposte", noAnswer: "Non specificato", none: "No",
    fullAnonymity: "Anonimato completo", limitedContact: "Contatto su accordo", openContact: "Contatto aperto",
    metric: "kg/cm", imperial: "lb/ft", heightPlain: "Altezza", weightPlain: "Peso", languagesPlain: "Lingue",
    personal: "Dati personali", name: "Il tuo nome", dob: "Data di nascita", country: "Paese", city: "Città",
    profileType: "Tipo di profilo", searchCity: "Inizia a digitare una città",
    chooseCountryFirst: "Seleziona prima un paese", noCitiesFound: "Nessuna città trovata",
    searchLanguage: "Inizia a digitare una lingua...", noLanguagesFound: "Nessuna lingua trovata",
    matching: "Compatibilità", lookingFor: "Sto cercando", appearance: "Aspetto", height: "Altezza (cm)",
    weight: "Peso (kg)", eye: "Colore degli occhi", hair: "Colore dei capelli", ethnicity: "Etnia",
    aboutSection: "Su di me", about: "Su di te", occupation: "Occupazione",
    occupationPlaceholder: "es. ingegnere software, insegnante...", education: "Istruzione",
    religion: "Religione", smoking: "Fumo", alcohol: "Alcol", languages: "Lingue (separate da virgola)",
    save: "Salva modifiche", saved: "Profilo salvato.", choose: "Scegli",
    verificationHeading: "Verifica del profilo",
    verificationTitle: "Confronteremo il tuo selfie con la tua foto principale",
    verificationBody: "Assicurati che la tua foto principale mostri chiaramente il tuo viso — senza occhiali da sole, cappello o telefono che lo coprano. In caso contrario, cambiala prima, altrimenti la verifica fallirà.",
    currentPhoto: "La tua foto principale", changeMainPhoto: "Cambia foto principale",
    startVerification: "Avvia verifica", startingVerification: "Avvio della verifica…",
    continueVerification: "Continua verifica", cancelVerification: "Annulla",
    cancellingVerification: "Annullamento…",
    verificationCancelled: "Verifica annullata. Puoi ricominciare in qualsiasi momento.",
    verificationCancelFailed: "Impossibile annullare la verifica. Riprova.",
    tryAgain: "Riprova", verificationPending: "Verifica in revisione",
    verificationApproved: "Profilo verificato", verificationComplete: "Verifica completata",
    verificationSuccessTitle: "Verifica completata con successo", verificationSuccessBody: "Il tuo profilo è stato verificato.",
    verificationFailureTitle: "Verifica non riuscita", verificationFailed: "La verifica non è riuscita. Puoi riprovare.",
    verificationResultOk: "OK",
    verificationPhotoRequired: "Carica una foto principale approvata prima di avviare la verifica.",
    verificationLoadFailed: "Impossibile caricare lo stato della verifica. Riprova.",
    verificationStartTimeout: "Non è stato possibile avviare la verifica in tempo. Riprova.",
    verificationCreditsUnavailable: "La verifica foto è temporaneamente non disponibile perché il servizio non ha crediti disponibili.",
    providerUnavailable: "La verifica foto è temporaneamente non disponibile.",
    notificationsTitle: "Notifiche via email",
    notificationsIntro: "Gestisci le email che ti inviamo. Le notifiche push si controllano dalle impostazioni del dispositivo.",
    newMatch: "Nuovi match", newMatchHelp: "Quando qualcuno fa match con te", newLike: "Nuovi like",
    newLikeHelp: "Quando a qualcuno piace il tuo profilo", newMessage: "Nuovi messaggi",
    newMessageHelp: "Quando qualcuno ti invia un messaggio", profileView: "Visualizzazioni del profilo",
    profileViewHelp: "Riepilogo giornaliero di chi ha visto il tuo profilo", marketing: "Novità e aggiornamenti",
    marketingHelp: "Aggiornamenti del prodotto e offerte speciali", noBlocked: "Non hai bloccato nessuno.",
    unblock: "Sblocca", selectLanguage: "Scegli la lingua dell'interfaccia", close: "Chiudi",
    deleteTitle: "Elimina account",
    deleteBody: "Il tuo profilo verrà nascosto immediatamente. Il tuo account e i tuoi dati personali verranno eliminati definitivamente dopo 30 giorni.",
    deleteReason: "Perché te ne vai?", deleteConfirm: "Digita delete per confermare",
    deleteWord: "delete", deleteButton: "Elimina il mio account", deletionSent: "Eliminazione dell'account programmata.",
  },
  pl: { ...ACCOUNT_COPY_BASE.en,
    back: "Powrót do profilu", blockedBack: "Mój profil", blockedTitle: "Zablokowani użytkownicy",
    unblockConfirmPrefix: "Odblokuj",
    unblockConfirmBody: "Ten użytkownik będzie mógł ponownie zobaczyć Twój profil i napisać do Ciebie.",
    edit: "Edytuj profil", photos: "Edytuj zdjęcia", photosHeading: "Zdjęcia",
    photosIntro: "Dodaj zdjęcia do swojego profilu. Pierwsze zdjęcie będzie Twoim awatarem.",
    primary: "Główne", mainPhoto: "Główne zdjęcie", avatar: "Awatar", avatarSet: "Awatar ustawiony",
    avatarNotSet: "Awatar nieustawiony", changeAvatar: "Zmień awatar", remove: "Usuń",
    photoDeleteMainTitle: "Usunąć główne zdjęcie?",
    photoDeleteMainBody: "Twoje główne zdjęcie i awatar zostaną usunięte. Czy na pewno chcesz kontynuować?",
    photoDeleteAdditionalTitle: "Usunąć to zdjęcie?",
    photoDeleteAdditionalBody: "To zdjęcie zostanie trwale usunięte z Twojego profilu.",
    additionalPhotos: "Dodatkowe zdjęcia", addPhoto: "Dodaj kolejne zdjęcie",
    uploadPrompt: "Kliknij, aby przesłać, lub przeciągnij plik", photoHelp: "JPEG, PNG lub WebP (maks. 10 MB)",
    photoLimit: "Możesz przesłać maksymalnie 6 zdjęć.", photoLimitReached: "Osiągnięto limit 6 zdjęć.",
    photoInvalid: "Obsługiwane są tylko obrazy JPEG, PNG i WebP.", photoTooLarge: "Zdjęcie nie może przekraczać 10 MB.",
    photoEmpty: "Wybrane zdjęcie jest puste.", photoUploadFailed: "Nie udało się przesłać zdjęcia. Spróbuj ponownie.",
    photoUploadTimeout: "Przesyłanie zdjęcia trwało zbyt długo. Sprawdź połączenie i spróbuj ponownie.",
    cropTitle: "Przytnij swój awatar", scale: "Skala", cancel: "Anuluj", saveAvatar: "Zapisz awatar",
    saving: "", upload: "", photoPending: "Zdjęcie jest automatycznie sprawdzane.",
    photoRejected: "Zdjęcie zostało odrzucone. Wybierz inny obraz.", photoApproved: "Zdjęcie zatwierdzone.",
    avatarVerificationResetTitle: "Zmienić zdjęcie zweryfikowanego profilu?",
    avatarVerificationResetBody: "Jeśli zmienisz główne zdjęcie, weryfikacja zostanie zresetowana i trzeba będzie przejść ją ponownie.",
    avatarVerificationResetAction: "Zmień zdjęcie", completed: "Profil uzupełniony", visible: "Widoczny w katalogu",
    premium: "Subskrypcja Premium", advisor: "AI Family Advisor", verification: "Weryfikacja profilu",
    notifications: "Ustawienia powiadomień", language: "Język interfejsu", blocked: "Zablokowani użytkownicy",
    delete: "Usuń konto", signOut: "Wyloguj się", editHeading: "Edytuj profil",
    basicInfo: "Podstawowe informacje", questionnaire: "Kwestionariusz dopasowania",
    questionnaireHelp: "Te odpowiedzi decydują o tym, kogo widzisz i kto widzi Ciebie.",
    who: "Kim jesteś", donorReady: "Gotowość zostania dawcą/dawczynią", childContact: "Kontakt z dzieckiem",
    editAnswers: "Edytuj odpowiedzi", noAnswer: "Nie podano", none: "Nie",
    fullAnonymity: "Pełna anonimowość", limitedContact: "Kontakt na podstawie ustaleń", openContact: "Otwarty kontakt",
    metric: "kg/cm", imperial: "lb/ft", heightPlain: "Wzrost", weightPlain: "Waga", languagesPlain: "Języki",
    personal: "Dane osobowe", name: "Twoje imię", dob: "Data urodzenia", country: "Kraj", city: "Miasto",
    profileType: "Typ profilu", searchCity: "Zacznij wpisywać miasto",
    chooseCountryFirst: "Najpierw wybierz kraj", noCitiesFound: "Nie znaleziono miast",
    searchLanguage: "Zacznij wpisywać język...", noLanguagesFound: "Nie znaleziono języków",
    matching: "Dopasowanie", lookingFor: "Szukam", appearance: "Wygląd", height: "Wzrost (cm)",
    weight: "Waga (kg)", eye: "Kolor oczu", hair: "Kolor włosów", ethnicity: "Pochodzenie etniczne",
    aboutSection: "O mnie", about: "O Tobie", occupation: "Zawód",
    occupationPlaceholder: "np. inżynier oprogramowania, nauczyciel...", education: "Wykształcenie",
    religion: "Religia", smoking: "Palenie", alcohol: "Alkohol", languages: "Języki (oddzielone przecinkami)",
    save: "Zapisz zmiany", saved: "Profil zapisany.", choose: "Wybierz",
    verificationHeading: "Weryfikacja profilu",
    verificationTitle: "Porównamy Twoje selfie z głównym zdjęciem",
    verificationBody: "Upewnij się, że na głównym zdjęciu wyraźnie widać Twoją twarz — bez okularów przeciwsłonecznych, czapki czy telefonu ją zasłaniającego. W przeciwnym razie zmień je najpierw, w przeciwnym razie weryfikacja się nie powiedzie.",
    currentPhoto: "Twoje główne zdjęcie", changeMainPhoto: "Zmień główne zdjęcie",
    startVerification: "Rozpocznij weryfikację", startingVerification: "Rozpoczynanie weryfikacji…",
    continueVerification: "Kontynuuj weryfikację", cancelVerification: "Anuluj",
    cancellingVerification: "Anulowanie…",
    verificationCancelled: "Weryfikacja anulowana. Możesz zacząć ponownie w dowolnym momencie.",
    verificationCancelFailed: "Nie udało się anulować weryfikacji. Spróbuj ponownie.",
    tryAgain: "Spróbuj ponownie", verificationPending: "Weryfikacja w trakcie sprawdzania",
    verificationApproved: "Profil zweryfikowany", verificationComplete: "Weryfikacja zakończona",
    verificationSuccessTitle: "Weryfikacja zakończona sukcesem", verificationSuccessBody: "Twój profil został zweryfikowany.",
    verificationFailureTitle: "Weryfikacja nieudana", verificationFailed: "Weryfikacja nie powiodła się. Możesz spróbować ponownie.",
    verificationResultOk: "OK",
    verificationPhotoRequired: "Prześlij zatwierdzone główne zdjęcie przed rozpoczęciem weryfikacji.",
    verificationLoadFailed: "Nie udało się załadować statusu weryfikacji. Spróbuj ponownie.",
    verificationStartTimeout: "Nie udało się rozpocząć weryfikacji na czas. Spróbuj ponownie.",
    verificationCreditsUnavailable: "Weryfikacja zdjęcia jest tymczasowo niedostępna, ponieważ usługa weryfikacji nie ma dostępnych środków.",
    providerUnavailable: "Weryfikacja zdjęcia jest tymczasowo niedostępna.",
    notificationsTitle: "Powiadomienia e-mail",
    notificationsIntro: "Zarządzaj e-mailami, które do Ciebie wysyłamy. Powiadomienia push są kontrolowane w ustawieniach urządzenia.",
    newMatch: "Nowe dopasowania", newMatchHelp: "Gdy ktoś się z Tobą dopasuje", newLike: "Nowe polubienia",
    newLikeHelp: "Gdy ktoś polubi Twój profil", newMessage: "Nowe wiadomości",
    newMessageHelp: "Gdy ktoś wyśle Ci wiadomość", profileView: "Wyświetlenia profilu",
    profileViewHelp: "Codzienne podsumowanie osób, które wyświetliły Twój profil", marketing: "Nowości i aktualizacje",
    marketingHelp: "Aktualizacje produktu i oferty specjalne", noBlocked: "Nikogo nie zablokowałeś/aś.",
    unblock: "Odblokuj", selectLanguage: "Wybierz język interfejsu", close: "Zamknij",
    deleteTitle: "Usuń konto",
    deleteBody: "Twój profil zostanie natychmiast ukryty. Twoje konto i dane osobowe zostaną trwale usunięte po 30 dniach.",
    deleteReason: "Dlaczego odchodzisz?", deleteConfirm: "Wpisz delete, aby potwierdzić",
    deleteWord: "delete", deleteButton: "Usuń moje konto", deletionSent: "Zaplanowano usunięcie konta.",
  },
} as const;

export const ACCOUNT_ICONS = {
  eyeIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"></path><circle cx="12" cy="12" r="2.5"></circle></svg>',
  lockIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><rect width="14" height="10" x="5" y="11" rx="2"></rect><path d="M8 11V7a4 4 0 0 1 8 0v4"></path></svg>',
  globeIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"></circle><path d="M3 12h18"></path><path d="M12 3c2.4 2.5 3.6 5.5 3.6 9S14.4 18.5 12 21c-2.4-2.5-3.6-5.5-3.6-9S9.6 5.5 12 3Z"></path></svg>',
  edit: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M11.5 15H7a4 4 0 0 0-4 4v2"></path><path d="M21.378 16.626a1 1 0 0 0-3.004-3.004l-4.01 4.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z"></path><circle cx="10" cy="7" r="4"></circle></svg>',
  premium:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z"></path><path d="M5 21h14"></path></svg>',
  verification:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"></path><path d="m9 12 2 2 4-4"></path></svg>',
  notifications:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10.268 21a2 2 0 0 0 3.464 0"></path><path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"></path></svg>',
  language:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 8 6 6"></path><path d="m4 14 6-6 2-3"></path><path d="M2 5h12"></path><path d="M7 2h1"></path><path d="m22 22-5-10-5 10"></path><path d="M14 18h6"></path></svg>',
  blocked:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><path d="M4.929 4.929 19.07 19.071"></path></svg>',
  delete:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 11v6"></path><path d="M14 11v6"></path><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"></path><path d="M3 6h18"></path><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>',
  signout:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m16 17 5-5-5-5"></path><path d="M21 12H9"></path><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path></svg>',
  cameraIcon:
    '<svg class="action-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M14.5 4h-5L7.7 6H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-2.7L14.5 4Z"></path><circle cx="12" cy="13" r="3"></circle></svg>',
  mailIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"></rect><path d="m3 7 9 6 9-6"></path></svg>',
  languageCheckIcon:
    '<svg class="language-selected-check" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"></path></svg>',
  savedFavouriteIcon:
    '<svg class="saved-directory-button-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z"></path><path d="M7 10v12"></path></svg>',
  // Added Sept 2026 for the account-page nav-parity tiles (Boost,
  // Community, Invite/Referral) - Alena: "на сайте нету половины меню
  // как в приложении" (the site's own /profile page never got the same
  // MemberLinks sub-nav every other member page has, so Boost/Community/
  // Referral/Safety Check-In/Saved were unreachable from here).
  boostIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13 2 3 14h7l-1 8 10-12h-7z"></path></svg>',
  communityIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>',
  referralIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="8" width="18" height="4"></rect><path d="M12 8v13"></path><path d="M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7"></path><path d="M7.5 8a2.5 2.5 0 0 1 0-5C11 3 12 8 12 8"></path><path d="M16.5 8a2.5 2.5 0 0 0 0-5C13 3 12 8 12 8"></path></svg>',
  // A separate icon (not a reuse of "verification") specifically so the
  // Safety Check-In tile below never accidentally picks up the
  // setting()-helper's verification-only green styling
  // (action === "verification" && verified ? " account-setting-verified"
  // : "" in Overview() - a real profile-verification-specific class, not
  // a generic "looks fine" indicator).
  safetyIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"></path><path d="M12 8v4"></path><path d="M12 16h.01"></path></svg>',
} as const;

const ACCOUNT_DELETION_REASONS_BASE = {
  en: [
    "No matches",
    "No longer interested",
    "Found what I was looking for",
    "Too expensive",
    "Privacy concerns",
    "Technical problems",
    "Taking a break",
    "Other",
    "Prefer not to say",
  ],
  ru: [
    "Нет совпадений",
    "Больше неинтересно",
    "Я нашёл то, что искал",
    "Слишком дорого",
    "Опасения о конфиденциальности",
    "Технические проблемы",
    "Просто делаю перерыв",
    "Другое",
    "Предпочитаю не отвечать",
  ],
  es: [
    "Sin coincidencias",
    "Ya no me interesa",
    "Encontré lo que buscaba",
    "Demasiado caro",
    "Privacidad",
    "Problemas técnicos",
    "Tomarme un descanso",
    "Otro",
    "Prefiero no decirlo",
  ],
} as const;

export const ACCOUNT_DELETION_REASONS = {
  ...ACCOUNT_DELETION_REASONS_BASE,
  pt: [
    "Nenhum match",
    "Não tenho mais interesse",
    "Encontrei o que procurava",
    "Muito caro",
    "Preocupações com privacidade",
    "Problemas técnicos",
    "Fazendo uma pausa",
    "Outro",
    "Prefiro não dizer",
  ],
  fr: [
    "Aucun match",
    "Plus intéressé(e)",
    "J'ai trouvé ce que je cherchais",
    "Trop cher",
    "Préoccupations liées à la confidentialité",
    "Problèmes techniques",
    "Je fais une pause",
    "Autre",
    "Je préfère ne pas répondre",
  ],
  de: [
    "Keine Matches",
    "Kein Interesse mehr",
    "Ich habe gefunden, wonach ich gesucht habe",
    "Zu teuer",
    "Datenschutzbedenken",
    "Technische Probleme",
    "Ich mache eine Pause",
    "Sonstiges",
    "Möchte ich nicht sagen",
  ],
  it: [
    "Nessun match",
    "Non più interessato/a",
    "Ho trovato quello che cercavo",
    "Troppo costoso",
    "Preoccupazioni sulla privacy",
    "Problemi tecnici",
    "Mi sto prendendo una pausa",
    "Altro",
    "Preferisco non dirlo",
  ],
  pl: [
    "Brak dopasowań",
    "Nie jestem już zainteresowany/a",
    "Znalazłem/am to, czego szukałem/am",
    "Zbyt drogie",
    "Obawy dotyczące prywatności",
    "Problemy techniczne",
    "Robię sobie przerwę",
    "Inne",
    "Wolę nie odpowiadać",
  ],
} as const;

const LIKES_COPY_BASE = {
  en: {
    likesTitle: "Likes",
    likesYou: "Likes you",
    matches: "Matches",
    myLikes: "My likes",
    visitors: "Visitors",
    clinics: "Clinics",
    lawyers: "Lawyers",
    noLikes:
      "No one has liked you yet. Complete your profile to attract more attention!",
    noMatches: "You do not have any matches yet.",
    myLikesEmpty: "Profiles you like will appear here.",
    noViews: "No one has viewed your profile yet.",
    savedClinics:
      "You haven't saved any clinics yet. Browse clinics to add them to your favorites!",
    savedLawyers:
      "You haven't saved any lawyers yet. Browse lawyers to add them to your favorites!",
    peopleLiked: "people liked your profile",
    peopleViewed: "people viewed your profile",
    likesPremium: "Upgrade to Premium to see who liked you",
    viewsPremium: "Upgrade to Premium to see profile visitors",
    saved: "Liked",
    favouriteRemoveFailed: "Could not remove this item from saved.",
    like: "Like",
    liked: "Liked",
    sendMessage: "Send message",
  },
  ru: {
    likesTitle: "Лайки",
    likesYou: "Вас лайкнули",
    matches: "Совпадения",
    myLikes: "Мои лайки",
    visitors: "Гости",
    clinics: "Клиники",
    lawyers: "Юристы",
    noLikes:
      "Вам пока не поставили лайк. Заполните профиль, чтобы привлечь больше внимания.",
    noMatches: "Совпадений пока нет.",
    myLikesEmpty: "Понравившиеся анкеты появятся здесь.",
    noViews: "Ваш профиль пока никто не просматривал.",
    savedClinics:
      "Вы пока не сохранили ни одной клиники. Добавьте понравившиеся клиники в избранное!",
    savedLawyers:
      "Вы пока не сохранили ни одного юриста. Добавьте понравившихся юристов в избранное!",
    peopleLiked: "человек отметили вашу анкету",
    peopleViewed: "человек посмотрели вашу анкету",
    likesPremium: "Перейдите на Premium, чтобы увидеть, кому вы понравились",
    viewsPremium: "Перейдите на Premium, чтобы увидеть посетителей профиля",
    saved: "В избранном",
    favouriteRemoveFailed: "Не удалось удалить из избранного.",
    like: "Нравится",
    liked: "Понравилось",
    sendMessage: "Отправить сообщение",
  },
  es: {
    likesTitle: "Me gusta",
    likesYou: "Les gustas",
    matches: "Coincidencias",
    myLikes: "Mis Me gusta",
    visitors: "Visitantes",
    clinics: "Clínicas",
    lawyers: "Abogados",
    noLikes:
      "Aún no le has gustado a nadie. Completa tu perfil para atraer más atención.",
    noMatches: "Aún no tienes coincidencias.",
    myLikesEmpty: "Los perfiles que te gusten aparecerán aquí.",
    noViews: "Nadie ha visto tu perfil todavía.",
    savedClinics:
      "Aún no has guardado ninguna clínica. Añade tus clínicas favoritas.",
    savedLawyers:
      "Aún no has guardado ningún abogado. Añade tus abogados favoritos.",
    peopleLiked: "personas marcaron tu perfil",
    peopleViewed: "personas vieron tu perfil",
    likesPremium: "Mejora a Premium para ver a quién le gustas",
    viewsPremium: "Mejora a Premium para ver visitantes",
    saved: "Guardado",
    favouriteRemoveFailed: "No se pudo quitar de guardados.",
    like: "Me gusta",
    liked: "Me gustó",
    sendMessage: "Enviar mensaje",
  },
} as const;

export const LIKES_COPY = {
  ...LIKES_COPY_BASE,
  pt: { likesTitle: "Gostos", likesYou: "Gostam de ti", matches: "Correspondências", myLikes: "Os meus gostos", visitors: "Visitantes", clinics: "Clínicas", lawyers: "Advogados", noLikes: "Ainda ninguém gostou de ti. Completa o teu perfil para atrair mais atenção!", noMatches: "Ainda não tens correspondências.", myLikesEmpty: "Os perfis de que gostares vão aparecer aqui.", noViews: "Ainda ninguém viu o teu perfil.", savedClinics: "Ainda não guardaste nenhuma clínica. Explora as clínicas para as adicionares aos teus favoritos!", savedLawyers: "Ainda não guardaste nenhum advogado. Explora os advogados para os adicionares aos teus favoritos!", peopleLiked: "pessoas gostaram do teu perfil", peopleViewed: "pessoas visualizaram o teu perfil", likesPremium: "Atualiza para Premium para veres quem gostou de ti", viewsPremium: "Atualiza para Premium para veres os visitantes do perfil", saved: "Guardado", favouriteRemoveFailed: "Não foi possível remover este item dos favoritos.", like: "Gosto", liked: "Gostei", sendMessage: "Enviar mensagem" },
  fr: { likesTitle: "J'aime", likesYou: "Vous plaisez", matches: "Matchs", myLikes: "Mes J'aime", visitors: "Visiteurs", clinics: "Cliniques", lawyers: "Avocats", noLikes: "Personne ne vous a encore aimé(e). Complétez votre profil pour attirer plus d'attention !", noMatches: "Vous n'avez pas encore de matchs.", myLikesEmpty: "Les profils que vous aimez apparaîtront ici.", noViews: "Personne n'a encore consulté votre profil.", savedClinics: "Vous n'avez enregistré aucune clinique pour le moment. Parcourez les cliniques pour les ajouter à vos favoris !", savedLawyers: "Vous n'avez enregistré aucun avocat pour le moment. Parcourez les avocats pour les ajouter à vos favoris !", peopleLiked: "personnes ont aimé votre profil", peopleViewed: "personnes ont consulté votre profil", likesPremium: "Passez à Premium pour voir qui vous a aimé(e)", viewsPremium: "Passez à Premium pour voir les visiteurs de votre profil", saved: "Enregistré", favouriteRemoveFailed: "Impossible de retirer cet élément des favoris.", like: "J'aime", liked: "Aimé", sendMessage: "Envoyer un message" },
  de: { likesTitle: "Likes", likesYou: "Likes für dich", matches: "Matches", myLikes: "Meine Likes", visitors: "Besucher", clinics: "Kliniken", lawyers: "Anwälte", noLikes: "Bisher hat dir noch niemand ein Like gegeben. Vervollständige dein Profil, um mehr Aufmerksamkeit zu bekommen!", noMatches: "Du hast noch keine Matches.", myLikesEmpty: "Profile, die dir gefallen, erscheinen hier.", noViews: "Dein Profil wurde noch von niemandem angesehen.", savedClinics: "Du hast noch keine Kliniken gespeichert. Durchstöbere die Kliniken, um sie zu deinen Favoriten hinzuzufügen!", savedLawyers: "Du hast noch keine Anwälte gespeichert. Durchstöbere die Anwälte, um sie zu deinen Favoriten hinzuzufügen!", peopleLiked: "Personen gefällt dein Profil", peopleViewed: "Personen haben dein Profil angesehen", likesPremium: "Hol dir Premium, um zu sehen, wem du gefällst", viewsPremium: "Hol dir Premium, um die Besucher deines Profils zu sehen", saved: "Gespeichert", favouriteRemoveFailed: "Dieser Eintrag konnte nicht aus den Favoriten entfernt werden.", like: "Like", liked: "Geliked", sendMessage: "Nachricht senden" },
  it: { likesTitle: "Mi piace", likesYou: "Piaci", matches: "Match", myLikes: "I miei Mi piace", visitors: "Visitatori", clinics: "Cliniche", lawyers: "Avvocati", noLikes: "Nessuno ti ha ancora messo Mi piace. Completa il tuo profilo per attirare più attenzione!", noMatches: "Non hai ancora nessun match.", myLikesEmpty: "I profili che ti piacciono appariranno qui.", noViews: "Nessuno ha ancora visualizzato il tuo profilo.", savedClinics: "Non hai ancora salvato nessuna clinica. Sfoglia le cliniche per aggiungerle ai preferiti!", savedLawyers: "Non hai ancora salvato nessun avvocato. Sfoglia gli avvocati per aggiungerli ai preferiti!", peopleLiked: "persone hanno messo Mi piace al tuo profilo", peopleViewed: "persone hanno visualizzato il tuo profilo", likesPremium: "Passa a Premium per scoprire chi ti ha messo Mi piace", viewsPremium: "Passa a Premium per vedere i visitatori del profilo", saved: "Salvato", favouriteRemoveFailed: "Non è stato possibile rimuovere questo elemento dai salvati.", like: "Mi piace", liked: "Piaciuto", sendMessage: "Invia messaggio" },
  pl: { likesTitle: "Polubienia", likesYou: "Polubili Cię", matches: "Dopasowania", myLikes: "Moje polubienia", visitors: "Odwiedzający", clinics: "Kliniki", lawyers: "Prawnicy", noLikes: "Nikt jeszcze Cię nie polubił. Uzupełnij swój profil, aby przyciągnąć więcej uwagi!", noMatches: "Nie masz jeszcze żadnych dopasowań.", myLikesEmpty: "Tutaj pojawią się profile, które polubisz.", noViews: "Nikt jeszcze nie wyświetlił Twojego profilu.", savedClinics: "Nie zapisałeś(-aś) jeszcze żadnej kliniki. Przeglądaj kliniki, aby dodać je do ulubionych!", savedLawyers: "Nie zapisałeś(-aś) jeszcze żadnego prawnika. Przeglądaj prawników, aby dodać ich do ulubionych!", peopleLiked: "osób polubiło Twój profil", peopleViewed: "osób wyświetliło Twój profil", likesPremium: "Przejdź na Premium, aby zobaczyć, kto Cię polubił", viewsPremium: "Przejdź na Premium, aby zobaczyć osoby odwiedzające profil", saved: "Zapisano", favouriteRemoveFailed: "Nie udało się usunąć tego elementu z zapisanych.", like: "Polub", liked: "Polubiono", sendMessage: "Wyślij wiadomość" },
} as const;
