const CHAT_COPY_BASE = {
  "en": {
    "messagesTitle": "Messages",
    "searchConversations": "Search conversations...",
    "noSearchConversations": "No conversations yet",
    "noConversations": "No conversations yet. Use Message on a profile to start one.",
    "selectConversation": "Select a conversation to start messaging",
    "backConversations": "Back to conversations",
    "secureChat": "",
    "loadingMessages": "",
    "noMessages": "No messages yet",
    "noMessagesHelp": "No messages yet. Start the conversation below.",
    "chooseConversation": "Choose a conversation.",
    "chooseFirst": "Choose a conversation first.",
    "writeMessage": "Type a message...",
    "emoji": "Add emoji",
    "attachment": "Attach file",
    "send": "Send",
    "photo": "Photo",
    "today": "Today",
    "you": "You",
    "support": "Support",
    "member": "LetsBeParents member",
    "close": "Close",
    "report": "Report",
    "blockUser": "Block user",
    "attachmentTooLarge": "The attachment must be no larger than 10 MB.",
    "attachmentFailed": "Could not send the attachment.",
    "messageSent": "Sent",
    "messageDelivered": "Delivered",
    "messageRead": "Read",
    "blockConfirmCancel": "Cancel",
    "blockConfirmAction": "Block",
    "blockConfirmLabel": "Block",
    "blockConfirmBody": "This user will not be able to see your profile, send you messages, or find you in search. You can unblock them later.",
    "reportTitle": "Report profile",
    "reportReason": "Reason",
    "reportDetails": "Description",
    "reportPlaceholder": "Provide additional details (optional)",
    "reportChoose": "Select a reason",
    "reportSubmit": "Submit report",
    "reportCancel": "Close",
    "reportSent": "Report sent to moderation.",
    "verifyProfile": "Profile verification",
    "verifyBody": "To keep our community safe, profile photo verification is required. It's free, fast, and no documents are needed — just a quick selfie.",
    "verifyNow": "Start verification",
    "notNow": "Not now",
    "viewProfile": "View profile",
    "deleteChat": "Delete chat",
    "deleteTitle": "Delete chat?",
    "deleteBody": "Chat will reappear if you receive a new message or start the conversation again.",
    "deleteConfirm": "Delete",
    "deleted": "Chat deleted.",
    "voiceCall": "Voice call",
    "videoCall": "Video call",
    "callsUnavailable": "Calls are not available yet.",
    "actions": "Chat actions",
    "call": {
      "incomingVoice": "Incoming voice call",
      "incomingVideo": "Incoming video call",
      "calling": "Calling…",
      "connecting": "Connecting…",
      "connected": "Connected",
      "accept": "Accept",
      "decline": "Decline",
      "end": "End call",
      "microphone": "Microphone",
      "camera": "Camera",
      "requestingMicrophone": "Allow microphone access in the browser request",
      "requestingCamera": "Allow camera access in the browser request",
      "microphoneUnavailable": "Microphone access is denied. Allow it in your browser settings and try again.",
      "cameraUnavailable": "Camera access is denied. Allow it in your browser settings to enable video.",
      "connectionFailed": "Unable to connect the call. Try again.",
      "unavailable": "Calls are temporarily unavailable."
    }
  },
  "ru": {
    "messagesTitle": "Сообщения",
    "searchConversations": "Поиск бесед",
    "noSearchConversations": "Пока нет бесед",
    "noConversations": "Диалогов пока нет. Откройте профиль и нажмите «Написать».",
    "selectConversation": "Выберите диалог, чтобы начать общение",
    "backConversations": "Назад к диалогам",
    "secureChat": "",
    "loadingMessages": "",
    "noMessages": "Сообщений пока нет",
    "noMessagesHelp": "Сообщений пока нет. Начните диалог ниже.",
    "chooseConversation": "Выберите диалог.",
    "chooseFirst": "Сначала выберите диалог.",
    "writeMessage": "Напишите сообщение...",
    "emoji": "Добавить эмодзи",
    "attachment": "Прикрепить файл",
    "send": "Отправить",
    "photo": "Фото",
    "today": "Сегодня",
    "you": "Вы",
    "support": "Поддержка",
    "member": "Участник LetsBeParents",
    "close": "Закрыть",
    "report": "Пожаловаться",
    "blockUser": "Заблокировать",
    "attachmentTooLarge": "Размер вложения не должен превышать 10 МБ.",
    "attachmentFailed": "Не удалось отправить вложение.",
    "messageSent": "Отправлено",
    "messageDelivered": "Доставлено",
    "messageRead": "Прочитано",
    "blockConfirmCancel": "Отмена",
    "blockConfirmAction": "Заблокировать",
    "blockConfirmLabel": "Заблокировать",
    "blockConfirmBody": "Этот пользователь не сможет видеть ваш профиль, писать вам сообщения или находить вас в поиске. Разблокировать можно позже.",
    "reportTitle": "Пожаловаться на профиль",
    "reportReason": "Причина",
    "reportDetails": "Описание",
    "reportPlaceholder": "Укажите дополнительные детали (необязательно)",
    "reportChoose": "Выберите причину",
    "reportSubmit": "Отправить жалобу",
    "reportCancel": "Закрыть",
    "reportSent": "Жалоба отправлена модератору.",
    "verifyProfile": "Верификация профиля",
    "verifyBody": "Чтобы наше сообщество оставалось безопасным, необходимо пройти верификацию фото профиля. Это бесплатно, быстро и без документов — нужно лишь быстрое селфи.",
    "verifyNow": "Пройти верификацию",
    "notNow": "Не сейчас",
    "viewProfile": "Посмотреть профиль",
    "deleteChat": "Удалить чат",
    "deleteTitle": "Удалить этот чат?",
    "deleteBody": "Диалог исчезнет из списка. Если придёт новое сообщение, он появится снова.",
    "deleteConfirm": "Удалить",
    "deleted": "Чат удалён.",
    "voiceCall": "Аудиозвонок",
    "videoCall": "Видеозвонок",
    "callsUnavailable": "Звонки пока недоступны.",
    "actions": "Действия с чатом",
    "call": {
      "incomingVoice": "Входящий аудиозвонок",
      "incomingVideo": "Входящий видеозвонок",
      "calling": "Вызов…",
      "connecting": "Подключение…",
      "connected": "Соединено",
      "accept": "Принять",
      "decline": "Отклонить",
      "end": "Завершить",
      "microphone": "Микрофон",
      "camera": "Камера",
      "requestingMicrophone": "Разрешите доступ к микрофону в запросе браузера",
      "requestingCamera": "Разрешите доступ к камере в запросе браузера",
      "microphoneUnavailable": "Доступ к микрофону запрещён. Разрешите его в настройках браузера и повторите звонок.",
      "cameraUnavailable": "Доступ к камере запрещён. Разрешите его в настройках браузера, чтобы включить видео.",
      "connectionFailed": "Не удалось подключить звонок. Попробуйте ещё раз.",
      "unavailable": "Звонки временно недоступны."
    }
  },
  "es": {
    "messagesTitle": "Mensajes",
    "searchConversations": "Buscar conversaciones...",
    "noSearchConversations": "Aún no hay conversaciones",
    "noConversations": "Aún no hay conversaciones. Usa Mensaje en un perfil para iniciar una.",
    "selectConversation": "Selecciona una conversación para empezar",
    "backConversations": "Volver a conversaciones",
    "secureChat": "",
    "loadingMessages": "",
    "noMessages": "Aún no hay mensajes",
    "noMessagesHelp": "Aún no hay mensajes. Inicia la conversación abajo.",
    "chooseConversation": "Selecciona una conversación.",
    "chooseFirst": "Selecciona primero una conversación.",
    "writeMessage": "Escribe un mensaje...",
    "emoji": "Añadir emoji",
    "attachment": "Adjuntar archivo",
    "send": "Enviar",
    "photo": "Foto",
    "today": "Hoy",
    "you": "Tú",
    "support": "Soporte",
    "member": "Miembro de LetsBeParents",
    "close": "Cerrar",
    "report": "Reportar",
    "blockUser": "Bloquear",
    "attachmentTooLarge": "El archivo no debe superar los 10 MB.",
    "attachmentFailed": "No se pudo enviar el archivo.",
    "messageSent": "Enviado",
    "messageDelivered": "Entregado",
    "messageRead": "Leído",
    "blockConfirmCancel": "Cancelar",
    "blockConfirmAction": "Bloquear",
    "blockConfirmLabel": "Bloquear",
    "blockConfirmBody": "Este usuario ya no podrá ver tu perfil, escribirte ni encontrarte en la búsqueda. Podrás desbloquearlo más tarde.",
    "reportTitle": "Reportar perfil",
    "reportReason": "Motivo",
    "reportDetails": "Descripción",
    "reportPlaceholder": "Añade detalles adicionales (opcional)",
    "reportChoose": "Elige un motivo",
    "reportSubmit": "Enviar reporte",
    "reportCancel": "Cerrar",
    "reportSent": "Reporte enviado a moderación.",
    "verifyProfile": "Verificación del perfil",
    "verifyBody": "Para mantener segura nuestra comunidad, es necesario verificar la foto del perfil. Es gratis, rápido y no requiere documentos: solo un selfie rápido.",
    "verifyNow": "Iniciar verificación",
    "notNow": "Ahora no",
    "viewProfile": "Ver perfil",
    "deleteChat": "Eliminar chat",
    "deleteTitle": "¿Eliminar este chat?",
    "deleteBody": "Esta conversación desaparecerá de tu lista. Volverá a aparecer si llega un mensaje nuevo.",
    "deleteConfirm": "Eliminar",
    "deleted": "Chat eliminado.",
    "voiceCall": "Llamada de voz",
    "videoCall": "Videollamada",
    "callsUnavailable": "Las llamadas aún no están disponibles.",
    "actions": "Acciones del chat",
    "call": {
      "incomingVoice": "Llamada de voz entrante",
      "incomingVideo": "Videollamada entrante",
      "calling": "Llamando…",
      "connecting": "Conectando…",
      "connected": "Conectado",
      "accept": "Aceptar",
      "decline": "Rechazar",
      "end": "Finalizar",
      "microphone": "Micrófono",
      "camera": "Cámara",
      "requestingMicrophone": "Permite el acceso al micrófono en la solicitud del navegador",
      "requestingCamera": "Permite el acceso a la cámara en la solicitud del navegador",
      "microphoneUnavailable": "El acceso al micrófono está denegado. Permítelo en la configuración del navegador e inténtalo de nuevo.",
      "cameraUnavailable": "El acceso a la cámara está denegado. Permítelo en la configuración del navegador para activar el video.",
      "connectionFailed": "No se pudo conectar la llamada. Inténtalo de nuevo.",
      "unavailable": "Las llamadas no están disponibles temporalmente."
    }
  }
} as const;

export const CHAT_COPY = {
  ...CHAT_COPY_BASE,
  pt: {
    "messagesTitle": "Mensagens", "searchConversations": "Pesquisar conversas...", "noSearchConversations": "Ainda não há conversas",
    "noConversations": "Ainda nao ha conversas.",
    "selectConversation": "Selecione uma conversa para começar", "backConversations": "Voltar às conversas",
    "secureChat": "", "loadingMessages": "",
    "noMessages": "Ainda não há mensagens", "noMessagesHelp": "Ainda não há mensagens. Inicie a conversa abaixo.",
    "chooseConversation": "Selecione uma conversa.", "chooseFirst": "Selecione primeiro uma conversa.",
    "writeMessage": "Digite uma mensagem...", "emoji": "Adicionar emoji", "attachment": "Anexar ficheiro", "send": "Enviar", "photo": "Foto",
    "today": "Hoje", "you": "Voce", "support": "Suporte", "member": "Membro da LetsBeParents",
    "close": "Fechar", "report": "Denunciar", "blockUser": "Bloquear",
    "attachmentTooLarge": "O anexo não pode ultrapassar 10 MB.", "attachmentFailed": "Não foi possível enviar o anexo.",
    "messageSent": "Enviada", "messageDelivered": "Entregue", "messageRead": "Lida",
    "blockConfirmCancel": "Cancelar", "blockConfirmAction": "Bloquear", "blockConfirmLabel": "Bloquear",
    "blockConfirmBody": "Este utilizador deixará de poder ver o seu perfil, enviar-lhe mensagens ou encontrá-lo na pesquisa. Pode desbloqueá-lo mais tarde.",
    "reportTitle": "Denunciar perfil", "reportReason": "Motivo", "reportDetails": "Descrição",
    "reportPlaceholder": "Forneça detalhes adicionais (opcional)", "reportChoose": "Selecione um motivo",
    "reportSubmit": "Enviar denúncia", "reportCancel": "Fechar", "reportSent": "Denúncia enviada para moderação.",
    "verifyProfile": "Verificação de perfil",
    "verifyBody": "Para manter a nossa comunidade segura, é necessário verificar a foto de perfil. É gratuito, rápido e não requer documentos — apenas uma selfie rápida.",
    "verifyNow": "Iniciar verificação", "notNow": "Agora não", "viewProfile": "Ver perfil",
    "deleteChat": "Eliminar conversa", "deleteTitle": "Eliminar esta conversa?",
    "deleteBody": "A conversa vai reaparecer se receber uma nova mensagem ou iniciar a conversa novamente.",
    "deleteConfirm": "Eliminar", "deleted": "Conversa eliminada.",
    "voiceCall": "Chamada de voz", "videoCall": "Videochamada", "callsUnavailable": "As chamadas ainda não estão disponíveis.", "actions": "Ações da conversa",
    "call": {
      "incomingVoice": "Chamada de voz a receber", "incomingVideo": "Videochamada a receber", "calling": "A chamar…",
      "connecting": "A ligar…", "connected": "Ligado", "accept": "Aceitar", "decline": "Recusar", "end": "Terminar chamada",
      "microphone": "Microfone", "camera": "Câmara",
      "requestingMicrophone": "Permita o acesso ao microfone no pedido do navegador",
      "requestingCamera": "Permita o acesso à câmara no pedido do navegador",
      "microphoneUnavailable": "O acesso ao microfone foi negado. Permita-o nas definições do navegador e tente novamente.",
      "cameraUnavailable": "O acesso à câmara foi negado. Permita-o nas definições do navegador para ativar o vídeo.",
      "connectionFailed": "Não foi possível ligar a chamada. Tente novamente.", "unavailable": "As chamadas estão temporariamente indisponíveis."
    }
  },
  fr: {
    "messagesTitle": "Messages", "searchConversations": "Rechercher des conversations...", "noSearchConversations": "Aucune conversation pour l'instant",
    "noConversations": "Aucune conversation pour le moment.",
    "selectConversation": "Sélectionnez une conversation pour commencer à discuter", "backConversations": "Retour aux conversations",
    "secureChat": "", "loadingMessages": "",
    "noMessages": "Aucun message pour le moment", "noMessagesHelp": "Aucun message pour le moment. Démarrez la conversation ci-dessous.",
    "chooseConversation": "Choisissez une conversation.", "chooseFirst": "Choisissez d'abord une conversation.",
    "writeMessage": "Ecrire un message...", "emoji": "Ajouter un emoji", "attachment": "Joindre un fichier", "send": "Envoyer", "photo": "Photo",
    "today": "Aujourd'hui", "you": "Vous", "support": "Assistance", "member": "Membre LetsBeParents",
    "close": "Fermer", "report": "Signaler", "blockUser": "Bloquer",
    "attachmentTooLarge": "La pièce jointe ne doit pas dépasser 10 Mo.", "attachmentFailed": "Impossible d'envoyer la pièce jointe.",
    "messageSent": "Envoyé", "messageDelivered": "Distribué", "messageRead": "Lu",
    "blockConfirmCancel": "Annuler", "blockConfirmAction": "Bloquer", "blockConfirmLabel": "Bloquer",
    "blockConfirmBody": "Cet utilisateur ne pourra plus voir votre profil, vous envoyer de messages ni vous trouver dans les recherches. Vous pourrez le débloquer plus tard.",
    "reportTitle": "Signaler le profil", "reportReason": "Motif", "reportDetails": "Description",
    "reportPlaceholder": "Ajoutez des détails supplémentaires (facultatif)", "reportChoose": "Sélectionnez un motif",
    "reportSubmit": "Envoyer le signalement", "reportCancel": "Fermer", "reportSent": "Signalement envoyé à la modération.",
    "verifyProfile": "Vérification du profil",
    "verifyBody": "Pour préserver la sécurité de notre communauté, la vérification de la photo de profil est obligatoire. C'est gratuit, rapide et sans document — juste un selfie rapide.",
    "verifyNow": "Commencer la vérification", "notNow": "Plus tard", "viewProfile": "Voir le profil",
    "deleteChat": "Supprimer la conversation", "deleteTitle": "Supprimer cette conversation ?",
    "deleteBody": "La conversation réapparaîtra si vous recevez un nouveau message ou si vous relancez la discussion.",
    "deleteConfirm": "Supprimer", "deleted": "Conversation supprimée.",
    "voiceCall": "Appel vocal", "videoCall": "Appel vidéo", "callsUnavailable": "Les appels ne sont pas encore disponibles.", "actions": "Actions de la conversation",
    "call": {
      "incomingVoice": "Appel vocal entrant", "incomingVideo": "Appel vidéo entrant", "calling": "Appel en cours…",
      "connecting": "Connexion…", "connected": "Connecté", "accept": "Accepter", "decline": "Refuser", "end": "Raccrocher",
      "microphone": "Microphone", "camera": "Caméra",
      "requestingMicrophone": "Autorisez l'accès au microphone dans la demande du navigateur",
      "requestingCamera": "Autorisez l'accès à la caméra dans la demande du navigateur",
      "microphoneUnavailable": "L'accès au microphone est refusé. Autorisez-le dans les paramètres de votre navigateur et réessayez.",
      "cameraUnavailable": "L'accès à la caméra est refusé. Autorisez-le dans les paramètres de votre navigateur pour activer la vidéo.",
      "connectionFailed": "Impossible de connecter l'appel. Réessayez.", "unavailable": "Les appels sont temporairement indisponibles."
    }
  },
  de: {
    "messagesTitle": "Nachrichten", "searchConversations": "Unterhaltungen suchen...", "noSearchConversations": "Noch keine Unterhaltungen",
    "noConversations": "Noch keine Unterhaltungen.",
    "selectConversation": "Wähle eine Unterhaltung aus, um zu chatten", "backConversations": "Zurück zu den Unterhaltungen",
    "secureChat": "", "loadingMessages": "",
    "noMessages": "Noch keine Nachrichten", "noMessagesHelp": "Noch keine Nachrichten. Starte die Unterhaltung unten.",
    "chooseConversation": "Wähle eine Unterhaltung aus.", "chooseFirst": "Wähle zuerst eine Unterhaltung aus.",
    "writeMessage": "Nachricht eingeben...", "emoji": "Emoji hinzufügen", "attachment": "Datei anhängen", "send": "Senden", "photo": "Foto",
    "today": "Heute", "you": "Du", "support": "Support", "member": "LetsBeParents-Mitglied",
    "close": "Schliessen", "report": "Melden", "blockUser": "Blockieren",
    "attachmentTooLarge": "Der Anhang darf nicht größer als 10 MB sein.", "attachmentFailed": "Der Anhang konnte nicht gesendet werden.",
    "messageSent": "Gesendet", "messageDelivered": "Zugestellt", "messageRead": "Gelesen",
    "blockConfirmCancel": "Abbrechen", "blockConfirmAction": "Blockieren", "blockConfirmLabel": "Blockieren",
    "blockConfirmBody": "Dieser Nutzer kann dein Profil nicht mehr sehen, dir keine Nachrichten mehr senden und dich nicht mehr in der Suche finden. Du kannst ihn später wieder entsperren.",
    "reportTitle": "Profil melden", "reportReason": "Grund", "reportDetails": "Beschreibung",
    "reportPlaceholder": "Zusätzliche Details angeben (optional)", "reportChoose": "Grund auswählen",
    "reportSubmit": "Meldung senden", "reportCancel": "Schließen", "reportSent": "Meldung an die Moderation gesendet.",
    "verifyProfile": "Profilverifizierung",
    "verifyBody": "Um unsere Community sicher zu halten, ist eine Verifizierung des Profilfotos erforderlich. Sie ist kostenlos, schnell und ohne Dokumente – nur ein kurzes Selfie.",
    "verifyNow": "Verifizierung starten", "notNow": "Nicht jetzt", "viewProfile": "Profil ansehen",
    "deleteChat": "Chat löschen", "deleteTitle": "Chat löschen?",
    "deleteBody": "Der Chat erscheint wieder, wenn du eine neue Nachricht erhältst oder die Unterhaltung erneut beginnst.",
    "deleteConfirm": "Löschen", "deleted": "Chat gelöscht.",
    "voiceCall": "Sprachanruf", "videoCall": "Videoanruf", "callsUnavailable": "Anrufe sind noch nicht verfügbar.", "actions": "Chat-Aktionen",
    "call": {
      "incomingVoice": "Eingehender Sprachanruf", "incomingVideo": "Eingehender Videoanruf", "calling": "Anruf läuft…",
      "connecting": "Verbindung wird hergestellt…", "connected": "Verbunden", "accept": "Annehmen", "decline": "Ablehnen", "end": "Anruf beenden",
      "microphone": "Mikrofon", "camera": "Kamera",
      "requestingMicrophone": "Erlaube den Mikrofonzugriff in der Browseranfrage",
      "requestingCamera": "Erlaube den Kamerazugriff in der Browseranfrage",
      "microphoneUnavailable": "Der Zugriff auf das Mikrofon wurde verweigert. Erlaube ihn in deinen Browsereinstellungen und versuche es erneut.",
      "cameraUnavailable": "Der Zugriff auf die Kamera wurde verweigert. Erlaube ihn in deinen Browsereinstellungen, um Video zu aktivieren.",
      "connectionFailed": "Der Anruf konnte nicht verbunden werden. Versuche es erneut.", "unavailable": "Anrufe sind vorübergehend nicht verfügbar."
    }
  },
  it: {
    "messagesTitle": "Messaggi", "searchConversations": "Cerca conversazioni...", "noSearchConversations": "Ancora nessuna conversazione",
    "noConversations": "Ancora nessuna conversazione.",
    "selectConversation": "Seleziona una conversazione per iniziare a scrivere", "backConversations": "Torna alle conversazioni",
    "secureChat": "", "loadingMessages": "",
    "noMessages": "Ancora nessun messaggio", "noMessagesHelp": "Ancora nessun messaggio. Inizia la conversazione qui sotto.",
    "chooseConversation": "Seleziona una conversazione.", "chooseFirst": "Seleziona prima una conversazione.",
    "writeMessage": "Scrivi un messaggio...", "emoji": "Aggiungi emoji", "attachment": "Allega file", "send": "Invia", "photo": "Foto",
    "today": "Oggi", "you": "Tu", "support": "Assistenza", "member": "Membro di LetsBeParents",
    "close": "Chiudi", "report": "Segnala", "blockUser": "Blocca",
    "attachmentTooLarge": "L'allegato non deve superare i 10 MB.", "attachmentFailed": "Impossibile inviare l'allegato.",
    "messageSent": "Inviato", "messageDelivered": "Consegnato", "messageRead": "Letto",
    "blockConfirmCancel": "Annulla", "blockConfirmAction": "Blocca", "blockConfirmLabel": "Blocca",
    "blockConfirmBody": "Questo utente non potrà più vedere il tuo profilo, scriverti messaggi o trovarti nelle ricerche. Potrai sbloccarlo in seguito.",
    "reportTitle": "Segnala profilo", "reportReason": "Motivo", "reportDetails": "Descrizione",
    "reportPlaceholder": "Aggiungi dettagli (facoltativo)", "reportChoose": "Seleziona un motivo",
    "reportSubmit": "Invia segnalazione", "reportCancel": "Chiudi", "reportSent": "Segnalazione inviata alla moderazione.",
    "verifyProfile": "Verifica del profilo",
    "verifyBody": "Per mantenere sicura la nostra community, è richiesta la verifica della foto del profilo. È gratuita, veloce e non richiede documenti: basta un selfie veloce.",
    "verifyNow": "Avvia la verifica", "notNow": "Non ora", "viewProfile": "Visualizza profilo",
    "deleteChat": "Elimina chat", "deleteTitle": "Eliminare questa chat?",
    "deleteBody": "La chat riapparirà se ricevi un nuovo messaggio o riprendi la conversazione.",
    "deleteConfirm": "Elimina", "deleted": "Chat eliminata.",
    "voiceCall": "Chiamata vocale", "videoCall": "Videochiamata", "callsUnavailable": "Le chiamate non sono ancora disponibili.", "actions": "Azioni chat",
    "call": {
      "incomingVoice": "Chiamata vocale in arrivo", "incomingVideo": "Videochiamata in arrivo", "calling": "Chiamata in corso…",
      "connecting": "Connessione in corso…", "connected": "Connesso", "accept": "Accetta", "decline": "Rifiuta", "end": "Termina chiamata",
      "microphone": "Microfono", "camera": "Fotocamera",
      "requestingMicrophone": "Consenti l'accesso al microfono nella richiesta del browser",
      "requestingCamera": "Consenti l'accesso alla fotocamera nella richiesta del browser",
      "microphoneUnavailable": "L'accesso al microfono è negato. Consentilo nelle impostazioni del browser e riprova.",
      "cameraUnavailable": "L'accesso alla fotocamera è negato. Consentilo nelle impostazioni del browser per attivare il video.",
      "connectionFailed": "Impossibile connettere la chiamata. Riprova.", "unavailable": "Le chiamate non sono temporaneamente disponibili."
    }
  },
  pl: {
    "messagesTitle": "Wiadomosci", "searchConversations": "Szukaj rozmow...", "noSearchConversations": "Brak rozmów",
    "noConversations": "Brak rozmow.",
    "selectConversation": "Wybierz rozmowę, aby zacząć pisać", "backConversations": "Wróć do rozmów",
    "secureChat": "", "loadingMessages": "",
    "noMessages": "Brak wiadomości", "noMessagesHelp": "Brak wiadomości. Rozpocznij rozmowę poniżej.",
    "chooseConversation": "Wybierz rozmowę.", "chooseFirst": "Najpierw wybierz rozmowę.",
    "writeMessage": "Napisz wiadomosc...", "emoji": "Dodaj emoji", "attachment": "Dołącz plik", "send": "Wyslij", "photo": "Zdjęcie",
    "today": "Dzisiaj", "you": "Ty", "support": "Wsparcie", "member": "Członek LetsBeParents",
    "close": "Zamknij", "report": "Zglos", "blockUser": "Zablokuj",
    "attachmentTooLarge": "Załącznik nie może przekraczać 10 MB.", "attachmentFailed": "Nie udało się wysłać załącznika.",
    "messageSent": "Wysłano", "messageDelivered": "Dostarczono", "messageRead": "Przeczytano",
    "blockConfirmCancel": "Anuluj", "blockConfirmAction": "Zablokuj", "blockConfirmLabel": "Zablokuj",
    "blockConfirmBody": "Ten użytkownik nie będzie mógł widzieć Twojego profilu, wysyłać Ci wiadomości ani znaleźć Cię w wyszukiwarce. Możesz go później odblokować.",
    "reportTitle": "Zgłoś profil", "reportReason": "Powód", "reportDetails": "Opis",
    "reportPlaceholder": "Podaj dodatkowe informacje (opcjonalnie)", "reportChoose": "Wybierz powód",
    "reportSubmit": "Wyślij zgłoszenie", "reportCancel": "Zamknij", "reportSent": "Zgłoszenie zostało wysłane do moderacji.",
    "verifyProfile": "Weryfikacja profilu",
    "verifyBody": "Aby zapewnić bezpieczeństwo naszej społeczności, wymagana jest weryfikacja zdjęcia profilowego. Jest darmowa, szybka i nie wymaga dokumentów — wystarczy krótkie selfie.",
    "verifyNow": "Rozpocznij weryfikację", "notNow": "Nie teraz", "viewProfile": "Zobacz profil",
    "deleteChat": "Usuń rozmowę", "deleteTitle": "Usunąć tę rozmowę?",
    "deleteBody": "Rozmowa pojawi się ponownie, jeśli otrzymasz nową wiadomość lub zaczniesz ją od nowa.",
    "deleteConfirm": "Usuń", "deleted": "Rozmowa usunięta.",
    "voiceCall": "Połączenie głosowe", "videoCall": "Połączenie wideo", "callsUnavailable": "Połączenia nie są jeszcze dostępne.", "actions": "Akcje rozmowy",
    "call": {
      "incomingVoice": "Przychodzące połączenie głosowe", "incomingVideo": "Przychodzące połączenie wideo", "calling": "Dzwonienie…",
      "connecting": "Łączenie…", "connected": "Połączono", "accept": "Odbierz", "decline": "Odrzuć", "end": "Zakończ połączenie",
      "microphone": "Mikrofon", "camera": "Kamera",
      "requestingMicrophone": "Zezwól na dostęp do mikrofonu w oknie przeglądarki",
      "requestingCamera": "Zezwól na dostęp do kamery w oknie przeglądarki",
      "microphoneUnavailable": "Dostęp do mikrofonu jest zablokowany. Zezwól na niego w ustawieniach przeglądarki i spróbuj ponownie.",
      "cameraUnavailable": "Dostęp do kamery jest zablokowany. Zezwól na niego w ustawieniach przeglądarki, aby włączyć wideo.",
      "connectionFailed": "Nie udało się połączyć rozmowy. Spróbuj ponownie.", "unavailable": "Połączenia są tymczasowo niedostępne."
    }
  },
} as const;
export const CHAT_ICONS: Record<string,string> = {
  "supportIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 14v-2a8 8 0 0 1 16 0v2\"></path><path d=\"M18 19h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3v4a3 3 0 0 1-3 3Z\"></path><path d=\"M6 19h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H4v4a3 3 0 0 0 3 3Z\"></path></svg>",
  "messageIcon": "<svg class=\"action-icon message-action-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7A8.38 8.38 0 0 1 4 11.5a8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5Z\"></path></svg>",
  "pageBackIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"m12 19-7-7 7-7\"></path><path d=\"M19 12H5\"></path></svg>",
  "phoneIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.79 19.79 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.69 2.8a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.9.33 1.84.56 2.8.69A2 2 0 0 1 22 16.92Z\"></path></svg>",
  "videoIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"m22 8-6 4 6 4V8Z\"></path><rect x=\"2\" y=\"6\" width=\"14\" height=\"12\" rx=\"2\"></rect></svg>",
  "moreVerticalIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"12\" cy=\"5\" r=\"1\"></circle><circle cx=\"12\" cy=\"12\" r=\"1\"></circle><circle cx=\"12\" cy=\"19\" r=\"1\"></circle></svg>",
  "userProfileIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"12\" cy=\"8\" r=\"4\"></circle><path d=\"M4 22a8 8 0 0 1 16 0\"></path></svg>",
  "trashIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M3 6h18\"></path><path d=\"M8 6V4h8v2\"></path><path d=\"m19 6-1 14H6L5 6\"></path><path d=\"M10 11v5\"></path><path d=\"M14 11v5\"></path></svg>",
  "flagIcon": "<svg class=\"action-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 22V4\"></path><path d=\"M5 4h11l-1 4 1 4H5\"></path></svg>",
  "banIcon": "<svg class=\"action-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"12\" cy=\"12\" r=\"9\"></circle><path d=\"m5.6 5.6 12.8 12.8\"></path></svg>",
  "smileIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><path d=\"M8 14s1.5 2 4 2 4-2 4-2\"></path><path d=\"M9 9h.01\"></path><path d=\"M15 9h.01\"></path></svg>",
  "paperclipIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l9.19-9.19a4 4 0 0 1 5.66 5.66l-9.2 9.19a2 2 0 0 1-2.83-2.83l8.49-8.48\"></path></svg>",
  "sendIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"m22 2-7 20-4-9-9-4Z\"></path><path d=\"M22 2 11 13\"></path></svg>",
  "microphoneIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><rect x=\"9\" y=\"2\" width=\"6\" height=\"12\" rx=\"3\"></rect><path d=\"M5 10a7 7 0 0 0 14 0M12 17v5M8 22h8\"></path></svg>",
  "closeIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M18 6 6 18\"></path><path d=\"m6 6 12 12\"></path></svg>"
};
