// Text, option labels and SVG markup preserved from the existing HTML member profile.
export const PROFILE_COPY = {
  en: {
    close: "Close",
    member: "LetsBeParents member",
    notSpecified: "Not specified",
    profileNotFound: "Profile not found",
    descriptionFallback: "This member has not added a profile description yet.",
    goBack: "Go back",
    moreOptions: "More options",
    profileActions: "Profile actions",
    blockUser: "Block user",
    report: "Report",
    sendMessage: "Send message",
    like: "Like",
    liked: "Liked",
    aboutMe: "About me",
    languages: "Languages",
    appearance: "Appearance",
    height: "Height",
    weight: "Weight",
    smoking: "Smoking",
    alcohol: "Alcohol",
    eyeColor: "Eye color",
    hairColor: "Hair color",
    ethnicity: "Ethnicity",
    religion: "Religion",
    locationHidden: "Location hidden",
    profilePhotos: "Profile photos",
    previousPhoto: "Previous photo",
    nextPhoto: "Next photo",
    showPhoto: "Show photo",
    lookingFor: "Looking for",
    verified: "Verified",
    verifyProfile: "Profile verification",
    verifyBody:
      "To keep our community safe, profile photo verification is required. It's free, fast, and no documents are needed — just a quick selfie.",
    verifyNow: "Start verification",
    notNow: "Not now",
    signInRequired: "Sign in required",
    signInBody: "Profiles are available after registration or sign in.",
    signIn: "Sign in",
    blockConfirm: "Block this user?",
    blockConfirmLabel: "Block",
    blockConfirmBody:
      "This user will not be able to see your profile, send you messages, or find you in search. You can unblock them later.",
    blockConfirmCancel: "Cancel",
    blockConfirmAction: "Block",
    reportTitle: "Report profile",
    reportReason: "Reason",
    reportDetails: "Description",
    reportPlaceholder: "Provide additional details (optional)",
    reportChoose: "Select a reason",
    reportSubmit: "Submit report",
    reportCancel: "Close",
    reportSent: "Report sent to moderation.",
    occupation: "Occupation",
    education: "Education",
    childContact: "Contact with the child",
    fullAnonymity: "Full anonymity",
    limitedContact: "Limited contact",
    openContact: "Ongoing relationship",
    identity: "Identity disclosed at 18",
  },
  ru: {
    close: "Закрыть",
    member: "Участник LetsBeParents",
    notSpecified: "Не указано",
    profileNotFound: "Профиль не найден",
    descriptionFallback: "Пользователь пока не добавил описание профиля.",
    goBack: "Назад",
    moreOptions: "Другие действия",
    profileActions: "Действия с профилем",
    blockUser: "Заблокировать",
    report: "Пожаловаться",
    sendMessage: "Отправить сообщение",
    like: "Нравится",
    liked: "Liked",
    aboutMe: "Обо мне",
    languages: "Языки",
    appearance: "Внешность",
    height: "Рост",
    weight: "Вес",
    smoking: "Курение",
    alcohol: "Алкоголь",
    eyeColor: "Цвет глаз",
    hairColor: "Цвет волос",
    ethnicity: "Этническая принадлежность",
    religion: "Религия",
    locationHidden: "Местоположение скрыто",
    profilePhotos: "Фотографии профиля",
    previousPhoto: "Предыдущее фото",
    nextPhoto: "Следующее фото",
    showPhoto: "Показать фото",
    lookingFor: "Ищет",
    verified: "Подтверждённый профиль",
    verifyProfile: "Верификация профиля",
    verifyBody:
      "Чтобы наше сообщество оставалось безопасным, необходимо пройти верификацию фото профиля. Это бесплатно, быстро и без документов — нужно лишь быстрое селфи.",
    verifyNow: "Пройти верификацию",
    notNow: "Не сейчас",
    signInRequired: "Требуется вход",
    signInBody: "Анкеты доступны после регистрации или входа.",
    signIn: "Войти",
    blockConfirm: "Заблокировать пользователя?",
    blockConfirmLabel: "Заблокировать",
    blockConfirmBody:
      "Этот пользователь не сможет видеть ваш профиль, писать вам сообщения или находить вас в поиске. Разблокировать можно позже.",
    blockConfirmCancel: "Отмена",
    blockConfirmAction: "Заблокировать",
    reportTitle: "Пожаловаться на профиль",
    reportReason: "Причина",
    reportDetails: "Описание",
    reportPlaceholder: "Укажите дополнительные детали (необязательно)",
    reportChoose: "Выберите причину",
    reportSubmit: "Отправить жалобу",
    reportCancel: "Закрыть",
    reportSent: "Жалоба отправлена модератору.",
    occupation: "Профессия",
    education: "Образование",
    childContact: "Мой контакт с ребёнком",
    fullAnonymity: "Полная анонимность",
    limitedContact: "Контакт по договорённости",
    openContact: "Открытый контакт",
    identity: "Раскрытие личности в 18 лет",
  },
  es: {
    close: "Cerrar",
    member: "Miembro de LetsBeParents",
    notSpecified: "No especificado",
    profileNotFound: "Perfil no encontrado",
    descriptionFallback: "Este miembro aún no ha añadido una descripción.",
    goBack: "Volver",
    moreOptions: "Más opciones",
    profileActions: "Acciones del perfil",
    blockUser: "Bloquear",
    report: "Reportar",
    sendMessage: "Enviar mensaje",
    like: "Me gusta",
    liked: "Liked",
    aboutMe: "Sobre mí",
    languages: "Idiomas",
    appearance: "Apariencia",
    height: "Altura",
    weight: "Peso",
    smoking: "Tabaco",
    alcohol: "Alcohol",
    eyeColor: "Color de ojos",
    hairColor: "Color de pelo",
    ethnicity: "Origen étnico",
    religion: "Religión",
    locationHidden: "Ubicación oculta",
    profilePhotos: "Fotos del perfil",
    previousPhoto: "Foto anterior",
    nextPhoto: "Foto siguiente",
    showPhoto: "Mostrar foto",
    lookingFor: "Busca",
    verified: "Perfil verificado",
    verifyProfile: "Verificación del perfil",
    verifyBody:
      "Para mantener segura nuestra comunidad, es necesario verificar la foto del perfil. Es gratis, rápido y no requiere documentos: solo un selfie rápido.",
    verifyNow: "Iniciar verificación",
    notNow: "Ahora no",
    signInRequired: "Inicia sesión",
    signInBody:
      "Los perfiles están disponibles después de registrarte o iniciar sesión.",
    signIn: "Iniciar sesión",
    blockConfirm: "¿Bloquear a este usuario?",
    blockConfirmLabel: "Bloquear",
    blockConfirmBody:
      "Este usuario ya no podrá ver tu perfil, escribirte ni encontrarte en la búsqueda. Podrás desbloquearlo más tarde.",
    blockConfirmCancel: "Cancelar",
    blockConfirmAction: "Bloquear",
    reportTitle: "Reportar perfil",
    reportReason: "Motivo",
    reportDetails: "Descripción",
    reportPlaceholder: "Añade detalles adicionales (opcional)",
    reportChoose: "Elige un motivo",
    reportSubmit: "Enviar reporte",
    reportCancel: "Cerrar",
    reportSent: "Reporte enviado a moderación.",
    occupation: "Ocupación",
    education: "Educación",
    childContact: "Contacto con el niño",
    fullAnonymity: "Anonimato completo",
    limitedContact: "Contacto por acuerdo",
    openContact: "Contacto abierto",
    identity: "Revelación de identidad a los 18 años",
  },
};
export const PROFILE_OPTIONS: Record<string, string[][]> = {
  profileTypes: [
    ["SINGLE_WOMAN", "Single Woman"],
    ["SINGLE_MAN", "Single Man"],
    ["HETERO_COUPLE", "Heterosexual Couple"],
    ["LESBIAN_COUPLE", "Lesbian Couple"],
    ["GAY_COUPLE", "Gay Couple"],
  ],
  donorTypes: [
    ["SPERM", "Sperm Donor", "🧬"],
    ["EGG", "Egg Donor", "🥚"],
  ],
  lookingFor: [
    ["SPERM_DONOR", "Sperm donor"],
    ["EGG_DONOR", "Egg donor"],
    ["CO_PARENTING_PARTNER", "Co-parenting partner"],
  ],
  ethnicity: [
    ["CAUCASIAN_WHITE", "Caucasian / White"],
    ["AFRICAN_AMERICAN_BLACK", "African American / Black"],
    ["HISPANIC_LATINO", "Hispanic / Latino"],
    ["ASIAN_EAST", "East Asian"],
    ["ASIAN_SOUTH", "South Asian"],
    ["ASIAN_SOUTHEAST", "Southeast Asian"],
    ["MIDDLE_EASTERN_ARAB", "Middle Eastern / Arab"],
    ["ASHKENAZI_JEWISH", "Ashkenazi Jewish"],
    ["SEPHARDIC_MIZRAHI_JEWISH", "Sephardic / Mizrahi Jewish"],
    ["NATIVE_AMERICAN", "Native American"],
    ["PACIFIC_ISLANDER", "Pacific Islander"],
    ["MIXED_MULTIRACIAL", "Mixed / Multiracial"],
  ],
  hairColor: [
    ["BLONDE", "Blonde"],
    ["LIGHT_BLONDE", "Light blonde"],
    ["DARK_BLONDE", "Dark blonde"],
    ["STRAWBERRY_BLONDE", "Strawberry blonde"],
    ["AUBURN", "Auburn"],
    ["RED", "Red"],
    ["LIGHT_BROWN", "Light brown"],
    ["MEDIUM_BROWN", "Medium brown"],
    ["DARK_BROWN", "Dark brown"],
    ["BLACK", "Black"],
    ["GREY", "Grey"],
    ["WHITE", "White"],
    ["BALD_SHAVED", "Bald / shaved"],
  ],
  eyeColor: [
    ["GREY", "Grey"],
    ["LIGHT_BLUE", "Light blue"],
    ["BLUE", "Blue"],
    ["GREEN", "Green"],
    ["YELLOW", "Yellow"],
    ["BROWN_HAZEL", "Brown / hazel"],
    ["BLACK", "Black"],
  ],
  education: [
    ["HIGH_SCHOOL", "High school"],
    ["SOME_COLLEGE", "Some college"],
    ["VOCATIONAL", "Vocational"],
    ["ASSOCIATE", "Associate degree"],
    ["BACHELORS", "Bachelor's degree"],
    ["MASTERS", "Master's degree"],
    ["PHD", "PhD"],
    ["PROFESSIONAL", "Professional degree"],
    ["POSTDOCTORAL", "Postdoctoral"],
    ["STUDENT", "Student"],
    ["PREFER_NOT_TO_SAY", "Prefer not to say"],
    ["OTHER", "Other"],
  ],
  religion: [
    ["CHRISTIAN_ORTHODOX", "Christian Orthodox"],
    ["CHRISTIAN_CATHOLIC", "Christian Catholic"],
    ["CHRISTIAN_PROTESTANT", "Christian Protestant"],
    ["CHRISTIAN_OTHER", "Christian (other)"],
    ["MUSLIM_SUNNI", "Muslim Sunni"],
    ["MUSLIM_SHIA", "Muslim Shia"],
    ["JEWISH_ORTHODOX", "Jewish Orthodox"],
    ["JEWISH_CONSERVATIVE", "Jewish Conservative"],
    ["JEWISH_REFORM", "Jewish Reform"],
    ["JEWISH_SECULAR", "Jewish Secular"],
    ["HINDU", "Hindu"],
    ["BUDDHIST", "Buddhist"],
    ["SIKH", "Sikh"],
    ["SHINTO", "Shinto"],
    ["SPIRITUAL", "Spiritual"],
    ["NOT_RELIGIOUS", "Not religious"],
  ],
  smokingStatus: [
    ["NON_SMOKER", "Non-smoker"],
    ["OCCASIONAL", "Occasional smoker"],
    ["REGULAR", "Regular smoker"],
    ["TRYING_TO_QUIT", "Trying to quit"],
    ["PREFER_NOT_TO_SAY", "Prefer not to say"],
  ],
  drinkingStatus: [
    ["NEVER", "Never"],
    ["SOCIAL", "Socially"],
    ["OCCASIONALLY", "Occasionally"],
    ["REGULARLY", "Regularly"],
    ["PREFER_NOT_TO_SAY", "Prefer not to say"],
  ],
};
export const PROFILE_TRANSLATIONS: Record<string, Record<string, string>> = {
  ru: {
    SINGLE_WOMAN: "Одинокая женщина",
    SINGLE_MAN: "Одинокий мужчина",
    HETERO_COUPLE: "Гетеросексуальная пара",
    LESBIAN_COUPLE: "Лесбийская пара",
    GAY_COUPLE: "Гей-пара",
    SPERM: "Донор спермы",
    EGG: "Донор яйцеклеток",
    SPERM_DONOR: "Донор спермы",
    EGG_DONOR: "Донор яйцеклеток",
    CO_PARENTING_PARTNER: "Партнёр для совместного родительства",
    CAUCASIAN_WHITE: "Европеоидная / белая",
    AFRICAN_AMERICAN_BLACK: "Африканская / темнокожая",
    HISPANIC_LATINO: "Латиноамериканская",
    ASIAN_EAST: "Восточноазиатская",
    ASIAN_SOUTH: "Южноазиатская",
    ASIAN_SOUTHEAST: "Юго-Восточная Азия",
    MIDDLE_EASTERN_ARAB: "Ближневосточная / арабская",
    ASHKENAZI_JEWISH: "Ашкеназская еврейская",
    SEPHARDIC_MIZRAHI_JEWISH: "Сефардская / мизрахская еврейская",
    NATIVE_AMERICAN: "Коренные народы Америки",
    PACIFIC_ISLANDER: "Народы Тихоокеанских островов",
    MIXED_MULTIRACIAL: "Смешанная",
    GREY: "Серый",
    LIGHT_BLUE: "Светло-голубой",
    BLUE: "Голубой",
    GREEN: "Зелёный",
    YELLOW: "Жёлтый",
    BROWN_HAZEL: "Карий / ореховый",
    BLACK: "Чёрный",
    BLONDE: "Блонд",
    LIGHT_BLONDE: "Светлый блонд",
    DARK_BLONDE: "Тёмный блонд",
    STRAWBERRY_BLONDE: "Клубничный блонд",
    AUBURN: "Каштаново-рыжий",
    RED: "Рыжий",
    LIGHT_BROWN: "Светло-коричневый",
    MEDIUM_BROWN: "Средне-коричневый",
    DARK_BROWN: "Тёмно-коричневый",
    WHITE: "Белый",
    BALD_SHAVED: "Бритая голова",
    HIGH_SCHOOL: "Средняя школа",
    SOME_COLLEGE: "Незаконченное высшее",
    VOCATIONAL: "Профессиональное",
    ASSOCIATE: "Среднее специальное",
    BACHELORS: "Бакалавриат",
    MASTERS: "Магистратура",
    PHD: "Докторантура",
    PROFESSIONAL: "Профессиональная степень",
    POSTDOCTORAL: "Постдокторантура",
    STUDENT: "Студент",
    PREFER_NOT_TO_SAY: "Предпочитаю не указывать",
    OTHER: "Другое",
    CHRISTIAN_ORTHODOX: "Православие",
    CHRISTIAN_CATHOLIC: "Католицизм",
    CHRISTIAN_PROTESTANT: "Протестантизм",
    CHRISTIAN_OTHER: "Другое христианство",
    MUSLIM_SUNNI: "Ислам, суннизм",
    MUSLIM_SHIA: "Ислам, шиизм",
    JEWISH_ORTHODOX: "Ортодоксальный иудаизм",
    JEWISH_CONSERVATIVE: "Консервативный иудаизм",
    JEWISH_REFORM: "Реформистский иудаизм",
    JEWISH_SECULAR: "Светский иудаизм",
    HINDU: "Индуизм",
    BUDDHIST: "Буддизм",
    SIKH: "Сикхизм",
    SHINTO: "Синтоизм",
    SPIRITUAL: "Духовные практики",
    NOT_RELIGIOUS: "Не религиозен",
    NON_SMOKER: "Не курю",
    OCCASIONAL: "Иногда",
    REGULAR: "Регулярно",
    TRYING_TO_QUIT: "Бросаю",
    NEVER: "Никогда",
    SOCIAL: "В компании",
    OCCASIONALLY: "Иногда",
    REGULARLY: "Регулярно",
  },
  es: {
    SINGLE_WOMAN: "Mujer soltera",
    SINGLE_MAN: "Hombre soltero",
    HETERO_COUPLE: "Pareja heterosexual",
    LESBIAN_COUPLE: "Pareja de mujeres",
    GAY_COUPLE: "Pareja de hombres",
    SPERM: "Donante de esperma",
    EGG: "Donante de óvulos",
    SPERM_DONOR: "Donante de esperma",
    EGG_DONOR: "Donante de óvulos",
    CO_PARENTING_PARTNER: "Pareja de coparentalidad",
    CAUCASIAN_WHITE: "Caucásico / blanco",
    AFRICAN_AMERICAN_BLACK: "Afroamericano / negro",
    HISPANIC_LATINO: "Hispano / latino",
    ASIAN_EAST: "Asia oriental",
    ASIAN_SOUTH: "Asia meridional",
    ASIAN_SOUTHEAST: "Sudeste asiático",
    MIDDLE_EASTERN_ARAB: "Oriente Medio / árabe",
    ASHKENAZI_JEWISH: "Judío asquenazí",
    SEPHARDIC_MIZRAHI_JEWISH: "Judío sefardí / mizrají",
    NATIVE_AMERICAN: "Nativo americano",
    PACIFIC_ISLANDER: "Islas del Pacífico",
    MIXED_MULTIRACIAL: "Mixto / multirracial",
    GREY: "Gris",
    LIGHT_BLUE: "Azul claro",
    BLUE: "Azul",
    GREEN: "Verde",
    YELLOW: "Amarillo",
    BROWN_HAZEL: "Marrón / avellana",
    BLACK: "Negro",
    BLONDE: "Rubio",
    LIGHT_BLONDE: "Rubio claro",
    DARK_BLONDE: "Rubio oscuro",
    STRAWBERRY_BLONDE: "Rubio fresa",
    AUBURN: "Castaño rojizo",
    RED: "Pelirrojo",
    LIGHT_BROWN: "Castaño claro",
    MEDIUM_BROWN: "Castaño medio",
    DARK_BROWN: "Castaño oscuro",
    WHITE: "Blanco",
    BALD_SHAVED: "Calvo / rapado",
    HIGH_SCHOOL: "Secundaria",
    SOME_COLLEGE: "Estudios universitarios parciales",
    VOCATIONAL: "Formación profesional",
    ASSOCIATE: "Título técnico",
    BACHELORS: "Licenciatura",
    MASTERS: "Máster",
    PHD: "Doctorado",
    PROFESSIONAL: "Título profesional",
    POSTDOCTORAL: "Posdoctorado",
    STUDENT: "Estudiante",
    PREFER_NOT_TO_SAY: "Prefiero no decirlo",
    OTHER: "Otro",
    CHRISTIAN_ORTHODOX: "Cristianismo ortodoxo",
    CHRISTIAN_CATHOLIC: "Catolicismo",
    CHRISTIAN_PROTESTANT: "Protestantismo",
    CHRISTIAN_OTHER: "Otro cristianismo",
    MUSLIM_SUNNI: "Islam suní",
    MUSLIM_SHIA: "Islam chií",
    JEWISH_ORTHODOX: "Judaísmo ortodoxo",
    JEWISH_CONSERVATIVE: "Judaísmo conservador",
    JEWISH_REFORM: "Judaísmo reformista",
    JEWISH_SECULAR: "Judaísmo secular",
    HINDU: "Hinduismo",
    BUDDHIST: "Budismo",
    SIKH: "Sijismo",
    SHINTO: "Sintoísmo",
    SPIRITUAL: "Espiritual",
    NOT_RELIGIOUS: "No religioso",
    NON_SMOKER: "No fumador",
    OCCASIONAL: "Ocasional",
    REGULAR: "Regular",
    TRYING_TO_QUIT: "Intentando dejarlo",
    NEVER: "Nunca",
    SOCIAL: "Socialmente",
    OCCASIONALLY: "Ocasionalmente",
    REGULARLY: "Regularmente",
  },
};
export const PROFILE_ICONS = {
  pageBackIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 19-7-7 7-7"></path><path d="M19 12H5"></path></svg>',
  moreVerticalIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="5" r="1"></circle><circle cx="12" cy="12" r="1"></circle><circle cx="12" cy="19" r="1"></circle></svg>',
  banIcon:
    '<svg class="action-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"></circle><path d="m5.6 5.6 12.8 12.8"></path></svg>',
  flagIcon:
    '<svg class="action-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 22V4"></path><path d="M5 4h11l-1 4 1 4H5"></path></svg>',
  messageIcon:
    '<svg class="action-icon message-action-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7A8.38 8.38 0 0 1 4 11.5a8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5Z"></path></svg>',
  thumbsUpIcon:
    '<svg class="action-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z"></path><path d="M7 10v12"></path></svg>',
  arrowLeftIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 18-6-6 6-6"></path></svg>',
  arrowRightIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg>',
  closeIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 6 6 18"></path><path d="m6 6 12 12"></path></svg>',
  locationIcon:
    '<svg class="inline-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"></path><circle cx="12" cy="10" r="2.5"></circle></svg>',
  shieldCheckIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 13c0 5-3.5 7.5-8 9-4.5-1.5-8-4-8-9V5l8-3 8 3v8Z"></path><path d="m9 12 2 2 4-4"></path></svg>',
  verifiedIcon:
    '<svg class="verified-icon is-verified" viewBox="0 0 24 24" aria-hidden="true"><path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z"></path><path d="m9 12 2 2 4-4"></path></svg>',
  unverifiedIcon:
    '<svg class="verified-icon is-unverified" viewBox="0 0 24 24" aria-hidden="true"><path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z"></path><path d="m9 12 2 2 4-4"></path></svg>',
};
