// Copy and fixed SVG assets retained from the existing HTML implementation.
export const ACCOUNT_COPY = {
  en: {
    back: "Back to profile",
    blockedBack: "My profile",
    blockedTitle: "Blocked users",
    unblockConfirmPrefix: "Unblock",
    unblockConfirmBody:
      "This user will be able to see your profile and write to you again.",
    edit: "Edit profile",
    photos: "Edit photos",
    photosHeading: "Photos",
    photosIntro:
      "Add photos to your profile. The first photo will be your avatar.",
    primary: "Primary",
    mainPhoto: "Main photo",
    avatar: "Avatar",
    avatarSet: "Avatar set",
    avatarNotSet: "Avatar not set",
    changeAvatar: "Change avatar",
    remove: "Delete",
    photoDeleteMainTitle: "Delete main photo?",
    photoDeleteMainBody:
      "Your main photo and avatar will be removed. Are you sure you want to continue?",
    photoDeleteAdditionalTitle: "Delete this photo?",
    photoDeleteAdditionalBody:
      "This photo will be permanently removed from your profile.",
    additionalPhotos: "Additional photos",
    addPhoto: "Add another photo",
    uploadPrompt: "Click to upload or drag a file",
    photoHelp: "JPEG, PNG or WebP (max. 10 MB)",
    photoLimit: "You can upload up to 6 photos.",
    photoLimitReached: "The 6 photo limit has been reached.",
    photoInvalid: "Only JPEG, PNG and WebP images are supported.",
    photoTooLarge: "The photo must not exceed 10 MB.",
    photoEmpty: "The selected photo is empty.",
    photoUploadFailed: "Unable to upload the photo. Try again.",
    photoUploadTimeout:
      "Photo upload took too long. Check your connection and try again.",
    cropTitle: "Crop your avatar",
    scale: "Scale",
    cancel: "Cancel",
    saveAvatar: "Save avatar",
    saving: "",
    upload: "",
    photoPending: "Photo is being checked automatically.",
    photoRejected: "Photo was rejected. Choose another image.",
    photoApproved: "Photo approved.",
    avatarVerificationResetTitle: "Change your verified profile photo?",
    avatarVerificationResetBody:
      "If you replace your main photo, your verification will be reset and you will need to complete it again.",
    avatarVerificationResetAction: "Change photo",
    completed: "Profile completed",
    visible: "Visible in catalog",
    premium: "Premium subscription",
    verification: "Profile verification",
    notifications: "Notification settings",
    language: "Interface language",
    blocked: "Blocked users",
    delete: "Delete account",
    signOut: "Sign out",
    editHeading: "Edit profile",
    basicInfo: "Basic information",
    questionnaire: "Matching questionnaire",
    questionnaireHelp:
      "These answers determine who you see and who can see you.",
    who: "Who you are",
    donorReady: "Ready to be a donor",
    childContact: "Contact with the child",
    editAnswers: "Edit answers",
    noAnswer: "Not specified",
    none: "No",
    fullAnonymity: "Full anonymity",
    limitedContact: "Contact by agreement",
    openContact: "Open contact",
    metric: "kg/cm",
    imperial: "lb/ft",
    heightPlain: "Height",
    weightPlain: "Weight",
    languagesPlain: "Languages",
    personal: "Personal details",
    name: "Your name",
    dob: "Date of birth",
    country: "Country",
    city: "City",
    profileType: "Profile type",
    searchCity: "Start typing a city",
    chooseCountryFirst: "Select a country first",
    noCitiesFound: "No cities found",
    searchLanguage: "Start typing a language...",
    noLanguagesFound: "No languages found",
    matching: "Matching",
    lookingFor: "Looking for",
    appearance: "Appearance",
    height: "Height (cm)",
    weight: "Weight (kg)",
    eye: "Eye color",
    hair: "Hair color",
    ethnicity: "Ethnicity",
    aboutSection: "About me",
    about: "About you",
    occupation: "Occupation",
    occupationPlaceholder: "e.g. Software Engineer, Teacher...",
    education: "Education",
    religion: "Religion",
    smoking: "Smoking",
    alcohol: "Alcohol",
    languages: "Languages (comma separated)",
    save: "Save changes",
    saved: "Profile saved.",
    choose: "Choose",
    verificationHeading: "Profile verification",
    verificationTitle: "We'll match your selfie to your main photo",
    verificationBody:
      "Make sure your main photo clearly shows your face — no sunglasses, hat, or phone covering it. If it doesn't, change it first or verification will fail.",
    currentPhoto: "Your main photo",
    changeMainPhoto: "Change main photo",
    startVerification: "Start verification",
    startingVerification: "Starting verification…",
    continueVerification: "Continue verification",
    cancelVerification: "Cancel",
    cancellingVerification: "Cancelling…",
    verificationCancelled:
      "Verification cancelled. You can start again at any time.",
    verificationCancelFailed:
      "Unable to cancel verification. Please try again.",
    tryAgain: "Try again",
    verificationPending: "Verification is being reviewed",
    verificationApproved: "Profile verified",
    verificationComplete: "Verification completed",
    verificationSuccessTitle: "Verification successful",
    verificationSuccessBody: "Your profile has been verified.",
    verificationFailureTitle: "Verification unsuccessful",
    verificationFailed: "Verification failed. You can try again.",
    verificationResultOk: "OK",
    verificationPhotoRequired:
      "Upload an approved main photo before starting verification.",
    verificationLoadFailed: "Unable to load verification status. Try again.",
    verificationStartTimeout:
      "Verification could not be started in time. Please try again.",
    verificationCreditsUnavailable:
      "Photo verification is temporarily unavailable because the verification service has no available credits.",
    providerUnavailable: "Photo verification is temporarily unavailable.",
    notificationsTitle: "Email notifications",
    notificationsIntro:
      "Manage the emails we send you. Push notifications are controlled by your device settings.",
    newMatch: "New matches",
    newMatchHelp: "When someone matches with you",
    newLike: "New likes",
    newLikeHelp: "When someone likes your profile",
    newMessage: "New messages",
    newMessageHelp: "When someone sends you a message",
    profileView: "Profile views",
    profileViewHelp: "Daily summary of who viewed your profile",
    marketing: "News & updates",
    marketingHelp: "Product updates and special offers",
    noBlocked: "You haven't blocked anyone",
    unblock: "Unblock",
    selectLanguage: "Choose interface language",
    close: "Close",
    deleteTitle: "Delete account",
    deleteBody:
      "Your profile will be hidden immediately. Your account and personal data will be permanently deleted after 30 days.",
    deleteReason: "Why are you leaving?",
    deleteConfirm: "Type delete to confirm",
    deleteWord: "delete",
    deleteButton: "Delete my account",
    deletionSent: "Account deletion scheduled.",
  },
  ru: {
    back: "Назад к профилю",
    blockedBack: "Мой профиль",
    blockedTitle: "Заблокированные",
    unblockConfirmPrefix: "Разблокировать",
    unblockConfirmBody:
      "Этот пользователь снова сможет видеть ваш профиль и писать вам.",
    edit: "Редактировать профиль",
    photos: "Редактировать фото",
    photosHeading: "Фотографии",
    photosIntro:
      "Добавьте фотографии в профиль. Первое фото будет вашим аватаром.",
    primary: "Главное",
    mainPhoto: "Главное фото",
    avatar: "Аватар",
    avatarSet: "Аватар установлен",
    avatarNotSet: "Аватар не установлен",
    changeAvatar: "Сменить аватар",
    remove: "Удалить",
    photoDeleteMainTitle: "Удалить главное фото?",
    photoDeleteMainBody:
      "Главное фото и аватар будут удалены. Вы уверены, что хотите продолжить?",
    photoDeleteAdditionalTitle: "Удалить эту фотографию?",
    photoDeleteAdditionalBody:
      "Фотография будет безвозвратно удалена из вашего профиля.",
    additionalPhotos: "Дополнительные фото",
    addPhoto: "Добавить фото",
    uploadPrompt: "Нажмите для загрузки или перетащите файл",
    photoHelp: "JPEG, PNG или WebP (макс. 10МБ)",
    photoLimit: "Можно загрузить не более 6 фотографий.",
    photoLimitReached: "Достигнут лимит: 6 фотографий.",
    photoInvalid: "Поддерживаются только JPEG, PNG и WebP.",
    photoTooLarge: "Размер фотографии не должен превышать 10 МБ.",
    photoEmpty: "Выбранная фотография пуста.",
    photoUploadFailed: "Не удалось загрузить фотографию. Попробуйте ещё раз.",
    photoUploadTimeout:
      "Загрузка фотографии заняла слишком много времени. Проверьте соединение и повторите попытку.",
    cropTitle: "Обрежьте аватар",
    scale: "Масштаб",
    cancel: "Отмена",
    saveAvatar: "Сохранить аватар",
    saving: "",
    upload: "",
    photoPending: "Фотография проходит автоматическую проверку.",
    photoRejected: "Фотография отклонена. Выберите другое изображение.",
    photoApproved: "Фотография одобрена.",
    avatarVerificationResetTitle: "Сменить фото верифицированного профиля?",
    avatarVerificationResetBody:
      "Если вы замените главное фото, верификация будет сброшена и её потребуется пройти заново.",
    avatarVerificationResetAction: "Сменить фото",
    completed: "Профиль заполнен",
    visible: "Показывать в каталоге",
    premium: "Премиум-подписка",
    verification: "Верификация профиля",
    notifications: "Настройки уведомлений",
    language: "Язык интерфейса",
    blocked: "Заблокированные пользователи",
    delete: "Удалить аккаунт",
    signOut: "Выйти",
    editHeading: "Редактирование профиля",
    basicInfo: "Основная информация",
    questionnaire: "Анкета для подбора",
    questionnaireHelp:
      "Эти ответы определяют, кого мы тебе показываем и кому показываем тебя.",
    who: "Кто ты",
    donorReady: "Готов(а) стать донором",
    childContact: "Мой контакт с ребёнком",
    editAnswers: "Изменить ответы",
    noAnswer: "Не указано",
    none: "Нет",
    fullAnonymity: "Полная анонимность",
    limitedContact: "Контакт по договорённости",
    openContact: "Открытый контакт",
    metric: "kg/cm",
    imperial: "lb/ft",
    heightPlain: "Рост",
    weightPlain: "Вес",
    languagesPlain: "Языки",
    personal: "Личные данные",
    name: "Ваше имя",
    dob: "Дата рождения",
    country: "Страна",
    city: "Город",
    profileType: "Тип профиля",
    searchCity: "Начните вводить город...",
    chooseCountryFirst: "Сначала выберите страну",
    noCitiesFound: "Города не найдены",
    searchLanguage: "Начните вводить язык...",
    noLanguagesFound: "Языки не найдены",
    matching: "Подбор пары",
    lookingFor: "Кого вы ищете",
    appearance: "Внешность",
    height: "Рост (см)",
    weight: "Вес (кг)",
    eye: "Цвет глаз",
    hair: "Цвет волос",
    ethnicity: "Этническая принадлежность",
    aboutSection: "Обо мне",
    about: "О себе",
    occupation: "Профессия",
    occupationPlaceholder: "Например, программист, учитель...",
    education: "Образование",
    religion: "Религия",
    smoking: "Курение",
    alcohol: "Алкоголь",
    languages: "Языки через запятую",
    save: "Сохранить",
    saved: "Профиль сохранён.",
    choose: "Выберите",
    verificationHeading: "Верификация профиля",
    verificationTitle: "Мы сравним ваше селфи с главным фото",
    verificationBody:
      "Убедитесь, что на главном фото хорошо видно ваше лицо — без солнцезащитных очков, головного убора и телефона, закрывающего лицо. Если это не так, сначала смените фото, иначе проверка не пройдёт.",
    currentPhoto: "Ваше главное фото",
    changeMainPhoto: "Сменить главное фото",
    startVerification: "Начать верификацию",
    startingVerification: "Запускаем верификацию…",
    continueVerification: "Продолжить верификацию",
    cancelVerification: "Отменить",
    cancellingVerification: "Отменяем…",
    verificationCancelled:
      "Верификация отменена. Её можно начать заново в любое время.",
    verificationCancelFailed:
      "Не удалось отменить верификацию. Попробуйте ещё раз.",
    tryAgain: "Попробовать снова",
    verificationPending: "Верификация на проверке",
    verificationApproved: "Профиль верифицирован",
    verificationComplete: "Верификация завершена",
    verificationSuccessTitle: "Верификация прошла успешно",
    verificationSuccessBody: "Ваш профиль верифицирован.",
    verificationFailureTitle: "Верификация не пройдена",
    verificationFailed: "Верификация не пройдена. Можно попробовать снова.",
    verificationResultOk: "ОК",
    verificationPhotoRequired:
      "Перед началом верификации загрузите одобренное главное фото.",
    verificationLoadFailed:
      "Не удалось загрузить статус верификации. Попробуйте ещё раз.",
    verificationStartTimeout:
      "Не удалось вовремя запустить верификацию. Попробуйте ещё раз.",
    verificationCreditsUnavailable:
      "Фотоверификация временно недоступна: на балансе сервиса проверки нет средств.",
    providerUnavailable: "Фотоверификация временно недоступна.",
    notificationsTitle: "Email-уведомления",
    notificationsIntro:
      "Управляйте письмами, которые мы вам отправляем. Push-уведомления настраиваются в настройках устройства.",
    newMatch: "Новые совпадения",
    newMatchHelp: "Когда кто-то совпал с вами",
    newLike: "Новые лайки",
    newLikeHelp: "Когда кто-то лайкнул ваш профиль",
    newMessage: "Новые сообщения",
    newMessageHelp: "Когда вам отправили сообщение",
    profileView: "Просмотры профиля",
    profileViewHelp: "Ежедневная сводка о тех, кто смотрел ваш профиль",
    marketing: "Новости и обновления",
    marketingHelp: "Обновления продукта и специальные предложения",
    noBlocked: "Вы никого не заблокировали.",
    unblock: "Разблокировать",
    selectLanguage: "Выберите язык интерфейса",
    close: "Закрыть",
    deleteTitle: "Удаление аккаунта",
    deleteBody:
      "Профиль будет скрыт сразу. Аккаунт и персональные данные будут окончательно удалены через 30 дней.",
    deleteReason: "Почему вы уходите?",
    deleteConfirm: "Введите delete для подтверждения",
    deleteWord: "delete",
    deleteButton: "Удалить аккаунт",
    deletionSent: "Удаление аккаунта запланировано.",
  },
  es: {
    back: "Volver al perfil",
    blockedBack: "Mi perfil",
    blockedTitle: "Bloqueados",
    unblockConfirmPrefix: "Desbloquear",
    unblockConfirmBody:
      "Este usuario podrá volver a ver tu perfil y escribirte.",
    edit: "Editar perfil",
    photos: "Editar fotos",
    photosHeading: "Fotos",
    photosIntro: "Añade fotos a tu perfil. La primera foto será tu avatar.",
    primary: "Principal",
    mainPhoto: "Foto principal",
    avatar: "Avatar",
    avatarSet: "Avatar establecido",
    avatarNotSet: "Avatar no establecido",
    changeAvatar: "Cambiar avatar",
    remove: "Eliminar",
    photoDeleteMainTitle: "¿Eliminar la foto principal?",
    photoDeleteMainBody:
      "Se eliminarán tu foto principal y tu avatar. ¿Seguro que quieres continuar?",
    photoDeleteAdditionalTitle: "¿Eliminar esta foto?",
    photoDeleteAdditionalBody:
      "Esta foto se eliminará permanentemente de tu perfil.",
    additionalPhotos: "Fotos adicionales",
    addPhoto: "Añadir foto",
    uploadPrompt: "Haz clic para subir o arrastra un archivo",
    photoHelp: "JPEG, PNG o WebP (máx. 10 MB)",
    photoLimit: "Puedes subir hasta 6 fotos.",
    photoLimitReached: "Se alcanzó el límite de 6 fotos.",
    photoInvalid: "Solo se admiten imágenes JPEG, PNG y WebP.",
    photoTooLarge: "La foto no debe superar los 10 MB.",
    photoEmpty: "La foto seleccionada está vacía.",
    photoUploadFailed: "No se pudo cargar la foto. Inténtalo de nuevo.",
    photoUploadTimeout:
      "La carga de la foto tardó demasiado. Comprueba la conexión e inténtalo de nuevo.",
    cropTitle: "Recorta tu avatar",
    scale: "Escala",
    cancel: "Cancelar",
    saveAvatar: "Guardar avatar",
    saving: "",
    upload: "",
    photoPending: "La foto está siendo comprobada automáticamente.",
    photoRejected: "La foto fue rechazada. Elige otra imagen.",
    photoApproved: "Foto aprobada.",
    avatarVerificationResetTitle: "¿Cambiar la foto de un perfil verificado?",
    avatarVerificationResetBody:
      "Si reemplazas la foto principal, se restablecerá la verificación y tendrás que completarla de nuevo.",
    avatarVerificationResetAction: "Cambiar foto",
    completed: "Perfil completado",
    visible: "Visible en el catálogo",
    premium: "Suscripción Premium",
    verification: "Verificación del perfil",
    notifications: "Notificaciones",
    language: "Idioma",
    blocked: "Usuarios bloqueados",
    delete: "Eliminar cuenta",
    signOut: "Cerrar sesión",
    editHeading: "Editar perfil",
    basicInfo: "Información básica",
    questionnaire: "Cuestionario de coincidencias",
    questionnaireHelp:
      "Estas respuestas determinan a quién ves y quién puede verte.",
    who: "Quién eres",
    donorReady: "Dispuesto a donar",
    childContact: "Contacto con el niño",
    editAnswers: "Editar respuestas",
    noAnswer: "Sin especificar",
    none: "No",
    fullAnonymity: "Anonimato completo",
    limitedContact: "Contacto por acuerdo",
    openContact: "Contacto abierto",
    metric: "kg/cm",
    imperial: "lb/ft",
    heightPlain: "Altura",
    weightPlain: "Peso",
    languagesPlain: "Idiomas",
    personal: "Datos personales",
    name: "Tu nombre",
    dob: "Fecha de nacimiento",
    country: "País",
    city: "Ciudad",
    profileType: "Tipo de perfil",
    searchCity: "Empieza a escribir una ciudad...",
    chooseCountryFirst: "Selecciona primero un país",
    noCitiesFound: "No se encontraron ciudades",
    searchLanguage: "Empieza a escribir un idioma...",
    noLanguagesFound: "No se encontraron idiomas",
    matching: "Coincidencias",
    lookingFor: "Busco",
    appearance: "Apariencia",
    height: "Altura (cm)",
    weight: "Peso (kg)",
    eye: "Color de ojos",
    hair: "Color de pelo",
    ethnicity: "Origen étnico",
    aboutSection: "Sobre mí",
    about: "Sobre mí",
    occupation: "Ocupación",
    occupationPlaceholder: "p. ej., ingeniero de software, docente...",
    education: "Educación",
    religion: "Religión",
    smoking: "Tabaco",
    alcohol: "Alcohol",
    languages: "Idiomas separados por comas",
    save: "Guardar",
    saved: "Perfil guardado.",
    choose: "Selecciona",
    verificationHeading: "Verificación del perfil",
    verificationTitle: "Compararemos tu selfie con tu foto principal",
    verificationBody:
      "Asegúrate de que tu foto principal muestre claramente tu cara, sin gafas de sol, gorra ni teléfono que la tapen. Si no es así, cámbiala primero o la verificación fallará.",
    currentPhoto: "Tu foto principal",
    changeMainPhoto: "Cambiar foto principal",
    startVerification: "Iniciar verificación",
    startingVerification: "Iniciando la verificación…",
    continueVerification: "Continuar verificación",
    cancelVerification: "Cancelar",
    cancellingVerification: "Cancelando…",
    verificationCancelled:
      "Verificación cancelada. Puedes volver a iniciarla en cualquier momento.",
    verificationCancelFailed:
      "No se pudo cancelar la verificación. Inténtalo de nuevo.",
    tryAgain: "Intentar de nuevo",
    verificationPending: "Verificación en revisión",
    verificationApproved: "Perfil verificado",
    verificationComplete: "Verificación completada",
    verificationSuccessTitle: "Verificación completada correctamente",
    verificationSuccessBody: "Tu perfil ha sido verificado.",
    verificationFailureTitle: "No se pudo completar la verificación",
    verificationFailed: "La verificación falló. Puedes volver a intentarlo.",
    verificationResultOk: "Aceptar",
    verificationPhotoRequired:
      "Sube una foto principal aprobada antes de iniciar la verificación.",
    verificationLoadFailed:
      "No se pudo cargar el estado de verificación. Inténtalo de nuevo.",
    verificationStartTimeout:
      "No se pudo iniciar la verificación a tiempo. Inténtalo de nuevo.",
    verificationCreditsUnavailable:
      "La verificación de foto no está disponible temporalmente porque el servicio no tiene créditos disponibles.",
    providerUnavailable:
      "La verificación de foto no está disponible temporalmente.",
    notificationsTitle: "Notificaciones por email",
    notificationsIntro:
      "Gestiona los correos que te enviamos. Las notificaciones push se controlan desde los ajustes de tu dispositivo.",
    newMatch: "Nuevos matches",
    newMatchHelp: "Cuando alguien hace match contigo",
    newLike: "Nuevos likes",
    newLikeHelp: "Cuando alguien da like a tu perfil",
    newMessage: "Nuevos mensajes",
    newMessageHelp: "Cuando alguien te envía un mensaje",
    profileView: "Visitas al perfil",
    profileViewHelp: "Resumen diario de quién ha visto tu perfil",
    marketing: "Noticias y novedades",
    marketingHelp: "Actualizaciones y ofertas especiales",
    noBlocked: "No has bloqueado a nadie.",
    unblock: "Desbloquear",
    selectLanguage: "Elige el idioma",
    close: "Cerrar",
    deleteTitle: "Eliminar cuenta",
    deleteBody:
      "Tu perfil se ocultará de inmediato. La cuenta y los datos se eliminarán definitivamente después de 30 días.",
    deleteReason: "¿Por qué te vas?",
    deleteConfirm: "Escribe delete para confirmar",
    deleteWord: "delete",
    deleteButton: "Eliminar mi cuenta",
    deletionSent: "Eliminación programada.",
  },
} as const;

export const ACCOUNT_ICONS = {
  eyeIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"></path><circle cx="12" cy="12" r="2.5"></circle></svg>',
  lockIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><rect width="14" height="10" x="5" y="11" rx="2"></rect><path d="M8 11V7a4 4 0 0 1 8 0v4"></path></svg>',
  globeIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"></circle><path d="M3 12h18"></path><path d="M12 3c2.4 2.5 3.6 5.5 3.6 9S14.4 18.5 12 21c-2.4-2.5-3.6-5.5-3.6-9S9.6 5.5 12 3Z"></path></svg>',
  edit: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M11.5 15H7a4 4 0 0 0-4 4v2"></path><path d="M21.378 16.626a1 1 0 0 0-3.004-3.004l-4.01 4.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z"></path><circle cx="10" cy="7" r="4"></circle></svg>',
  premium:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z"></path><path d="M5 21h14"></path></svg>',
  verification:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"></path><path d="m9 12 2 2 4-4"></path></svg>',
  notifications:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10.268 21a2 2 0 0 0 3.464 0"></path><path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"></path></svg>',
  language:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 8 6 6"></path><path d="m4 14 6-6 2-3"></path><path d="M2 5h12"></path><path d="M7 2h1"></path><path d="m22 22-5-10-5 10"></path><path d="M14 18h6"></path></svg>',
  blocked:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><path d="M4.929 4.929 19.07 19.071"></path></svg>',
  delete:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 11v6"></path><path d="M14 11v6"></path><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"></path><path d="M3 6h18"></path><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>',
  signout:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m16 17 5-5-5-5"></path><path d="M21 12H9"></path><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path></svg>',
  cameraIcon:
    '<svg class="action-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M14.5 4h-5L7.7 6H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-2.7L14.5 4Z"></path><circle cx="12" cy="13" r="3"></circle></svg>',
  mailIcon:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"></rect><path d="m3 7 9 6 9-6"></path></svg>',
  languageCheckIcon:
    '<svg class="language-selected-check" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"></path></svg>',
  savedFavouriteIcon:
    '<svg class="saved-directory-button-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z"></path><path d="M7 10v12"></path></svg>',
} as const;

export const ACCOUNT_DELETION_REASONS = {
  en: [
    "No matches",
    "No longer interested",
    "Found what I was looking for",
    "Too expensive",
    "Privacy concerns",
    "Technical problems",
    "Taking a break",
    "Other",
    "Prefer not to say",
  ],
  ru: [
    "Нет совпадений",
    "Больше неинтересно",
    "Я нашёл то, что искал",
    "Слишком дорого",
    "Опасения о конфиденциальности",
    "Технические проблемы",
    "Просто делаю перерыв",
    "Другое",
    "Предпочитаю не отвечать",
  ],
  es: [
    "Sin coincidencias",
    "Ya no me interesa",
    "Encontré lo que buscaba",
    "Demasiado caro",
    "Privacidad",
    "Problemas técnicos",
    "Tomarme un descanso",
    "Otro",
    "Prefiero no decirlo",
  ],
} as const;

export const LIKES_COPY = {
  en: {
    likesTitle: "Likes",
    likesYou: "Likes you",
    matches: "Matches",
    myLikes: "My likes",
    visitors: "Visitors",
    clinics: "Clinics",
    lawyers: "Lawyers",
    noLikes:
      "No one has liked you yet. Complete your profile to attract more attention!",
    noMatches: "You do not have any matches yet.",
    myLikesEmpty: "Profiles you like will appear here.",
    noViews: "No one has viewed your profile yet.",
    savedClinics:
      "You haven't saved any clinics yet. Browse clinics to add them to your favorites!",
    savedLawyers:
      "You haven't saved any lawyers yet. Browse lawyers to add them to your favorites!",
    peopleLiked: "people liked your profile",
    peopleViewed: "people viewed your profile",
    likesPremium: "Upgrade to Premium to see who liked you",
    viewsPremium: "Upgrade to Premium to see profile visitors",
    saved: "Liked",
    favouriteRemoveFailed: "Could not remove this item from saved.",
    like: "Like",
    liked: "Liked",
    sendMessage: "Send message",
  },
  ru: {
    likesTitle: "Лайки",
    likesYou: "Вас лайкнули",
    matches: "Совпадения",
    myLikes: "Мои лайки",
    visitors: "Гости",
    clinics: "Клиники",
    lawyers: "Юристы",
    noLikes:
      "Вам пока не поставили лайк. Заполните профиль, чтобы привлечь больше внимания.",
    noMatches: "Совпадений пока нет.",
    myLikesEmpty: "Понравившиеся анкеты появятся здесь.",
    noViews: "Ваш профиль пока никто не просматривал.",
    savedClinics:
      "Вы пока не сохранили ни одной клиники. Добавьте понравившиеся клиники в избранное!",
    savedLawyers:
      "Вы пока не сохранили ни одного юриста. Добавьте понравившихся юристов в избранное!",
    peopleLiked: "человек отметили вашу анкету",
    peopleViewed: "человек посмотрели вашу анкету",
    likesPremium: "Перейдите на Premium, чтобы увидеть, кому вы понравились",
    viewsPremium: "Перейдите на Premium, чтобы увидеть посетителей профиля",
    saved: "В избранном",
    favouriteRemoveFailed: "Не удалось удалить из избранного.",
    like: "Нравится",
    liked: "Liked",
    sendMessage: "Отправить сообщение",
  },
  es: {
    likesTitle: "Me gusta",
    likesYou: "Les gustas",
    matches: "Coincidencias",
    myLikes: "Mis Me gusta",
    visitors: "Visitantes",
    clinics: "Clínicas",
    lawyers: "Abogados",
    noLikes:
      "Aún no le has gustado a nadie. Completa tu perfil para atraer más atención.",
    noMatches: "Aún no tienes coincidencias.",
    myLikesEmpty: "Los perfiles que te gusten aparecerán aquí.",
    noViews: "Nadie ha visto tu perfil todavía.",
    savedClinics:
      "Aún no has guardado ninguna clínica. Añade tus clínicas favoritas.",
    savedLawyers:
      "Aún no has guardado ningún abogado. Añade tus abogados favoritos.",
    peopleLiked: "personas marcaron tu perfil",
    peopleViewed: "personas vieron tu perfil",
    likesPremium: "Mejora a Premium para ver a quién le gustas",
    viewsPremium: "Mejora a Premium para ver visitantes",
    saved: "Guardado",
    favouriteRemoveFailed: "No se pudo quitar de guardados.",
    like: "Me gusta",
    liked: "Liked",
    sendMessage: "Enviar mensaje",
  },
} as const;
