import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';
import { Link, Navigate, useLocation, useNavigate, useParams } from 'react-router-dom';
import { ApiError, createApiClient } from './api';
import { Overlay } from './member-profile';
import { AccountPremium, memberBoolean, ownProfileData } from './member-account';
import { UserAvatar } from './user-avatar';
import { CHAT_COPY, CHAT_ICONS } from './member-chat-reference';
import { type ChatLocale, type ChatRow, chatText, chatInitials, chatFileSize, chatName, chatPeer, chatSupport, chatPath, legacyChatPath, chatDate, chatDayKey, chatDay, chatTime, chatListTime, chatOnline, chatActivity, chatMediaUrl, chatImage, chatPreview, chatDelivery, mergeChatMessages, chatAttachmentError, CHAT_REPORT_REASONS } from './member-chat-model';

const api=createApiClient();
type Session={user:ChatRow}|null;
type MessagePage={items:ChatRow[];markedReadCount?:number;counts?:ChatRow;hasMore?:boolean};
const EXTRA={en:{loading:'Loading…',retry:'Try again',failed:'Unable to complete this action. Please try again.',missing:'This conversation is not available.',older:'Load earlier messages',file:'File',sending:'Sending…',unavailable:'Attachment unavailable'},ru:{loading:'Загрузка…',retry:'Повторить',failed:'Не удалось выполнить действие. Попробуйте ещё раз.',missing:'Этот диалог недоступен.',older:'Загрузить предыдущие сообщения',file:'Файл',sending:'Отправка…',unavailable:'Вложение недоступно'},es:{loading:'Cargando…',retry:'Reintentar',failed:'No se pudo completar la acción. Inténtalo de nuevo.',missing:'Esta conversación no está disponible.',older:'Cargar mensajes anteriores',file:'Archivo',sending:'Enviando…',unavailable:'Archivo no disponible'}};
export function ChatIcon({name,className='',label}:{name:string;className?:string;label?:string}){const source=CHAT_ICONS[name]||'';return <svg className={`chat-icon ${className}`} viewBox={source.match(/viewBox="([^"]+)"/)?.[1]||'0 0 24 24'} aria-hidden={label?undefined:true} role={label?'img':undefined} aria-label={label} dangerouslySetInnerHTML={{__html:source.replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'')}}/>;}
export function ChatAvatar({item,locale,className='chat-avatar'}:{item:ChatRow;locale:ChatLocale;className?:string}){const support=chatSupport(item),online=!support&&className!=='chat-message-avatar'&&chatOnline(item);return <span className={`${className}${support?' is-support':''}`}>
  {support?<ChatIcon name="supportIcon"/>:<UserAvatar src={chatMediaUrl(item.otherAvatarUrl||item.peerAvatarUrl)} name={chatName(item,locale)} initials={chatInitials(chatName(item,locale))} fallbackClassName="chat-avatar-fallback"/>}
  {online&&<span className="chat-presence-dot" role="img" aria-label={chatActivity(item,locale)} title={chatActivity(item,locale)}/>}
</span>;}
export function ChatLegacyRedirect(){const location=useLocation();return <Navigate replace to={legacyChatPath(location.pathname,location.search,location.hash)}/>;}
function ChatLoading({locale}:{locale:ChatLocale}){return <div className="chat-loading" role="status" aria-label={EXTRA[locale].loading}><span/></div>;}
function errorText(error:unknown,locale:ChatLocale){if(error instanceof ApiError&&error.status<500){try{const value=JSON.parse(error.message);if(typeof value.detail==='string')return value.detail;}catch{/* Do not expose HTML or internal server errors. */}}return EXTRA[locale].failed;}
function announceCounts(){window.dispatchEvent(new Event('lbp-member-changed'));}

type EmojiPickerOptions={onEmojiSelect:(emoji:{native?:string})=>void;[key:string]:unknown};
declare global {interface Window {EmojiMart?:{Picker:new(options:EmojiPickerOptions)=>HTMLElement}}}
let emojiScript:Promise<void>|undefined;
function loadEmojiScript(){if(window.EmojiMart)return Promise.resolve();if(!emojiScript)emojiScript=new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='/web-static/chat/emoji-mart-dd59b205.js';script.async=true;script.onload=()=>window.EmojiMart?resolve():reject(new Error('Emoji picker unavailable'));script.onerror=()=>{script.remove();reject(new Error('Emoji picker unavailable'));};document.head.append(script);}).catch(e=>{emojiScript=undefined;throw e;});return emojiScript;}
function ChatEmoji({locale,onSelect,onClose}:{locale:ChatLocale;onSelect:(emoji:string)=>void;onClose:()=>void}){const root=useRef<HTMLDivElement>(null),select=useRef(onSelect);select.current=onSelect;const [error,setError]=useState(false),[retry,setRetry]=useState(0);useEffect(()=>{let active=true;setError(false);const translations={en:'en-027a0f7a',ru:'ru-c8ea5595',es:'es-ccd117de'};void Promise.all([loadEmojiScript(),...['emoji-native-e1e7d657',translations[locale]].map(async file=>{const result=await fetch(`/web-static/chat/${file}.json`);if(!result.ok)throw new Error('Emoji data unavailable');return result.json();})]).then(([,data,i18n])=>{if(!active||!root.current||!window.EmojiMart)return;const picker=new window.EmojiMart.Picker({data,i18n,locale,set:'native',theme:'light',navPosition:'top',previewPosition:'none',skinTonePosition:'none',dynamicWidth:true,emojiButtonSize:36,emojiSize:24,onEmojiSelect:emoji=>{if(emoji.native)select.current(emoji.native);}});root.current.replaceChildren(picker);}).catch(()=>{if(active)setError(true);});return()=>{active=false;root.current?.replaceChildren();};},[locale,retry]);return <div className="chat-emoji-panel" role="dialog" aria-label={CHAT_COPY[locale].emoji} onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();onClose();}}}><div className="chat-emoji-mount" ref={root}/>{error&&<div role="alert">{EXTRA[locale].failed}<button onClick={()=>setRetry(v=>v+1)}>{EXTRA[locale].retry}</button></div>}</div>;}

export function MemberChat({session,locale}:{session:Session;locale:ChatLocale}){if(!session)return <Navigate to={`/${locale}/auth/login`} replace/>;return <ChatWorkspace key={chatText(session.user.id)} session={session} locale={locale}/>;}
function ChatWorkspace({session,locale}:{session:{user:ChatRow};locale:ChatLocale}){
  const c=CHAT_COPY[locale],x=EXTRA[locale],navigate=useNavigate(),location=useLocation(),params=useParams();
  const selected=chatText(params.conversationId),selectedRef=useRef(selected);selectedRef.current=selected;
  const [items,setItems]=useState<ChatRow[]>([]),[extra,setExtra]=useState<ChatRow|null>(null),[profile,setProfile]=useState<ChatRow>({});
  const [listLoading,setListLoading]=useState(true),[listError,setListError]=useState(''),[query,setQuery]=useState('');
  const [messages,setMessages]=useState<ChatRow[]>([]),[loading,setLoading]=useState(false),[hasMore,setHasMore]=useState(false),[loadingOlder,setLoadingOlder]=useState(false);
  const [drafts,setDrafts]=useState<Record<string,string>>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[menu,setMenu]=useState(false),[emoji,setEmoji]=useState(false);
  const [dialog,setDialog]=useState<'delete'|'block'|'report'|'premium'|'verify'|null>(null),[reason,setReason]=useState(''),[details,setDetails]=useState(''),[file,setFile]=useState<File|null>(null),[failedMedia,setFailedMedia]=useState<Record<string,boolean>>({}),[fileUrl,setFileUrl]=useState(''),[image,setImage]=useState('');
  const mounted=useRef(true),listSequence=useRef(0),messageFlight=useRef(false),actionFlight=useRef(false),messageSequence=useRef(0),scroll=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null),attachment=useRef<HTMLInputElement>(null),menuRoot=useRef<HTMLSpanElement>(null),compose=useRef<HTMLDivElement>(null),stickBottom=useRef(true),firstPage=useRef(true),scrollRestore=useRef<{height:number;top:number}|null>(null);
  const active=items.find(item=>chatText(item.id)===selected)||(chatText(extra?.id)===selected?extra:null),support=active?chatSupport(active):false;
  const profileId=chatText(profile.id,session.user.profileId),body=drafts[selected]||'';
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;messageSequence.current++;};},[]);
  useEffect(()=>{let alive=true;void api.get<ChatRow>('/member/me').then(result=>{if(alive)setProfile(ownProfileData(result.profile));}).catch(()=>{});return()=>{alive=false;};},[]);
  const loadList=useCallback(async()=>{const sequence=++listSequence.current,search=query.trim(),suffix=search?`?q=${encodeURIComponent(search)}`:'';try{const result=await api.get<{items:ChatRow[]}>(`/member/conversations${suffix}`);if(mounted.current&&sequence===listSequence.current){setItems(result.items||[]);setListError('');}}catch(failure){if(mounted.current&&sequence===listSequence.current)setListError(errorText(failure,locale));}finally{if(mounted.current&&sequence===listSequence.current)setListLoading(false);}},[locale,query]);
  useEffect(()=>{void loadList();const timer=window.setInterval(()=>{if(!document.hidden)void loadList();},10000);const focus=()=>{if(!document.hidden)void loadList();};document.addEventListener('visibilitychange',focus);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',focus);};},[loadList]);
  useEffect(()=>{let alive=true;setExtra(null);if(!selected||listLoading||items.some(item=>chatText(item.id)===selected))return;if(!/^[1-9]\d*$/.test(selected)){setError(x.missing);return;}void api.get<{items:ChatRow[]}>(`/member/conversations?conversationId=${encodeURIComponent(selected)}`).then(result=>{if(!alive)return;const item=result.items?.find(row=>chatText(row.id)===selected);if(item)setExtra(item);else setError(x.missing);}).catch(failure=>{if(alive)setError(errorText(failure,locale));});return()=>{alive=false;};},[selected,listLoading,items,locale,x.missing]);
  useEffect(()=>{setMessages([]);setError('');setNotice('');setMenu(false);setEmoji(false);setDialog(null);setFile(null);setHasMore(false);setLoading(!!selected);firstPage.current=true;stickBottom.current=true;messageSequence.current++;},[selected]);
  const refreshMessages=useCallback(async(force=false)=>{const id=selectedRef.current;if(!id||(!force&&messageFlight.current))return;const sequence=++messageSequence.current;messageFlight.current=true;try{const result=await api.get<MessagePage>(`/member/conversations/${encodeURIComponent(id)}/messages`);if(!mounted.current||selectedRef.current!==id||sequence!==messageSequence.current)return;const initial=firstPage.current;setMessages(previous=>initial?result.items||[]:mergeChatMessages(previous,result.items||[]));setHasMore(previous=>initial?!!result.hasMore:previous);firstPage.current=false;if(result.markedReadCount){announceCounts();setItems(previous=>previous.map(item=>chatText(item.id)===id?{...item,unreadCount:0}:item));}}catch(failure){if(mounted.current&&selectedRef.current===id&&sequence===messageSequence.current)setError(errorText(failure,locale));}finally{messageFlight.current=false;if(mounted.current&&selectedRef.current===id&&sequence===messageSequence.current)setLoading(false);}},[locale]);
  useEffect(()=>{if(!selected||!active)return;void refreshMessages(true);const timer=window.setInterval(()=>{if(!document.hidden)void refreshMessages();},3000);const focus=()=>{if(!document.hidden)void refreshMessages();};document.addEventListener('visibilitychange',focus);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',focus);};},[selected,!!active,refreshMessages]);
  useEffect(()=>{const refresh=()=>{void loadList();void refreshMessages(true);};window.addEventListener('lbp-chat-refresh',refresh);return()=>window.removeEventListener('lbp-chat-refresh',refresh);},[loadList,refreshMessages]);
  useLayoutEffect(()=>{const pane=scroll.current;if(!pane)return;if(scrollRestore.current){pane.scrollTop=scrollRestore.current.top+pane.scrollHeight-scrollRestore.current.height;scrollRestore.current=null;}else if(stickBottom.current)pane.scrollTop=pane.scrollHeight;},[messages,loading]);
  useLayoutEffect(()=>{if(input.current){input.current.style.height='40px';input.current.style.height=Math.min(input.current.scrollHeight,120)+'px';input.current.style.overflowY=input.current.scrollHeight>120?'auto':'hidden';}},[body,selected,!!active]);
  useEffect(()=>{if(!file)return;const url=file.type.startsWith('image/')?URL.createObjectURL(file):'';setFileUrl(url);return()=>{if(url)URL.revokeObjectURL(url);setFileUrl('');};},[file]);
  useEffect(()=>{const click=(event:MouseEvent)=>{const target=event.target as Node;if(!menuRoot.current?.contains(target))setMenu(false);if(!compose.current?.contains(target))setEmoji(false);};const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenu(false);setEmoji(false);}};document.addEventListener('click',click);document.addEventListener('keydown',key);return()=>{document.removeEventListener('click',click);document.removeEventListener('keydown',key);};},[]);
  useEffect(()=>{if(menu)menuRoot.current?.querySelector<HTMLElement>('[role=menuitem]')?.focus();},[menu]);
  if(!selected&&new URLSearchParams(location.search).has('conversation'))return <Navigate replace to={legacyChatPath(location.pathname,location.search,location.hash)}/>;
  const setBody=(value:string)=>setDrafts(previous=>({...previous,[selected]:value}));
  const close=()=>{if(!actionFlight.current){setDialog(null);setError('');}};
  const handleFailure=(failure:unknown)=>{if(failure instanceof ApiError&&failure.status===401){navigate(`/${locale}/auth/login`);return;}if(failure instanceof ApiError&&failure.status===402){setDialog('premium');return;}if(failure instanceof ApiError&&failure.status===403&&/verif/i.test(failure.message)){setDialog('verify');return;}setError(errorText(failure,locale));};
  const runAction=async(task:()=>Promise<void>)=>{if(actionFlight.current)return;const actionConversation=selectedRef.current;actionFlight.current=true;setBusy(true);setError('');try{await task();}catch(failure){if(mounted.current&&selectedRef.current===actionConversation)handleFailure(failure);}finally{actionFlight.current=false;if(mounted.current)setBusy(false);}};
  const send=()=>{const id=selectedRef.current,value=(drafts[id]||'').trim();if(!id||!active||!value)return;void runAction(async()=>{await api.post(`/member/conversations/${encodeURIComponent(id)}/messages`,{body:value});if(!mounted.current)return;setDrafts(previous=>previous[id]?.trim()===value?{...previous,[id]:''}:previous);if(selectedRef.current===id){stickBottom.current=true;await refreshMessages(true);input.current?.focus();}await loadList();announceCounts();});};
  const sendAttachment=()=>{const id=selectedRef.current,pending=file;if(!id||!pending)return;void runAction(async()=>{const data=new FormData();data.append('file',pending);await api.upload(`/member/conversations/${encodeURIComponent(id)}/attachments`,data);if(!mounted.current)return;setFile(null);if(selectedRef.current===id){stickBottom.current=true;await refreshMessages(true);}await loadList();announceCounts();});};
  const loadOlder=async()=>{if(loadingOlder||!messages.length||!selected)return;const id=selected;setLoadingOlder(true);try{const result=await api.get<MessagePage>(`/member/conversations/${encodeURIComponent(id)}/messages?beforeId=${encodeURIComponent(chatText(messages[0].id))}`);if(!mounted.current||id!==selectedRef.current)return;if(scroll.current)scrollRestore.current={height:scroll.current.scrollHeight,top:scroll.current.scrollTop};setMessages(previous=>mergeChatMessages(previous,result.items||[]));setHasMore(!!result.hasMore);}catch(failure){if(mounted.current&&selectedRef.current===id)setError(errorText(failure,locale));}finally{if(mounted.current)setLoadingOlder(false);}};
  const peer=active?chatPeer(active):'';
  const viewPeer=()=>void runAction(async()=>{const id=selected;const result=await api.get<ChatRow>(`/member/conversations/${encodeURIComponent(id)}/peer-profile`);const target=chatText(result.profileId,peer);if(mounted.current&&selectedRef.current===id&&target)navigate(`/${locale}/profile/${encodeURIComponent(target)}`);});
  const mutate=()=>{const id=selected,kind=dialog,target=peer;if(!id||!active||support||!kind)return;void runAction(async()=>{if(kind==='delete')await api.delete(`/member/conversations/${encodeURIComponent(id)}`);else if(kind==='block'&&target)await api.post(`/member/blocks/${encodeURIComponent(target)}`);else if(kind==='report'&&target&&reason){await api.post(`/member/reports/${encodeURIComponent(target)}`,{reason,details:details.trim()});if(mounted.current){setNotice(c.reportSent);setDialog(null);}return;}else return;if(!mounted.current)return;setDialog(null);setItems(previous=>previous.filter(item=>chatText(item.id)!==id));setExtra(null);if(selectedRef.current===id)navigate(chatPath(locale),{replace:true});await loadList();announceCounts();});};
  const call=(callType:'VOICE'|'VIDEO')=>{if(!active||support)return;if(!memberBoolean(profile.isVerified)){setDialog('verify');return;}if(!memberBoolean(profile.isPremium)){setDialog('premium');return;}const id=selected;void runAction(async()=>{const result=await api.post<{call:ChatRow}>(`/member/conversations/${encodeURIComponent(id)}/calls`,{callType});if(result.call)window.dispatchEvent(new CustomEvent('lbp-call-start',{detail:result.call}));});};
  const visible=items,feedback=<>{error&&<div className="chat-feedback" role="alert">{error}<button type="button" disabled={busy} onClick={()=>{setError('');void loadList();if(selected)void refreshMessages(true);}}>{x.retry}</button></div>}{notice&&<p className="chat-feedback" role="status">{notice}</p>}</>;
  let previousDay='';
  return <div className="chat-page-shell"><section className={`chat-shell${selected?' conversation-open':''}`} aria-label={c.messagesTitle}>
    <aside className="chat-list-column"><div className="chat-list-head"><h1>{c.messagesTitle}</h1><label className="chat-search"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m21 21-4.34-4.34"/><circle cx="11" cy="11" r="8"/></svg><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={c.searchConversations} aria-label={c.searchConversations}/></label></div>
      {listLoading?<ChatLoading locale={locale}/>:listError?<div className="chat-feedback" role="alert">{listError}<button onClick={()=>void loadList()}>{x.retry}</button></div>:visible.length?<div className="chat-list">{visible.map(item=><button className={`chat-row${chatText(item.id)===selected?' active':''}`} key={chatText(item.id)} type="button" aria-current={chatText(item.id)===selected?'page':undefined} onClick={()=>navigate(chatPath(locale,item.id))}><ChatAvatar item={item} locale={locale}/><span className="chat-row-copy"><strong>{chatName(item,locale)}</strong><small title={chatPreview(item,profileId,locale)}>{chatPreview(item,profileId,locale)}</small></span><span className="chat-row-meta"><time>{chatListTime(item,locale)}</time>{Number(item.unreadCount)>0&&<span className="badge-inline">{Number(item.unreadCount)>99?'99+':Number(item.unreadCount)}</span>}</span></button>)}</div>:<p className={query?"chat-search-empty":"empty-chat-list"}>{query?c.noSearchConversations:c.noConversations}</p>}
    </aside>
    <section className="chat-pane" data-active={selected?'true':'false'} aria-label={active?chatName(active,locale):c.messagesTitle}>
      {!selected?<div className="chat-empty-state"><span><ChatIcon name="messageIcon" className="action-icon"/></span><p>{c.selectConversation}</p></div>:<div className="chat-active-pane">
        <div className="chat-head"><button className="chat-back" type="button" aria-label={c.backConversations} onClick={()=>navigate(chatPath(locale))}><ChatIcon name="pageBackIcon"/></button>{active&&<ChatAvatar item={active} locale={locale} className="chat-head-avatar"/>}<span className="chat-head-copy">{active&&!support&&peer?<Link to={`/${locale}/profile/${encodeURIComponent(peer)}`}><strong>{chatName(active,locale)}</strong></Link>:<strong>{active?chatName(active,locale):c.messagesTitle}</strong>}<small>{active?chatActivity(active,locale):''}</small></span>
          {active&&!support&&<span className="chat-head-actions"><button className="chat-head-action" disabled={busy} aria-label={c.voiceCall} title={c.voiceCall} onClick={()=>call('VOICE')}><ChatIcon name="phoneIcon"/></button><button className="chat-head-action" disabled={busy} aria-label={c.videoCall} title={c.videoCall} onClick={()=>call('VIDEO')}><ChatIcon name="videoIcon"/></button><span className="chat-head-menu-wrap" ref={menuRoot}><button className="chat-head-action" aria-label={c.actions} aria-haspopup="menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}><ChatIcon name="moreVerticalIcon"/></button>{menu&&<span className="chat-head-menu" role="menu" onKeyDown={event=>{const options=Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('[role=menuitem]')),index=options.indexOf(document.activeElement as HTMLButtonElement);if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();options[event.key==='Home'?0:event.key==='End'?options.length-1:(index+(event.key==='ArrowDown'?1:-1)+options.length)%options.length]?.focus();}if(event.key==='Escape'){setMenu(false);menuRoot.current?.querySelector('button')?.focus();}}}>
            {peer&&<button role="menuitem" disabled={busy} onClick={()=>{setMenu(false);viewPeer();}}><ChatIcon name="userProfileIcon"/><span>{c.viewProfile}</span></button>}{(['delete','report','block'] as const).filter(kind=>kind==='delete'||peer).map(kind=><button className="danger" role="menuitem" key={kind} disabled={busy} onClick={()=>{setMenu(false);setReason('');setDetails('');setError('');setDialog(kind);}}><ChatIcon name={{delete:'trashIcon',report:'flagIcon',block:'banIcon'}[kind]}/><span>{{delete:c.deleteChat,report:c.report,block:c.blockUser}[kind]}</span></button>)}
          </span>}</span></span>}
        </div>
        {!dialog&&feedback}
        <div className="chat-messages" ref={scroll} onScroll={()=>{const pane=scroll.current;if(pane)stickBottom.current=pane.scrollHeight-pane.scrollTop-pane.clientHeight<90;}}><div className="chat-message-list" aria-live="polite" aria-relevant="additions text">
          {hasMore&&<button className="chat-older" disabled={loadingOlder} onClick={()=>void loadOlder()}>{loadingOlder?x.loading:x.older}</button>}
          {loading&&active?<ChatLoading locale={locale}/>:!active?<p className="chat-no-messages">{listLoading?x.loading:error||x.missing}</p>:!messages.length?<p className="chat-no-messages">{c.noMessagesHelp}</p>:messages.map(message=>{const date=chatDate(message.created_at||message.createdAt),day=chatDayKey(date),divider=!!day&&day!==previousDay;previousDay=day;const own=!!profileId&&chatText(message.senderProfileId)===profileId,delivery=chatDelivery(message),media=chatMediaUrl(message.mediaUrl);return <div className="chat-message-group" key={chatText(message.id)}>{divider&&<div className="chat-date-divider"><span/><time>{chatDay(message.created_at||message.createdAt,locale)}</time><span/></div>}<div className={`chat-message-row ${own?'outgoing':'incoming'}`}><div className="chat-message-cluster">{!own&&<ChatAvatar item={active} locale={locale} className="chat-message-avatar"/>}<div className={`chat-bubble ${own?'outgoing':'incoming'}`}>
            {media?(chatImage(media)?failedMedia[media]?<span className="chat-unavailable-media"><span>{x.unavailable}</span><small>{chatText(message.body)||c.photo}</small><button type="button" onClick={()=>setFailedMedia(previous=>({...previous,[media]:false}))}>{x.retry}</button></span>:<button className="chat-message-media" type="button" aria-label={c.attachment} onClick={()=>setImage(media)}><img src={media} alt={chatText(message.body)||c.photo} onError={()=>setFailedMedia(previous=>({...previous,[media]:true}))} onLoad={()=>{if(stickBottom.current&&scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;}}/></button>:<a className="chat-file-attachment" href={media} target="_blank" rel="noopener noreferrer"><ChatIcon name="paperclipIcon"/><span>{chatText(message.body)||x.file}</span></a>):<div className="chat-message-body">{chatText(message.body)}</div>}
            {date&&<div className="chat-message-meta"><time dateTime={date.toISOString()}>{chatTime(date.toISOString(),locale)}</time>{own&&<svg className={`chat-message-status ${delivery}`} viewBox="0 0 16 11" role="img" aria-label={{sent:c.messageSent,delivered:c.messageDelivered,read:c.messageRead}[delivery]}><path d="M11.071 0.929 4.5 7.5 1.929 4.929"/>{delivery!=='sent'&&<path d="M14.071 0.929 7.5 7.5"/>}</svg>}</div>}
          </div></div></div></div>;})}
        </div></div>
        {active&&<div className="chat-compose-wrap" ref={compose}>{emoji&&<ChatEmoji locale={locale} onClose={()=>{setEmoji(false);input.current?.focus();}} onSelect={value=>{const start=input.current?.selectionStart??body.length,end=input.current?.selectionEnd??start;setBody(body.slice(0,start)+value+body.slice(end));setEmoji(false);requestAnimationFrame(()=>{input.current?.focus();input.current?.setSelectionRange(start+value.length,start+value.length);});}}/>}<form className="chat-compose" onSubmit={event=>{event.preventDefault();send();}}><button className="chat-tool chat-emoji" type="button" aria-label={c.emoji} aria-expanded={emoji} disabled={busy} onClick={()=>setEmoji(!emoji)}><ChatIcon name="smileIcon"/></button><button className="chat-tool chat-attachment" type="button" aria-label={c.attachment} disabled={busy} onClick={()=>attachment.current?.click()}><ChatIcon name="paperclipIcon"/></button><input ref={attachment} className="chat-file-input" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" tabIndex={-1} onChange={event=>{const pending=event.target.files?.[0];event.target.value='';if(!pending)return;const problem=chatAttachmentError(pending,locale);if(problem)setError(problem);else{setError('');setFile(pending);}}}/><textarea ref={input} rows={1} maxLength={4000} value={body} aria-label={c.messagesTitle} placeholder={c.writeMessage} onChange={event=>setBody(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();send();}}}/><button className="chat-send" type="submit" disabled={busy||!body.trim()} aria-label={busy?x.sending:c.send}><ChatIcon name="sendIcon"/></button></form></div>}
      </div>}
    </section>
  </section>
  {(dialog==='delete'||dialog==='block')&&<Overlay fullViewport className={`block-confirm-modal chat-${dialog}-confirm-modal`} label={dialog==='delete'?c.deleteTitle:c.blockUser} close={close} busy={busy}><div className="block-confirm-backdrop" onClick={close}/><section className="block-confirm-dialog"><button className="block-confirm-close" aria-label={c.close} disabled={busy} onClick={close}><ChatIcon name="closeIcon"/></button><h2>{dialog==='delete'?c.deleteTitle:`${c.blockConfirmLabel} ${active?chatName(active,locale):''}?`}</h2><p>{dialog==='delete'?c.deleteBody:c.blockConfirmBody}</p>{feedback}<div className="block-confirm-actions"><button className="soft-button" disabled={busy} onClick={close}>{c.blockConfirmCancel}</button><button className="danger-primary" disabled={busy} onClick={mutate}>{dialog==='delete'?c.deleteConfirm:c.blockConfirmAction}</button></div></section></Overlay>}
  {dialog==='report'&&<Overlay className="profile-dialog report-dialog chat-report-dialog" label={c.reportTitle} close={close} busy={busy} initialFocus="select"><div className="profile-dialog-backdrop" onClick={close}/><section className="profile-dialog-panel"><div className="profile-dialog-head"><h2>{c.reportTitle}</h2><button aria-label={c.close} disabled={busy} onClick={close}><ChatIcon name="closeIcon"/></button></div><form className="report-dialog-form" onSubmit={event=>{event.preventDefault();mutate();}}><label className="report-field"><span>{c.reportReason}</span><select required value={reason} disabled={busy} onChange={event=>setReason(event.target.value)}><option disabled value="">{c.reportChoose}</option>{CHAT_REPORT_REASONS[locale].map(value=><option key={value}>{value}</option>)}</select></label><label className="report-field"><span>{c.reportDetails}</span><textarea rows={4} maxLength={4000} value={details} disabled={busy} placeholder={c.reportPlaceholder} onChange={event=>setDetails(event.target.value)}/></label>{feedback}<div className="report-dialog-actions"><button type="button" className="soft-button" disabled={busy} onClick={close}>{c.reportCancel}</button><button type="submit" className="primary danger-primary" disabled={busy||!reason}>{c.reportSubmit}</button></div></form></section></Overlay>}
  {dialog==='premium'&&<AccountPremium locale={locale} close={close}/>}
  {dialog==='verify'&&<Overlay className="profile-dialog verification-prompt-dialog" label={c.verifyProfile} close={close}><div className="profile-dialog-backdrop" onClick={close}/><section className="profile-dialog-panel"><h2>{c.verifyProfile}</h2><p>{c.verifyBody}</p><div className="profile-dialog-actions"><button className="soft-button" onClick={close}>{c.notNow}</button><Link className="primary" to={`/${locale}/profile/verification`}>{c.verifyNow}</Link></div></section></Overlay>}
  {file&&<Overlay className="chat-attachment-preview" label={c.attachment} close={()=>{if(!actionFlight.current)setFile(null);}} busy={busy}><section className="chat-attachment-preview-card"><div className="chat-attachment-preview-media">{fileUrl?<img src={fileUrl} alt={file.name}/>:<span className="chat-attachment-preview-file"><ChatIcon name="paperclipIcon"/></span>}</div>{feedback}<div className="chat-attachment-preview-footer"><span className="chat-attachment-preview-copy"><strong>{file.name}</strong><small>{chatFileSize(file.size)}</small></span><button className="chat-attachment-preview-cancel" disabled={busy} aria-label={c.close} onClick={()=>setFile(null)}>×</button><button className="chat-attachment-preview-send" disabled={busy} aria-label={busy?x.sending:c.send} onClick={sendAttachment}><ChatIcon name="sendIcon"/></button></div></section></Overlay>}
  {image&&<Overlay className="chat-image-lightbox" label={c.attachment} close={()=>setImage('')}><img src={image} alt={c.photo}/><button className="chat-image-lightbox-close" aria-label={c.close} onClick={()=>setImage('')}>×</button></Overlay>}
  </div>;
}
