export const CHAT_COPY = {
  "en": {
    "messagesTitle": "Messages",
    "searchConversations": "Search conversations...",
    "noSearchConversations": "No conversations yet",
    "noConversations": "No conversations yet. Use Message on a profile to start one.",
    "selectConversation": "Select a conversation to start messaging",
    "backConversations": "Back to conversations",
    "secureChat": "",
    "loadingMessages": "",
    "noMessages": "No messages yet",
    "noMessagesHelp": "No messages yet. Start the conversation below.",
    "chooseConversation": "Choose a conversation.",
    "chooseFirst": "Choose a conversation first.",
    "writeMessage": "Type a message...",
    "emoji": "Add emoji",
    "attachment": "Attach file",
    "send": "Send",
    "photo": "Photo",
    "today": "Today",
    "you": "You",
    "support": "Support",
    "member": "LetsBeParents member",
    "close": "Close",
    "report": "Report",
    "blockUser": "Block user",
    "attachmentTooLarge": "The attachment must be no larger than 10 MB.",
    "attachmentFailed": "Could not send the attachment.",
    "messageSent": "Sent",
    "messageDelivered": "Delivered",
    "messageRead": "Read",
    "blockConfirmCancel": "Cancel",
    "blockConfirmAction": "Block",
    "blockConfirmLabel": "Block",
    "blockConfirmBody": "This user will not be able to see your profile, send you messages, or find you in search. You can unblock them later.",
    "reportTitle": "Report profile",
    "reportReason": "Reason",
    "reportDetails": "Description",
    "reportPlaceholder": "Provide additional details (optional)",
    "reportChoose": "Select a reason",
    "reportSubmit": "Submit report",
    "reportCancel": "Close",
    "reportSent": "Report sent to moderation.",
    "verifyProfile": "Profile verification",
    "verifyBody": "To keep our community safe, profile photo verification is required. It's free, fast, and no documents are needed — just a quick selfie.",
    "verifyNow": "Start verification",
    "notNow": "Not now",
    "viewProfile": "View profile",
    "deleteChat": "Delete chat",
    "deleteTitle": "Delete chat?",
    "deleteBody": "Chat will reappear if you receive a new message or start the conversation again.",
    "deleteConfirm": "Delete",
    "deleted": "Chat deleted.",
    "voiceCall": "Voice call",
    "videoCall": "Video call",
    "callsUnavailable": "Calls are not available yet.",
    "actions": "Chat actions",
    "call": {
      "incomingVoice": "Incoming voice call",
      "incomingVideo": "Incoming video call",
      "calling": "Calling…",
      "connecting": "Connecting…",
      "connected": "Connected",
      "accept": "Accept",
      "decline": "Decline",
      "end": "End call",
      "microphone": "Microphone",
      "camera": "Camera",
      "requestingMicrophone": "Allow microphone access in the browser request",
      "requestingCamera": "Allow camera access in the browser request",
      "microphoneUnavailable": "Microphone access is denied. Allow it in your browser settings and try again.",
      "cameraUnavailable": "Camera access is denied. Allow it in your browser settings to enable video.",
      "connectionFailed": "Unable to connect the call. Try again.",
      "unavailable": "Calls are temporarily unavailable."
    }
  },
  "ru": {
    "messagesTitle": "Сообщения",
    "searchConversations": "Поиск бесед",
    "noSearchConversations": "Пока нет бесед",
    "noConversations": "Диалогов пока нет. Откройте профиль и нажмите «Написать».",
    "selectConversation": "Выберите диалог, чтобы начать общение",
    "backConversations": "Назад к диалогам",
    "secureChat": "",
    "loadingMessages": "",
    "noMessages": "Сообщений пока нет",
    "noMessagesHelp": "Сообщений пока нет. Начните диалог ниже.",
    "chooseConversation": "Выберите диалог.",
    "chooseFirst": "Сначала выберите диалог.",
    "writeMessage": "Напишите сообщение...",
    "emoji": "Добавить эмодзи",
    "attachment": "Прикрепить файл",
    "send": "Отправить",
    "photo": "Фото",
    "today": "Сегодня",
    "you": "Вы",
    "support": "Поддержка",
    "member": "Участник LetsBeParents",
    "close": "Закрыть",
    "report": "Пожаловаться",
    "blockUser": "Заблокировать",
    "attachmentTooLarge": "Размер вложения не должен превышать 10 МБ.",
    "attachmentFailed": "Не удалось отправить вложение.",
    "messageSent": "Отправлено",
    "messageDelivered": "Доставлено",
    "messageRead": "Прочитано",
    "blockConfirmCancel": "Отмена",
    "blockConfirmAction": "Заблокировать",
    "blockConfirmLabel": "Заблокировать",
    "blockConfirmBody": "Этот пользователь не сможет видеть ваш профиль, писать вам сообщения или находить вас в поиске. Разблокировать можно позже.",
    "reportTitle": "Пожаловаться на профиль",
    "reportReason": "Причина",
    "reportDetails": "Описание",
    "reportPlaceholder": "Укажите дополнительные детали (необязательно)",
    "reportChoose": "Выберите причину",
    "reportSubmit": "Отправить жалобу",
    "reportCancel": "Закрыть",
    "reportSent": "Жалоба отправлена модератору.",
    "verifyProfile": "Верификация профиля",
    "verifyBody": "Чтобы наше сообщество оставалось безопасным, необходимо пройти верификацию фото профиля. Это бесплатно, быстро и без документов — нужно лишь быстрое селфи.",
    "verifyNow": "Пройти верификацию",
    "notNow": "Не сейчас",
    "viewProfile": "Посмотреть профиль",
    "deleteChat": "Удалить чат",
    "deleteTitle": "Удалить этот чат?",
    "deleteBody": "Диалог исчезнет из списка. Если придёт новое сообщение, он появится снова.",
    "deleteConfirm": "Удалить",
    "deleted": "Чат удалён.",
    "voiceCall": "Аудиозвонок",
    "videoCall": "Видеозвонок",
    "callsUnavailable": "Звонки пока недоступны.",
    "actions": "Действия с чатом",
    "call": {
      "incomingVoice": "Входящий аудиозвонок",
      "incomingVideo": "Входящий видеозвонок",
      "calling": "Вызов…",
      "connecting": "Подключение…",
      "connected": "Соединено",
      "accept": "Принять",
      "decline": "Отклонить",
      "end": "Завершить",
      "microphone": "Микрофон",
      "camera": "Камера",
      "requestingMicrophone": "Разрешите доступ к микрофону в запросе браузера",
      "requestingCamera": "Разрешите доступ к камере в запросе браузера",
      "microphoneUnavailable": "Доступ к микрофону запрещён. Разрешите его в настройках браузера и повторите звонок.",
      "cameraUnavailable": "Доступ к камере запрещён. Разрешите его в настройках браузера, чтобы включить видео.",
      "connectionFailed": "Не удалось подключить звонок. Попробуйте ещё раз.",
      "unavailable": "Звонки временно недоступны."
    }
  },
  "es": {
    "messagesTitle": "Mensajes",
    "searchConversations": "Buscar conversaciones...",
    "noSearchConversations": "Aún no hay conversaciones",
    "noConversations": "Aún no hay conversaciones. Usa Mensaje en un perfil para iniciar una.",
    "selectConversation": "Selecciona una conversación para empezar",
    "backConversations": "Volver a conversaciones",
    "secureChat": "",
    "loadingMessages": "",
    "noMessages": "Aún no hay mensajes",
    "noMessagesHelp": "Aún no hay mensajes. Inicia la conversación abajo.",
    "chooseConversation": "Selecciona una conversación.",
    "chooseFirst": "Selecciona primero una conversación.",
    "writeMessage": "Escribe un mensaje...",
    "emoji": "Añadir emoji",
    "attachment": "Adjuntar archivo",
    "send": "Enviar",
    "photo": "Foto",
    "today": "Hoy",
    "you": "Tú",
    "support": "Soporte",
    "member": "Miembro de LetsBeParents",
    "close": "Cerrar",
    "report": "Reportar",
    "blockUser": "Bloquear",
    "attachmentTooLarge": "El archivo no debe superar los 10 MB.",
    "attachmentFailed": "No se pudo enviar el archivo.",
    "messageSent": "Enviado",
    "messageDelivered": "Entregado",
    "messageRead": "Leído",
    "blockConfirmCancel": "Cancelar",
    "blockConfirmAction": "Bloquear",
    "blockConfirmLabel": "Bloquear",
    "blockConfirmBody": "Este usuario ya no podrá ver tu perfil, escribirte ni encontrarte en la búsqueda. Podrás desbloquearlo más tarde.",
    "reportTitle": "Reportar perfil",
    "reportReason": "Motivo",
    "reportDetails": "Descripción",
    "reportPlaceholder": "Añade detalles adicionales (opcional)",
    "reportChoose": "Elige un motivo",
    "reportSubmit": "Enviar reporte",
    "reportCancel": "Cerrar",
    "reportSent": "Reporte enviado a moderación.",
    "verifyProfile": "Verificación del perfil",
    "verifyBody": "Para mantener segura nuestra comunidad, es necesario verificar la foto del perfil. Es gratis, rápido y no requiere documentos: solo un selfie rápido.",
    "verifyNow": "Iniciar verificación",
    "notNow": "Ahora no",
    "viewProfile": "Ver perfil",
    "deleteChat": "Eliminar chat",
    "deleteTitle": "¿Eliminar este chat?",
    "deleteBody": "Esta conversación desaparecerá de tu lista. Volverá a aparecer si llega un mensaje nuevo.",
    "deleteConfirm": "Eliminar",
    "deleted": "Chat eliminado.",
    "voiceCall": "Llamada de voz",
    "videoCall": "Videollamada",
    "callsUnavailable": "Las llamadas aún no están disponibles.",
    "actions": "Acciones del chat",
    "call": {
      "incomingVoice": "Llamada de voz entrante",
      "incomingVideo": "Videollamada entrante",
      "calling": "Llamando…",
      "connecting": "Conectando…",
      "connected": "Conectado",
      "accept": "Aceptar",
      "decline": "Rechazar",
      "end": "Finalizar",
      "microphone": "Micrófono",
      "camera": "Cámara",
      "requestingMicrophone": "Permite el acceso al micrófono en la solicitud del navegador",
      "requestingCamera": "Permite el acceso a la cámara en la solicitud del navegador",
      "microphoneUnavailable": "El acceso al micrófono está denegado. Permítelo en la configuración del navegador e inténtalo de nuevo.",
      "cameraUnavailable": "El acceso a la cámara está denegado. Permítelo en la configuración del navegador para activar el video.",
      "connectionFailed": "No se pudo conectar la llamada. Inténtalo de nuevo.",
      "unavailable": "Las llamadas no están disponibles temporalmente."
    }
  }
} as const;
export const CHAT_ICONS: Record<string,string> = {
  "supportIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 14v-2a8 8 0 0 1 16 0v2\"></path><path d=\"M18 19h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3v4a3 3 0 0 1-3 3Z\"></path><path d=\"M6 19h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H4v4a3 3 0 0 0 3 3Z\"></path></svg>",
  "messageIcon": "<svg class=\"action-icon message-action-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7A8.38 8.38 0 0 1 4 11.5a8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5Z\"></path></svg>",
  "pageBackIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"m12 19-7-7 7-7\"></path><path d=\"M19 12H5\"></path></svg>",
  "phoneIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.79 19.79 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.69 2.8a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.9.33 1.84.56 2.8.69A2 2 0 0 1 22 16.92Z\"></path></svg>",
  "videoIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"m22 8-6 4 6 4V8Z\"></path><rect x=\"2\" y=\"6\" width=\"14\" height=\"12\" rx=\"2\"></rect></svg>",
  "moreVerticalIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"12\" cy=\"5\" r=\"1\"></circle><circle cx=\"12\" cy=\"12\" r=\"1\"></circle><circle cx=\"12\" cy=\"19\" r=\"1\"></circle></svg>",
  "userProfileIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"12\" cy=\"8\" r=\"4\"></circle><path d=\"M4 22a8 8 0 0 1 16 0\"></path></svg>",
  "trashIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M3 6h18\"></path><path d=\"M8 6V4h8v2\"></path><path d=\"m19 6-1 14H6L5 6\"></path><path d=\"M10 11v5\"></path><path d=\"M14 11v5\"></path></svg>",
  "flagIcon": "<svg class=\"action-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 22V4\"></path><path d=\"M5 4h11l-1 4 1 4H5\"></path></svg>",
  "banIcon": "<svg class=\"action-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"12\" cy=\"12\" r=\"9\"></circle><path d=\"m5.6 5.6 12.8 12.8\"></path></svg>",
  "smileIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><path d=\"M8 14s1.5 2 4 2 4-2 4-2\"></path><path d=\"M9 9h.01\"></path><path d=\"M15 9h.01\"></path></svg>",
  "paperclipIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l9.19-9.19a4 4 0 0 1 5.66 5.66l-9.2 9.19a2 2 0 0 1-2.83-2.83l8.49-8.48\"></path></svg>",
  "sendIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"m22 2-7 20-4-9-9-4Z\"></path><path d=\"M22 2 11 13\"></path></svg>",
  "microphoneIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><rect x=\"9\" y=\"2\" width=\"6\" height=\"12\" rx=\"3\"></rect><path d=\"M5 10a7 7 0 0 0 14 0M12 17v5M8 22h8\"></path></svg>",
  "closeIcon": "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M18 6 6 18\"></path><path d=\"m6 6 12 12\"></path></svg>"
};
