export const PRICING_TEXT = {
  en: {
    eyebrow: "PRICING",
    title: "Find the right person to build a family with.",
    intro: "Better matches. Deeper compatibility. More confidence. Start free, upgrade when you're ready to go deeper.",
    plans: [
      {
        key: "explore", name: "Explore", price: "€0", priceNote: "Free forever", altNote: "",
        tagline: "Create your profile and start discovering.",
        features: ["Full profile & basic discovery", "5 likes per day", "Basic matching"],
        cta: "Get started free", badge: "",
      },
      {
        key: "familyBuilder", name: "Family Builder", price: "€24.99", priceNote: "per month, billed monthly",
        altNote: "or €49.99 for 3 months - €16.66/month, save 33%",
        tagline: "For members ready to match with intention.",
        features: ["Compatibility Score & Why you match", "Advanced family filters", "See who liked you", "Video & audio calls", "15 likes/day, 5 reach-outs/day", "Priority in discovery"],
        cta: "Start Family Builder", badge: "Best value",
      },
      {
        key: "familyBuilderPro", name: "Family Builder Pro", price: "€29.99", priceNote: "per month", altNote: "",
        tagline: "Everything in Family Builder, plus deeper guidance.",
        features: ["Everything in Family Builder", "AI Family Advisor", "Detailed Compatibility Report", "Family Plan & Shared Family Room", "Document & checklist tools", "Priority support"],
        cta: "Go Pro", badge: "",
      },
    ],
    footnote: "Prices shown in EUR and may vary by region. Cancel anytime. Premium requires profile verification.",
    faqLinkLabel: "See how we verify members",
    compareTitle: "Compare all features",
    compareSub: "See exactly what's included in each plan.",
    matrixGroups: [
      { name: "Match better", rows: [
        { label: "Daily likes", values: ["5", "15", "Unlimited"] },
        { label: "Reach out first", values: ["", "5/day", "Unlimited"] },
        { label: "Advanced family filters", values: ["", "check", "check"] },
        { label: "Priority in catalog", values: ["", "check", "check"] },
        { label: "See who liked you", values: ["1", "check", "check"] },
        { label: "See profile visitors", values: ["2", "check", "check"] },
      ] },
      { name: "Understand compatibility", rows: [
        { label: "Compatibility Score", values: ["", "check", "check"] },
        { label: "Why you match", values: ["", "check", "check"] },
        { label: "Expanded profile info", values: ["", "check", "check"] },
        { label: "Verification info", values: ["", "check", "check"] },
      ] },
      { name: "Connect & communicate", rows: [
        { label: "Video & audio calls", values: ["", "check", "check"] },
        { label: "Private photos", values: ["", "check", "check"] },
        { label: "Incognito mode", values: ["", "check", "check"] },
      ] },
      { name: "Build your family", rows: [
        { label: "Family Plan (shared)", values: ["", "Limited", "check"] },
        { label: "AI Family Advisor", values: ["", "", "check"] },
        { label: "Detailed Compatibility Report", values: ["", "", "check"] },
        { label: "Document & checklist tools", values: ["", "", "check"] },
        { label: "Priority support", values: ["", "", "check"] },
      ] },
    ],
  },
  ru: {
    eyebrow: "ЦЕНЫ",
    title: "Найдите того, с кем строить семью.",
    intro: "Более точные совпадения. Глубже совместимость. Больше уверенности. Начните бесплатно, обновитесь, когда будете готовы к большему.",
    plans: [
      {
        key: "explore", name: "Explore", price: "€0", priceNote: "Бесплатно навсегда", altNote: "",
        tagline: "Создайте профиль и начните знакомиться.",
        features: ["Полный профиль и базовый поиск", "5 лайков в день", "Базовый подбор пар"],
        cta: "Начать бесплатно", badge: "",
      },
      {
        key: "familyBuilder", name: "Family Builder", price: "€24.99", priceNote: "в месяц, ежемесячная оплата",
        altNote: "или €49.99 за 3 месяца - €16.66/мес, экономия 33%",
        tagline: "Для тех, кто готов искать пару осознанно.",
        features: ["Оценка совместимости и «почему вы подходите»", "Расширенные семейные фильтры", "Кто лайкнул вас", "Видео- и аудиозвонки", "15 лайков/день, 5 обращений/день", "Приоритет в поиске"],
        cta: "Начать Family Builder", badge: "Лучшая цена",
      },
      {
        key: "familyBuilderPro", name: "Family Builder Pro", price: "€29.99", priceNote: "в месяц", altNote: "",
        tagline: "Всё из Family Builder плюс более глубокое сопровождение.",
        features: ["Всё из Family Builder", "AI Family Advisor", "Подробный отчёт о совместимости", "Family Plan и общая комната семьи", "Документы и чек-листы", "Приоритетная поддержка"],
        cta: "Перейти на Pro", badge: "",
      },
    ],
    footnote: "Цены указаны в евро и могут отличаться в зависимости от региона. Отмена в любой момент. Premium доступен после верификации профиля.",
    faqLinkLabel: "Как мы проверяем участников",
    compareTitle: "Сравните все возможности",
    compareSub: "Точный список того, что включено в каждый тариф.",
    matrixGroups: [
      { name: "Больше совпадений", rows: [
        { label: "Лайки в день", values: ["5", "15", "Без ограничений"] },
        { label: "Первым написать", values: ["", "5 в день", "Без ограничений"] },
        { label: "Расширенные семейные фильтры", values: ["", "check", "check"] },
        { label: "Приоритет в каталоге", values: ["", "check", "check"] },
        { label: "Кто лайкнул вас", values: ["1", "check", "check"] },
        { label: "Кто смотрел профиль", values: ["2", "check", "check"] },
      ] },
      { name: "Понимание совместимости", rows: [
        { label: "Оценка совместимости", values: ["", "check", "check"] },
        { label: "Почему вы подходите", values: ["", "check", "check"] },
        { label: "Расширенная информация профиля", values: ["", "check", "check"] },
        { label: "Информация о верификации", values: ["", "check", "check"] },
      ] },
      { name: "Связь и общение", rows: [
        { label: "Видео- и аудиозвонки", values: ["", "check", "check"] },
        { label: "Приватные фото", values: ["", "check", "check"] },
        { label: "Режим инкогнито", values: ["", "check", "check"] },
      ] },
      { name: "Постройте свою семью", rows: [
        { label: "Семейный план (общий)", values: ["", "Ограниченно", "check"] },
        { label: "AI Family Advisor", values: ["", "", "check"] },
        { label: "Подробный отчёт о совместимости", values: ["", "", "check"] },
        { label: "Документы и чек-листы", values: ["", "", "check"] },
        { label: "Приоритетная поддержка", values: ["", "", "check"] },
      ] },
    ],
  },
  es: {
    eyebrow: "PRECIOS",
    title: "Encuentra a la persona adecuada para formar una familia.",
    intro: "Mejores matches. Mayor compatibilidad. Más confianza. Empieza gratis y mejora cuando quieras ir más allá.",
    plans: [
      {
        key: "explore", name: "Explore", price: "€0", priceNote: "Gratis para siempre", altNote: "",
        tagline: "Crea tu perfil y empieza a descubrir.",
        features: ["Perfil completo y descubrimiento básico", "5 likes al día", "Emparejamiento básico"],
        cta: "Empieza gratis", badge: "",
      },
      {
        key: "familyBuilder", name: "Family Builder", price: "€24.99", priceNote: "al mes, facturación mensual",
        altNote: "o €49.99 por 3 meses - €16.66/mes, ahorra 33%",
        tagline: "Para quienes buscan match con intención.",
        features: ["Puntuación de compatibilidad y «por qué haces match»", "Filtros familiares avanzados", "Ver quién te dio like", "Videollamadas y llamadas de audio", "15 likes/día, 5 contactos/día", "Prioridad en el descubrimiento"],
        cta: "Empezar Family Builder", badge: "Mejor precio",
      },
      {
        key: "familyBuilderPro", name: "Family Builder Pro", price: "€29.99", priceNote: "al mes", altNote: "",
        tagline: "Todo lo de Family Builder, con acompañamiento más profundo.",
        features: ["Todo lo de Family Builder", "AI Family Advisor", "Informe de compatibilidad detallado", "Family Plan y Sala Familiar Compartida", "Documentos y listas de verificación", "Soporte prioritario"],
        cta: "Pasar a Pro", badge: "",
      },
    ],
    footnote: "Los precios se muestran en EUR y pueden variar según la región. Cancela cuando quieras. Premium requiere verificación de perfil.",
    faqLinkLabel: "Cómo verificamos a los miembros",
    compareTitle: "Compara todas las funciones",
    compareSub: "Mira exactamente qué incluye cada plan.",
    matrixGroups: [
      { name: "Mejores coincidencias", rows: [
        { label: "Me gusta diarios", values: ["5", "15", "Ilimitado"] },
        { label: "Escribir primero", values: ["", "5/día", "Ilimitado"] },
        { label: "Filtros familiares avanzados", values: ["", "check", "check"] },
        { label: "Prioridad en el catálogo", values: ["", "check", "check"] },
        { label: "Ver quién te dio like", values: ["1", "check", "check"] },
        { label: "Ver visitantes del perfil", values: ["2", "check", "check"] },
      ] },
      { name: "Entender la compatibilidad", rows: [
        { label: "Puntuación de compatibilidad", values: ["", "check", "check"] },
        { label: "Por qué coincidís", values: ["", "check", "check"] },
        { label: "Información ampliada del perfil", values: ["", "check", "check"] },
        { label: "Información de verificación", values: ["", "check", "check"] },
      ] },
      { name: "Conectar y comunicarse", rows: [
        { label: "Videollamadas y llamadas de audio", values: ["", "check", "check"] },
        { label: "Fotos privadas", values: ["", "check", "check"] },
        { label: "Modo incógnito", values: ["", "check", "check"] },
      ] },
      { name: "Construye tu familia", rows: [
        { label: "Plan familiar (compartido)", values: ["", "Limitado", "check"] },
        { label: "AI Family Advisor", values: ["", "", "check"] },
        { label: "Informe de compatibilidad detallado", values: ["", "", "check"] },
        { label: "Documentos y listas de verificación", values: ["", "", "check"] },
        { label: "Soporte prioritario", values: ["", "", "check"] },
      ] },
    ],
  },
};
